import path from 'node:path';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  test: {
    environment: 'happy-dom',
    include: [
      'src/lib/clinic-lab-state.spec.ts',
      'src/lib/patient-chart.spec.ts',
      'src/lib/clinic-lab-queue.spec.ts',
      'src/lib/clinic-lab-specimens.spec.ts',
      'src/lib/clinic-lab-results.spec.ts',
      'src/lib/clinic-specimen-label.spec.ts',
      'src/lib/public-clinic-results.spec.ts',
      'src/lib/clinic-lab-booking-request.spec.ts',
      'src/components/clinic/clinic-lab-status-badge.integration.spec.tsx',
      'src/components/clinic/booking-lab-order-push-panel.integration.spec.tsx',
      'src/components/clinic/booking-lab-order-staff-book-controls.integration.spec.tsx',
      'src/components/clinic/booking-lab-orders-section.integration.spec.tsx',
      'src/components/clinic/clinic-specimen-label-print.integration.spec.tsx',
      'src/components/clinic/clinic-specimen-queue-panel.integration.spec.tsx',
      'src/components/clinic/clinic-admin-tabs.integration.spec.tsx',
      'src/components/clinic/booking-intake-section.integration.spec.tsx',
      'src/components/public-booking/public-checkout-intake-step.integration.spec.tsx',
      'src/components/patient-chart/patient-chart.integration.spec.tsx',
      'src/components/patient-chart/patient-chart-i18n.integration.spec.tsx',
      'src/components/patient-chart/patient-chart-catalog-order-panel.integration.spec.tsx',
      'src/app/(dashboard)/dashboard/lab-queue/lab-queue.integration.spec.tsx',
      'src/components/public-booking/public-my-results-section.integration.spec.tsx',
      'src/components/clinic/results-action-history-modal.integration.spec.tsx',
      'src/components/public-booking/public-my-lab-booking-requests-section.integration.spec.tsx',
      'src/components/public-booking/public-patient-alerts-banner.integration.spec.tsx',
    ],
    coverage: {
      provider: 'v8',
      include: [
        'src/lib/clinic-lab-state.ts',
        'src/lib/patient-chart.ts',
        'src/lib/patient-chart-catalog-order.ts',
        'src/components/patient-chart/patient-chart-catalog-order-panel.tsx',
        'src/components/patient-chart/patient-chart-orders-tab.tsx',
        'src/lib/clinic-lab-queue.ts',
        'src/lib/clinic-lab-specimens.ts',
        'src/lib/clinic-lab-results.ts',
        'src/lib/clinic-specimen-label.ts',
        'src/lib/public-clinic-results.ts',
        'src/lib/clinic-lab-booking-request.ts',
        'src/components/clinic/clinic-lab-status-badge.tsx',
        'src/components/clinic/booking-lab-order-push-panel.tsx',
        'src/components/clinic/booking-lab-order-staff-book-controls.tsx',
        'src/components/clinic/booking-lab-results-section.tsx',
        'src/components/clinic/results-action-history-modal.tsx',
        'src/lib/clinic-lab-results.ts',
        'src/components/clinic/clinic-specimen-barcode.tsx',
        'src/components/clinic/clinic-specimen-label-sheet.tsx',
        'src/components/clinic/clinic-specimen-label-print-modal.tsx',
        'src/components/clinic/clinic-specimen-queue-panel.tsx',
        'src/components/clinic/clinic-specimen-ops-nav.tsx',
        'src/components/public-booking/public-my-results-section.tsx',
        'src/components/public-booking/public-my-lab-booking-requests-section.tsx',
        'src/components/public-booking/public-patient-alerts-banner.tsx',
        'src/lib/clinic-patient-alerts.ts',
        'src/components/clinic/booking-lab-orders-section.tsx',
        'src/components/clinic/clinic-catalog-order-picker.tsx',
      ],
      reportsDirectory: './coverage/sprint54',
      thresholds: {
        statements: 98,
        branches: 85,
        functions: 96,
        lines: 98,
      },
    },
  },
});
