#!/usr/bin/env python3
"""Generate similar-app-guide-prompts.generated.ts (ai-guide-1.6.2)."""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = Path(__file__).resolve().parent / "similar-app-guide-prompts.data.py"
OUT = ROOT / "src/modules/ai/similar-app-guide-prompts.generated.ts"


def load_data():
    spec = importlib.util.spec_from_file_location("similar_app_guide_prompts_data", DATA)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod.FLOWS, mod.PROMPTS


def main() -> None:
    flows_by_surface, prompts = load_data()
    flows_out: list[dict[str, str]] = []
    prompts_out: list[dict[str, str]] = []

    for surface, flows in flows_by_surface.items():
        if len(flows) != 20:
            raise SystemExit(f"{surface} must have 20 flows, got {len(flows)}")
        for flow in flows:
            flow_id = flow["id"]
            topic_id = flow["topicId"]
            variants = prompts.get(flow_id)
            if not variants or len(variants) < 10:
                n = 0 if not variants else len(variants)
                raise SystemExit(f"{flow_id} needs >=10 prompts, got {n}")
            flows_out.append({"id": flow_id, "surface": surface, "topicId": topic_id})
            for idx, prompt in enumerate(variants[:10], start=1):
                prompts_out.append(
                    {
                        "id": f"{surface}-{flow_id}-v{idx:02d}",
                        "surface": surface,
                        "topicId": topic_id,
                        "prompt": prompt,
                    }
                )

    lines = [
        "/** Generated by scripts/generate-similar-app-guide-prompts.py — ai-guide-1.6.2 */",
        "import type { CommandSurface } from './ai-command-registry.types.js';",
        "",
        "export interface TopAppGuideFlowDef {",
        "  id: string;",
        "  surface: CommandSurface;",
        "  topicId: string;",
        "}",
        "",
        "export interface SimilarAppGuidePrompt {",
        "  id: string;",
        "  surface: CommandSurface;",
        "  topicId: string;",
        "  prompt: string;",
        "}",
        "",
        f"export const TOP_APP_GUIDE_FLOWS: readonly TopAppGuideFlowDef[] = {json.dumps(flows_out, ensure_ascii=False, indent=2)} as const;",
        "",
        f"export const SIMILAR_APP_GUIDE_PROMPTS: readonly SimilarAppGuidePrompt[] = {json.dumps(prompts_out, ensure_ascii=False, indent=2)} as const;",
        "",
    ]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(flows_out)} flows, {len(prompts_out)} prompts)")


if __name__ == "__main__":
    main()
