/**
 * AI-ROADMAP Phase 1 - seventh domain slice: `clinic` (registry
 * `clinic-test-results`).
 *
 * 41 registry entries across **seven handlers**: lab booking, provider tasks,
 * results, orders, catalogue, consumer results and specimen collection. 20
 * reads, 21 mutations.
 *
 * The compensation reasoning here is medical rather than commercial, and splits
 * three ways:
 *
 * - **append-only records.** `enter_test_result` and `upload_patient_result`
 *   write to the medical record. A correction is a new entry; erasure is not
 *   available and would not be lawful.
 * - **chain of custody.** `mark_specimen_collected` and `transition_specimen`
 *   are audit trail. Reversing a step would falsify the trail, which is the
 *   opposite of what it is for.
 * - **released to the patient.** `release_test_result` has reached the person
 *   it concerns.
 *
 * `book_lab_collection` is registered READ despite the verb; the handler returns
 * a `bookUrl` and the pending requests, and the writes are
 * `staff_book_lab_collection` and `book_lab_from_order`. Checked, not assumed.
 */
import type { CommandSpec } from './ai-command-spec.types.js';

export const CLINIC_COMMAND_SPECS: readonly CommandSpec[] = [
  {
    id: 'clinic.book_lab_collection',
    aliases: ['book_lab_collection'],
    domain: 'clinic',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description:
      'Show the patient their pending lab requests and how to book collection. Returns a booking URL; creates nothing.',
    variables: {},
    examples: [
      'I need to book my blood test',
      'how do I book my lab collection',
    ],
    confirm: 'never',
    // Registered READ and correct: the handler returns `bookUrl` plus the
    // pending requests. `staff_book_lab_collection` and `book_lab_from_order`
    // are the writes.
    handler: 'AiClinicLabBookingService',
  },
  {
    id: 'clinic.explain_abnormal_result_flag',
    aliases: ['explain_abnormal_result_flag'],
    domain: 'clinic',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Explain why a result was flagged abnormal.',
    variables: {},
    examples: ['why is my result flagged', 'what does abnormal mean here'],
    confirm: 'never',
    handler: 'AiConsumerClinicTestResultsService',
  },
  {
    id: 'clinic.explain_task',
    aliases: ['explain_clinic_task'],
    domain: 'clinic',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain what a clinic task requires.',
    variables: {},
    examples: ['what is this task', 'explain this clinic task'],
    confirm: 'never',
    handler: 'AiProviderClinicTasksAndResultsService',
  },
  {
    id: 'clinic.explain_lab_result_history',
    aliases: ['explain_lab_result_history'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain how a patient results have changed over time.',
    variables: {},
    examples: ['how has this patient trended', 'show the result history'],
    confirm: 'never',
    handler: 'AiClinicTestResultService',
  },
  {
    id: 'clinic.explain_patient_results',
    aliases: ['explain_patient_results'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain a patient test results.',
    variables: {},
    examples: ['explain these results', 'what do the labs show'],
    confirm: 'never',
    handler: 'AiClinicTestResultService',
  },
  {
    id: 'clinic.explain_result_status',
    aliases: ['explain_result_status'],
    domain: 'clinic',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Report where a test result has got to.',
    variables: {},
    examples: ['are my results ready', 'what is the status of my test'],
    confirm: 'never',
    handler: 'AiConsumerClinicTestResultsService',
  },
  {
    id: 'clinic.explain_specimen_recollect',
    aliases: ['explain_specimen_recollect'],
    domain: 'clinic',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain why a specimen must be collected again.',
    variables: {},
    examples: ['why do we need another sample', 'explain the recollect'],
    confirm: 'never',
    handler: 'AiProviderClinicCollectionService',
  },
  {
    id: 'clinic.list_abnormal_results',
    aliases: ['list_abnormal_results'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List results outside their reference range.',
    variables: {},
    examples: ['what results are abnormal', 'show flagged results'],
    confirm: 'never',
    handler: 'AiClinicTestResultService',
  },
  {
    id: 'clinic.list_booking_lab_summaries',
    aliases: ['list_booking_lab_summaries'],
    domain: 'clinic',
    surfaces: ['provider', 'dashboard'],
    tiers: {
      provider: ['client', 'staff', 'manager', 'owner'],
      dashboard: ['staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Summarise the lab work attached to bookings.',
    variables: {},
    examples: [
      'what labs are on today bookings',
      'lab summary for my appointments',
    ],
    confirm: 'never',
    handler: 'AiProviderClinicTasksAndResultsService',
  },
  {
    id: 'clinic.list_tasks',
    aliases: ['list_clinic_tasks'],
    domain: 'clinic',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List outstanding clinic tasks.',
    variables: {},
    examples: ['what tasks do I have', 'show my clinic tasks'],
    confirm: 'never',
    handler: 'AiProviderClinicTasksAndResultsService',
  },
  {
    id: 'clinic.list_lab_results_queue',
    aliases: ['list_lab_results_queue'],
    domain: 'clinic',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List results waiting to be reviewed.',
    variables: {},
    examples: ['what results need reviewing', 'show the results queue'],
    confirm: 'never',
    handler: 'AiProviderClinicTasksAndResultsService',
  },
  {
    id: 'clinic.list_my_collection_queue',
    aliases: ['list_my_collection_queue'],
    domain: 'clinic',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List specimens this provider needs to collect.',
    variables: {},
    examples: ['what collections do I have', 'my specimen queue'],
    confirm: 'never',
    handler: 'AiProviderClinicCollectionService',
  },
  {
    id: 'clinic.list_my_documents',
    aliases: ['list_my_documents'],
    domain: 'clinic',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'List the clinical documents shared with the patient.',
    variables: {},
    examples: ['what documents do I have', 'show my clinic documents'],
    confirm: 'never',
    handler: 'AiConsumerClinicTestResultsService',
  },
  {
    id: 'clinic.list_my_lab_booking_requests',
    aliases: ['list_my_lab_booking_requests'],
    domain: 'clinic',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'List the lab bookings the patient has been asked to make.',
    variables: {},
    examples: ['what tests do I need to book', 'my pending lab requests'],
    confirm: 'never',
    handler: 'AiClinicLabBookingService',
  },
  {
    id: 'clinic.list_my_test_results',
    aliases: ['list_my_test_results'],
    domain: 'clinic',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'List the patient own test results.',
    variables: {},
    examples: ['show my test results', 'what were my results'],
    confirm: 'never',
    handler: 'AiConsumerClinicTestResultsService',
  },
  {
    id: 'clinic.list_patient_pending_lab_requests',
    aliases: ['list_patient_pending_lab_requests'],
    domain: 'clinic',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List lab requests a patient has not yet booked.',
    variables: {},
    examples: [
      'what has this patient not booked',
      'pending lab requests for them',
    ],
    confirm: 'never',
    handler: 'AiClinicLabBookingService',
  },
  {
    id: 'clinic.list_test_orders',
    aliases: ['list_test_orders'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List test orders that have been raised.',
    variables: {},
    examples: ['what tests have been ordered', 'list test orders'],
    confirm: 'never',
    handler: 'AiClinicTestOrderService',
  },
  {
    id: 'clinic.notify_patient_book_lab',
    aliases: ['notify_patient_book_lab'],
    domain: 'clinic',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description:
      'Prepare a prompt asking a patient to book their lab collection.',
    variables: {},
    examples: [
      'remind this patient to book their test',
      'nudge them about the blood test',
    ],
    confirm: 'never',
    handler: 'AiClinicLabBookingService',
  },
  {
    id: 'clinic.notify_when_results_ready',
    aliases: ['notify_when_results_ready'],
    domain: 'clinic',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Explain how the patient will be told when results arrive.',
    variables: {},
    examples: [
      'tell me when my results are in',
      'how will I know results are ready',
    ],
    confirm: 'never',
    handler: 'AiConsumerClinicTestResultsService',
  },
  {
    id: 'clinic.open_document',
    aliases: ['open_clinic_document'],
    domain: 'clinic',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Open a clinical document shared with the patient.',
    variables: {},
    examples: ['open my lab report', 'show me that document'],
    confirm: 'never',
    handler: 'AiConsumerClinicTestResultsService',
  },
  {
    id: 'clinic.track_lab_order_status',
    aliases: ['track_lab_order_status'],
    domain: 'clinic',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Track where a lab order has got to.',
    variables: {},
    examples: ['where is my lab order', 'track my test'],
    confirm: 'never',
    handler: 'AiConsumerClinicTestResultsService',
  },
  {
    id: 'clinic.book_lab_from_order',
    aliases: ['book_lab_from_order'],
    domain: 'clinic',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T1',
    description: 'Book a lab collection against an existing test order.',
    variables: {},
    examples: ['book the collection for my order', 'schedule my blood draw'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'The patient has been given an appointment and told about it; cancelling is a separate action.',
    },
    handler: 'AiClinicLabBookingService',
  },
  {
    id: 'clinic.staff_book_lab_collection',
    aliases: ['staff_book_lab_collection'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Book a lab collection on a patient behalf.',
    variables: {},
    examples: [
      'book the collection for this patient',
      'schedule their blood draw',
    ],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'The patient has been given an appointment and told about it; cancelling is a separate action.',
    },
    handler: 'AiClinicLabBookingService',
  },
  {
    id: 'clinic.push_lab_booking_to_patient',
    aliases: ['push_lab_booking_to_patient'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Send a patient a request to book their lab collection.',
    variables: {},
    examples: [
      'ask this patient to book their test',
      'send the lab booking request',
    ],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason: 'The request has been sent to the patient and cannot be unsent.',
    },
    handler: 'AiClinicLabBookingService',
  },
  {
    id: 'clinic.claim_task',
    aliases: ['claim_clinic_task'],
    domain: 'clinic',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Take ownership of a clinic task.',
    variables: {},
    examples: ['I will take that task', 'claim this task'],
    confirm: 'never',
    compensation: {
      kind: 'inverse',
      command: 'clinic.claim_task',
      captures: ['taskId', 'previousOwnerId'],
    },
    handler: 'AiProviderClinicTasksAndResultsService',
  },
  {
    id: 'clinic.complete_task',
    aliases: ['complete_clinic_task'],
    domain: 'clinic',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Mark a clinic task as done.',
    variables: {},
    examples: ['mark that task done', 'I have finished this task'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'clinic.complete_task',
      captures: ['taskId', 'previousStatus'],
    },
    handler: 'AiProviderClinicTasksAndResultsService',
  },
  {
    id: 'clinic.enter_test_result',
    aliases: ['enter_test_result'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T2',
    description: 'Record a test result against a patient.',
    variables: {},
    examples: ['enter the haemoglobin result', 'record these lab values'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'A clinical record is append-only; once written it is part of the medical record.',
    },
    handler: 'AiClinicTestResultService',
  },
  {
    id: 'clinic.upload_patient_result',
    aliases: ['upload_patient_result'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T2',
    description: 'Upload a result document to a patient record.',
    variables: {},
    examples: ['upload this lab report', 'attach the result PDF'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'A clinical record is append-only; once written it is part of the medical record.',
    },
    handler: 'AiClinicTestResultService',
  },
  {
    id: 'clinic.release_test_result',
    aliases: ['release_test_result'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T2',
    description: 'Release a test result to the patient.',
    variables: {},
    examples: [
      'release these results to the patient',
      'share the labs with them',
    ],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason: 'The result has reached the patient and cannot be recalled.',
    },
    handler: 'AiClinicTestResultService',
  },
  {
    id: 'clinic.transition_specimen',
    aliases: ['transition_specimen'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T2',
    description: 'Move a specimen to the next stage of processing.',
    variables: {},
    examples: [
      'mark the specimen as received',
      'move this sample to processing',
    ],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Specimen chain of custody is an audit trail; a correction is a new entry, not an erasure.',
    },
    handler: 'AiClinicTestResultService',
  },
  {
    id: 'clinic.mark_specimen_collected',
    aliases: ['mark_specimen_collected'],
    domain: 'clinic',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T2',
    description: 'Record that a specimen has been collected from the patient.',
    variables: {},
    examples: ['I have taken the sample', 'mark specimen collected'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Specimen chain of custody is an audit trail; a correction is a new entry, not an erasure.',
    },
    handler: 'AiProviderClinicCollectionService',
  },
  {
    id: 'clinic.configure_test_reference_range',
    aliases: ['configure_test_reference_range'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T1',
    description:
      'Set the normal range for a test, which decides what is flagged abnormal.',
    variables: {},
    examples: [
      'set the normal range for haemoglobin',
      'change the reference range',
    ],
    confirm: 'always',
    compensation: {
      kind: 'inverse',
      command: 'clinic.configure_test_reference_range',
      captures: ['testTypeId', 'previousRange'],
    },
    handler: 'AiClinicTestResultService',
  },
  {
    id: 'clinic.create_test_order',
    aliases: ['create_test_order'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T2',
    description: 'Order tests for a patient.',
    variables: {},
    examples: [
      'order a full blood count for this patient',
      'request these labs',
    ],
    confirm: 'always',
    compensation: {
      kind: 'manual',
      reason:
        'A test order may already have been sent to the lab and acted on; cancelling it is a clinical decision.',
    },
    handler: 'AiClinicTestOrderService',
  },
  {
    id: 'clinic.dismiss_patient_alert',
    aliases: ['dismiss_patient_alert'],
    domain: 'clinic',
    surfaces: ['dashboard', 'customer'],
    tiers: { dashboard: ['staff', 'manager', 'owner'], customer: ['client'] },
    risk: 'T1',
    description: 'Dismiss an alert raised on a patient record.',
    variables: {},
    examples: ['dismiss that alert', 'clear this patient flag'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'clinic.dismiss_patient_alert',
      captures: ['alertId', 'previousStatus'],
    },
    handler: 'AiConsumerClinicTestResultsService',
  },
  {
    id: 'clinic.create_test_type',
    aliases: ['create_test_type'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T1',
    description: 'Add a test to the clinic catalogue.',
    variables: {},
    examples: ['add a vitamin D test', 'create a new test type'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'clinic.delete_test_type',
      captures: ['testTypeId'],
    },
    handler: 'AiClinicTestCatalogService',
  },
  {
    id: 'clinic.update_test_type',
    aliases: ['update_test_type'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T1',
    description: 'Change a test in the clinic catalogue.',
    variables: {},
    examples: ['rename that test', 'change the test details'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'clinic.update_test_type',
      captures: ['testTypeId', 'previousValues'],
    },
    handler: 'AiClinicTestCatalogService',
  },
  {
    id: 'clinic.delete_test_type',
    aliases: ['delete_test_type'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T1',
    description: 'Remove a test from the clinic catalogue.',
    variables: {},
    examples: ['delete the old vitamin test', 'remove that test type'],
    confirm: 'always',
    compensation: {
      kind: 'manual',
      reason:
        'Existing orders and results reference the test type; recreating it does not restore those links.',
    },
    handler: 'AiClinicTestCatalogService',
  },
  {
    id: 'clinic.create_test_panel',
    aliases: ['create_test_panel'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T1',
    description: 'Create a panel grouping several tests ordered together.',
    variables: {},
    examples: [
      'create a routine bloods panel',
      'group these tests into a panel',
    ],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'manual',
      reason:
        'A panel may already have been used on orders; removing one needs an order check.',
    },
    handler: 'AiClinicTestCatalogService',
  },
  {
    id: 'clinic.update_test_panel',
    aliases: ['update_test_panel'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T1',
    description: 'Change a test panel - its name or description.',
    variables: {},
    examples: ['rename the bloods panel', 'update that panel'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'clinic.update_test_panel',
      captures: ['panelId', 'previousValues'],
    },
    handler: 'AiClinicTestCatalogService',
  },
  {
    id: 'clinic.set_test_panel_items',
    aliases: ['set_test_panel_items'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T1',
    description: 'Set which tests a panel contains.',
    variables: {},
    examples: [
      'add vitamin D to the bloods panel',
      'change what is in that panel',
    ],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'clinic.set_test_panel_items',
      captures: ['panelId', 'previousItems'],
    },
    handler: 'AiClinicTestCatalogService',
  },
  {
    id: 'clinic.import_catalog_csv',
    aliases: ['import_clinic_catalog_csv'],
    domain: 'clinic',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T3',
    description: 'Import a whole test catalogue from a CSV file.',
    variables: {},
    examples: ['import our test catalogue', 'upload the lab catalogue csv'],
    confirm: 'always',
    compensation: {
      kind: 'manual',
      reason:
        'Creates or updates many test types at once; unwinding needs per-row pre-state.',
    },
    handler: 'AiClinicTestCatalogService',
  },
] as const;
