/**
 * AI-ROADMAP Phase 1 - fourth domain slice: `customer`.
 *
 * 34 registry entries under `apiModule: 'customer-crm'`: 19 reads, 15 mutations.
 * Where the payment slice exercised the money half of T2, this one exercises the
 * **PII** half - `delete_customer_data`, `privacy_delete`, `privacy_export`,
 * `export_customer_data`, `merge_customers`.
 *
 * The compensation declarations here are blunt, and should be. An export has
 * left the building; erasure is the point of the command; a merge folds two
 * histories together without recording the seam. None is reversible in the sense
 * a saga needs, and pretending otherwise would be worse than useless - Phase 5's
 * `partially_rolled_back` exists to say so.
 *
 * Note the surface split: the same capability appears twice, once for staff
 * acting on someone else (`customer.export_data`, manager+) and once for the
 * person themselves (`customer.privacy_export`, client). They are separate
 * registry entries and stay separate specs, because the actor differs and so
 * does the tier.
 */
import type { CommandSpec } from './ai-command-spec.types.js';

export const CUSTOMER_COMMAND_SPECS: readonly CommandSpec[] = [
  {
    id: 'customer.no_show_history',
    aliases: ['customer_no_show_history'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T0',
    description: 'Report how often a customer has failed to attend.',
    variables: {},
    examples: [
      'how many no shows has Gevorg had',
      'show me this customer no show history',
    ],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.discover_gift_card_products',
    aliases: ['discover_gift_card_products'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'List the gift cards available to buy.',
    variables: {},
    examples: ['what gift cards do you sell', 'show me gift card options'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.discover_packages',
    aliases: ['discover_packages'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'List the packages available to buy.',
    variables: {},
    examples: ['what packages do you offer', 'show me your bundles'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.discover_subscription_plans',
    aliases: ['discover_subscription_plans'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'List the subscription plans available to join.',
    variables: {},
    examples: ['what memberships do you have', 'show me subscription options'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.explain_gift_card_order',
    aliases: ['explain_gift_card_order'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Explain the status and contents of a gift card order.',
    variables: {},
    examples: [
      'what happened to my gift card order',
      'explain my gift card purchase',
    ],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.explain_my_subscription',
    aliases: ['explain_my_subscription'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description:
      'Explain what the customer subscription includes and when it renews.',
    variables: {},
    examples: [
      'what does my membership include',
      'when does my subscription renew',
    ],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.get_my_locale',
    aliases: ['get_my_locale'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Report the language the customer is currently set to.',
    variables: {},
    examples: ['what language am I set to', 'which locale do I have'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.gift_card_balance',
    aliases: ['gift_card_balance'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Report the balance of a gift card the customer holds.',
    variables: {},
    examples: ['how much is on my gift card', 'my gift card balance'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.gift_card_redemption_history',
    aliases: ['gift_card_redemption_history'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'List where and when a gift card has been spent.',
    variables: {},
    examples: [
      'where have I used my gift card',
      'gift card redemption history',
    ],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.list_bookings',
    aliases: ['list_customer_bookings'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T0',
    description: 'List the bookings belonging to a specific customer.',
    variables: {},
    examples: ['show me Gevorg bookings', 'list this customer appointments'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.list_gift_cards',
    aliases: ['list_customer_gift_cards'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T0',
    description: 'List the gift cards held by a specific customer.',
    variables: {},
    examples: [
      'what gift cards does Gevorg have',
      'list this customer gift cards',
    ],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.list_subscriptions',
    aliases: ['list_customer_subscriptions'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T0',
    description: 'List the subscriptions held by a specific customer.',
    variables: {},
    examples: ['what plan is Gevorg on', 'list this customer subscriptions'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.my_appointments',
    aliases: ['my_appointments'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description:
      'List the upcoming appointments belonging to the requesting customer.',
    variables: {},
    examples: ['what are my appointments', 'when is my next booking'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.my_gift_cards',
    aliases: ['my_gift_cards'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'List the gift cards belonging to the requesting customer.',
    variables: {},
    examples: ['what gift cards do I have', 'show my gift cards'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.my_profile',
    aliases: ['my_profile'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Show the profile details of the requesting customer.',
    variables: {},
    examples: ['show my profile', 'what details do you have for me'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.my_subscriptions',
    aliases: ['my_subscriptions'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'List the subscriptions belonging to the requesting customer.',
    variables: {},
    examples: ['what am I subscribed to', 'show my memberships'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.subscription_usage',
    aliases: ['subscription_usage'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description:
      'Report how much of a subscription allowance the customer has used.',
    variables: {},
    examples: ['how many visits do I have left', 'my subscription usage'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.subscription_usage_history',
    aliases: ['subscription_usage_history'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T0',
    description: 'Report subscription usage across customers over time.',
    variables: {},
    examples: ['how are subscriptions being used', 'subscription usage report'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.track_physical_gift_card_order',
    aliases: ['track_physical_gift_card_order'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Report the delivery status of a physical gift card order.',
    variables: {},
    examples: ['where is my physical gift card', 'track my gift card delivery'],
    confirm: 'never',
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.cancel_subscription_admin',
    aliases: ['cancel_subscription_admin'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T2',
    description: 'Cancel a subscription on the customer behalf.',
    variables: {
      customerName: {
        type: 'string',
        description: 'Customer whose subscription to cancel.',
        required: true,
        resolver: 'customer',
      },
    },
    examples: ['cancel Gevorg membership', 'end this customer subscription'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Cancelling stops billing and notifies the customer; resubscribing is a new agreement, not an undo.',
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.claim_gift_card_balance',
    aliases: ['claim_gift_card_balance'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T2',
    description: 'Claim a gift card balance onto the customer account.',
    variables: {},
    examples: ['claim this gift card', 'add the gift card to my account'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'The data has left the system. An export cannot be recalled once delivered.',
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.delete_data',
    aliases: ['delete_customer_data'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T2',
    description: 'Erase the personal data held for a customer, on request.',
    variables: {
      customerName: {
        type: 'string',
        description: 'Customer whose data to erase.',
        required: true,
        resolver: 'customer',
      },
    },
    examples: [
      'delete this customer data',
      'erase Gevorg personal information',
    ],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Erasure is the point of the command; the records no longer exist to restore.',
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.export_data',
    aliases: ['export_customer_data'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T2',
    description:
      'Export the personal data held for a customer, for a subject access request.',
    variables: {
      customerName: {
        type: 'string',
        description: 'Customer whose data to export.',
        required: true,
        resolver: 'customer',
      },
    },
    examples: ['export this customer data', 'give me Gevorg data export'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'The data has left the system. An export cannot be recalled once delivered.',
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.extend_subscription',
    aliases: ['extend_subscription'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T2',
    description: 'Extend the subscription period for a customer.',
    variables: {
      customerName: {
        type: 'string',
        description: 'Customer whose subscription to extend.',
        required: true,
        resolver: 'customer',
      },
    },
    examples: ['give Gevorg another month', 'extend this subscription'],
    confirm: 'always',
    compensation: {
      kind: 'manual',
      reason:
        'The customer may already be relying on the extended period; shortening it back is a billing decision.',
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.merge',
    aliases: ['merge_customers'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T2',
    description: 'Merge two customer records that refer to the same person.',
    variables: {},
    examples: [
      'merge these two customers',
      'combine the duplicate Gevorg records',
    ],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'A merge folds two histories into one and does not record the seam, so they cannot be separated again.',
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.privacy_delete',
    aliases: ['privacy_delete'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T2',
    description: 'Erase the personal data of the requesting customer.',
    variables: {},
    examples: ['delete my data', 'erase my account information'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Erasure is the point of the command; the records no longer exist to restore.',
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.privacy_export',
    aliases: ['privacy_export'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T2',
    description: 'Export the personal data of the requesting customer.',
    variables: {},
    examples: ['export my data', 'send me everything you hold about me'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'The data has left the system. An export cannot be recalled once delivered.',
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.request_gift_card_cancel',
    aliases: ['request_gift_card_cancel'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T1',
    description: 'Ask for a gift card order to be cancelled.',
    variables: {},
    examples: ['cancel my gift card order', 'I want to cancel that gift card'],
    confirm: 'always',
    compensation: {
      kind: 'manual',
      reason:
        'Raises a request that a person acts on; withdrawing it needs the same person.',
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.request_gift_card_modify',
    aliases: ['request_gift_card_modify'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T1',
    description: 'Ask for a change to a gift card order.',
    variables: {},
    examples: [
      'change the amount on my gift card order',
      'modify my gift card',
    ],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'manual',
      reason:
        'Raises a request that a person acts on; withdrawing it needs the same person.',
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.send_reengagement_message',
    aliases: ['send_reengagement_message'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T2',
    description: 'Message customers who have not visited recently.',
    variables: {},
    examples: [
      'message customers who have not been in for 60 days',
      'send a win back message',
    ],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason: 'The message has been sent. It cannot be unsent.',
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.tag',
    aliases: ['tag_customer'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T1',
    description: 'Add or remove a tag on a customer record.',
    variables: {
      customerName: {
        type: 'string',
        description: 'Customer to tag.',
        required: true,
        resolver: 'customer',
      },
    },
    examples: ['tag Gevorg as VIP', 'remove the VIP tag from this customer'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'customer.tag',
      captures: ['customerId', 'previousTags'],
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.update',
    aliases: ['update_customer'],
    domain: 'customer',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['manager', 'owner'] },
    risk: 'T2',
    description: 'Change the stored details of a customer.',
    variables: {
      customerName: {
        type: 'string',
        description: 'Customer to change.',
        required: true,
        resolver: 'customer',
      },
    },
    examples: ['change Gevorg phone number', 'update this customer email'],
    confirm: 'always',
    compensation: {
      kind: 'inverse',
      command: 'customer.update',
      captures: ['customerId', 'previousValues'],
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.update_my_locale',
    aliases: ['update_my_locale'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T1',
    description: 'Change the language the requesting customer sees.',
    variables: {},
    examples: ['switch me to Armenian', 'change my language to Russian'],
    confirm: 'never',
    compensation: {
      kind: 'inverse',
      command: 'customer.update_my_locale',
      captures: ['previousLocale'],
    },
    handler: 'AiCustomerCrmService',
  },
  {
    id: 'customer.update_my_profile',
    aliases: ['update_my_profile'],
    domain: 'customer',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T2',
    description: 'Change the stored details of the requesting customer.',
    variables: {},
    examples: ['update my phone number', 'change my email address'],
    confirm: 'always',
    compensation: {
      kind: 'inverse',
      command: 'customer.update_my_profile',
      captures: ['previousValues'],
    },
    handler: 'AiCustomerCrmService',
  },
] as const;
