/**
 * AI-ROADMAP Phase 1 - eighth domain slice: `provider` (registry
 * `provider-mobile`).
 *
 * 39 entries and the most read-heavy slice yet: **30 reads to 9 mutations**.
 * Most of the reads are `explain_*` product-guide commands, which is what a
 * mobile app for busy practitioners mostly needs - it answers questions about
 * the app itself.
 *
 * Two commands, `coordinate_waitlist_offer` and `team_whos_next`, permit
 * **client, manager and owner but not staff**. That is copied from the live
 * gate rather than invented, and it looks wrong: a staff member cannot run them
 * while a client-tier provider-app user can. Filed as e2e-bug.378 rather than
 * quietly "corrected" here, because the spec must match the running system or
 * the conformance suite - correctly - fails.
 */
import type { CommandSpec } from './ai-command-spec.types.js';

export const PROVIDER_COMMAND_SPECS: readonly CommandSpec[] = [
  {
    id: 'provider.coordinate_waitlist_offer',
    aliases: ['coordinate_waitlist_offer'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['manager', 'owner'] },
    risk: 'T0',
    description: 'Work out which waitlisted customer to offer a freed slot to.',
    variables: {},
    examples: [
      'who should get this cancelled slot',
      'coordinate the waitlist offer',
    ],
    confirm: 'never',
    // Permits client, manager and owner but NOT staff - taken from the live
    // gate, not invented. A staff member cannot run this while a client-tier
    // provider-app user can, which looks wrong; see e2e-bug.378.
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.team_whos_next',
    aliases: ['team_whos_next'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['manager', 'owner'] },
    risk: 'T0',
    description: 'Report which team member is next up.',
    variables: {},
    examples: ['who is next on the floor', 'whose turn is it'],
    confirm: 'never',
    // Permits client, manager and owner but NOT staff - taken from the live
    // gate, not invented. A staff member cannot run this while a client-tier
    // provider-app user can, which looks wrong; see e2e-bug.378.
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.explain_accessibility_settings',
    aliases: ['explain_accessibility_settings'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain the accessibility options in the provider app.',
    variables: {},
    examples: [
      'how do I make the text bigger',
      'what accessibility settings are there',
    ],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.explain_ai_suggestions',
    aliases: ['explain_ai_suggestions'],
    domain: 'provider',
    surfaces: ['dashboard', 'provider'],
    tiers: {
      dashboard: ['staff', 'manager', 'owner'],
      provider: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Explain where the assistant suggestions come from.',
    variables: {},
    examples: ['why is it suggesting this', 'how do AI suggestions work'],
    confirm: 'never',
    handler: 'AiProductGuideService',
  },
  {
    id: 'provider.explain_appointment_tax',
    aliases: ['explain_appointment_tax'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain the tax lines on an appointment payment breakdown.',
    variables: {},
    examples: ['why is there tax on this', 'explain the tax on this booking'],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.explain_assistant_approval',
    aliases: ['explain_assistant_approval'],
    domain: 'provider',
    surfaces: ['dashboard', 'provider'],
    tiers: {
      dashboard: ['staff', 'manager', 'owner'],
      provider: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Explain when the assistant needs approval before acting.',
    variables: {},
    examples: [
      'why is it asking me to approve',
      'when does the assistant need approval',
    ],
    confirm: 'never',
    handler: 'AiProductGuideService',
  },
  {
    id: 'provider.explain_assistant_confirm_swipe',
    aliases: ['explain_assistant_confirm_swipe'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain the swipe-to-confirm gesture.',
    variables: {},
    examples: ['how do I confirm this', 'what is the swipe for'],
    confirm: 'never',
    handler: 'AiProductGuideService',
  },
  {
    id: 'provider.explain_block_vs_time_off',
    aliases: ['explain_block_vs_time_off'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description:
      'Explain the difference between blocking time and requesting time off.',
    variables: {},
    examples: [
      'should I block time or request leave',
      'what is the difference between a block and time off',
    ],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.explain_booking_status_badge',
    aliases: ['explain_booking_status_badge'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain what a booking status badge means.',
    variables: {},
    examples: ['what does this badge mean', 'why is this booking orange'],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.explain_calendar_utilization_bands',
    aliases: ['explain_calendar_utilization_bands'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain the utilisation shading on the calendar.',
    variables: {},
    examples: [
      'what do the colours on my calendar mean',
      'explain the utilisation bands',
    ],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.explain_dashboard_only_action',
    aliases: ['explain_dashboard_only_action'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain that an action is only available on the dashboard.',
    variables: {},
    examples: ['why can I not do this here', 'how do I do this on mobile'],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.explain_floor_status',
    aliases: ['explain_floor_status'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain the floor status strip.',
    variables: {},
    examples: ['what does the floor strip show', 'explain the floor status'],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.explain_offline_suggestions',
    aliases: ['explain_offline_suggestions'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain how suggestions behave without a connection.',
    variables: {},
    examples: [
      'why are suggestions not updating',
      'do suggestions work offline',
    ],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.explain_profile_settings',
    aliases: ['explain_profile_settings'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain the provider profile settings.',
    variables: {},
    examples: ['what can I change in my profile', 'explain profile settings'],
    confirm: 'never',
    handler: 'AiProductGuideService',
  },
  {
    id: 'provider.explain_app_tabs',
    aliases: ['explain_provider_app_tabs'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain what each tab in the provider app is for.',
    variables: {},
    examples: ['what is the Today tab', 'explain the app tabs'],
    confirm: 'never',
    handler: 'AiProductGuideService',
  },
  {
    id: 'provider.explain_compound_steps',
    aliases: ['explain_provider_compound_steps'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain how a multi-step request is carried out.',
    variables: {},
    examples: ['why did it do three things', 'explain the steps it took'],
    confirm: 'never',
    handler: 'AiProductGuideService',
  },
  {
    id: 'provider.explain_context',
    aliases: ['explain_provider_context'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain what the assistant knows about the current context.',
    variables: {},
    examples: [
      'what do you know about right now',
      'what context are you using',
    ],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.explain_reassign_limit',
    aliases: ['explain_reassign_limit'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain the limit on reassigning bookings.',
    variables: {},
    examples: ['why can I not reassign this', 'what is the reassign limit'],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.explain_staff_invite',
    aliases: ['explain_staff_invite'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain how staff are invited to the app.',
    variables: {},
    examples: ['how do I invite a colleague', 'explain staff invites'],
    confirm: 'never',
    handler: 'AiProductGuideService',
  },
  {
    id: 'provider.explain_team_view_scope',
    aliases: ['explain_team_view_scope'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain whose bookings the team view shows.',
    variables: {},
    examples: ['whose calendar am I seeing', 'what does the team view include'],
    confirm: 'never',
    handler: 'AiProductGuideService',
  },
  {
    id: 'provider.explain_time_off_approval',
    aliases: ['explain_time_off_approval'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain who approves time off and how long it takes.',
    variables: {},
    examples: ['who approves my time off', 'how does leave approval work'],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.explain_visibility_block',
    aliases: ['explain_visibility_block'],
    domain: 'provider',
    surfaces: ['dashboard', 'provider'],
    tiers: {
      dashboard: ['staff', 'manager', 'owner'],
      provider: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Explain why something is hidden from view.',
    variables: {},
    examples: ['why can I not see this', 'what is blocking my view'],
    confirm: 'never',
    handler: 'AiProductGuideEmptyStateService',
  },
  {
    id: 'provider.get_calendar_month',
    aliases: ['get_calendar_month'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Show the provider calendar for a month.',
    variables: {},
    examples: ['show me next month', 'my calendar for March'],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.get_schedule_summary',
    aliases: ['get_schedule_summary'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Summarise the provider schedule.',
    variables: {},
    examples: ['what does my week look like', 'summarise my schedule'],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.list_my_multi_service_groups',
    aliases: ['list_my_multi_service_groups'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List multi-service visits assigned to this provider.',
    variables: {},
    examples: ['what spa days do I have', 'my multi service bookings'],
    confirm: 'never',
    handler: 'AiProviderBookingService',
  },
  {
    id: 'provider.list_my_package_visits',
    aliases: ['list_my_package_visits'],
    domain: 'provider',
    surfaces: ['provider', 'customer'],
    tiers: {
      provider: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'List package visits for this provider.',
    variables: {},
    examples: ['what package visits do I have', 'my package appointments'],
    confirm: 'never',
    handler: 'AiProviderBookingService',
  },
  {
    id: 'provider.list_package_appointments_today',
    aliases: ['list_package_appointments_today'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List today package appointments.',
    variables: {},
    examples: ['what package visits are today', 'package appointments today'],
    confirm: 'never',
    handler: 'AiProviderBookingService',
  },
  {
    id: 'provider.list_upcoming_bookings',
    aliases: ['list_upcoming_bookings'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List the provider upcoming bookings.',
    variables: {},
    examples: ['what is coming up', 'my next bookings'],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.open_booking_detail',
    aliases: ['open_booking_detail'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Open the detail view for a booking.',
    variables: {},
    examples: ['open my 3pm booking', 'show me that appointment'],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.show_profile',
    aliases: ['show_provider_profile'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Show the provider own profile.',
    variables: {},
    examples: ['show my profile', 'what is on my profile'],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.voice_summarize_next_client',
    aliases: ['voice_summarize_next_client'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Summarise the next client out loud for hands-free use.',
    variables: {},
    examples: ['who is next', 'tell me about my next client'],
    confirm: 'never',
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.collect_remaining_balance',
    aliases: ['collect_remaining_balance'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T2',
    description: 'Collect the outstanding balance on a booking.',
    variables: {},
    examples: ['take the rest of the payment', 'collect what they still owe'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Money moved. Reversing it is a refund - a new financial event, not an undo.',
    },
    handler: 'AiProviderBookingService',
  },
  {
    id: 'provider.confirm_pending_booking',
    aliases: ['confirm_pending_booking'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Confirm a booking that is awaiting confirmation.',
    variables: {},
    examples: ['confirm that pending booking', 'accept the 3pm request'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason: 'The customer has been told their booking is confirmed.',
    },
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.mark_visit_in_progress',
    aliases: ['mark_visit_in_progress'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Mark a visit as under way.',
    variables: {},
    examples: ['start this visit', 'mark them as in progress'],
    confirm: 'never',
    compensation: {
      kind: 'inverse',
      command: 'provider.mark_visit_in_progress',
      captures: ['bookingId', 'previousStatus'],
    },
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.mark_visit_complete',
    aliases: ['mark_visit_complete'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Mark a visit as finished.',
    variables: {},
    examples: ['mark that visit done', 'finish this appointment'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'provider.mark_visit_complete',
      captures: ['bookingId', 'previousStatus'],
    },
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.mark_multi_service_step_done',
    aliases: ['mark_multi_service_step_done'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Mark one service in a multi-service visit as finished.',
    variables: {},
    examples: ['the massage part is done', 'mark that step complete'],
    confirm: 'never',
    compensation: {
      kind: 'inverse',
      command: 'provider.mark_multi_service_step_done',
      captures: ['stepId', 'previousStatus'],
    },
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.suggest_reschedule_from_push',
    aliases: ['suggest_reschedule_from_push'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T1',
    description:
      'Offer the customer a reschedule in response to a notification.',
    variables: {},
    examples: ['suggest they move it', 'offer a reschedule for that push'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'The suggestion has been sent to the customer and cannot be unsent.',
    },
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.update_profile',
    aliases: ['update_provider_profile'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T2',
    description: 'Change the provider own profile details.',
    variables: {},
    examples: ['update my bio', 'change my profile photo'],
    confirm: 'always',
    compensation: {
      kind: 'inverse',
      command: 'provider.update_profile',
      captures: ['previousValues'],
    },
    handler: 'ProviderAiCommandService',
  },
  {
    id: 'provider.give_ai_feedback',
    aliases: ['give_provider_ai_feedback'],
    domain: 'provider',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Record feedback about an assistant response.',
    variables: {},
    examples: ['that was wrong', 'this suggestion was unhelpful'],
    confirm: 'never',
    compensation: {
      kind: 'none',
      reason:
        'Feedback is an observation about what happened; retracting it would remove the signal \u00a743 mines.',
    },
    handler: 'ProviderAiCommandService',
  },
] as const;
