/**
 * AI-ROADMAP Phase 1 - fifth domain slice: `schedule` (the roadmap's
 * "staff/schedule").
 *
 * 32 registry entries across four modules that are one domain in practice:
 * `schedule-resources` (18), `provider-time-off` (5), `provider-open-shifts` (5)
 * and `schedule` (4). 18 reads, 14 mutations, and - unlike every slice so far -
 * **four different handlers**, so `handler` is per command rather than per file.
 *
 * The recurring compensation theme here is that scheduling decisions are
 * communicated. Approving leave, denying it, or closing the business are not
 * database states that can be quietly put back: a provider has been told, and
 * customers have been turned away. Those are declared `none` or `manual` for the
 * same reason payment commands are, without any money being involved.
 */
import type { CommandSpec } from './ai-command-spec.types.js';

export const SCHEDULE_COMMAND_SPECS: readonly CommandSpec[] = [
  {
    id: 'schedule.book_walk_in_gap',
    aliases: ['book_walk_in_gap'],
    domain: 'schedule',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Book a walk-in customer into a gap in the provider schedule.',
    variables: {},
    examples: ['quick book a trim now', 'fit this walk-in into my next gap'],
    confirm: 'always',
    // e2e-bug.377 FIXED. This creates a real booking — `handleBookWalkInGap`
    // calls `bookingService.create(...)` — but was registered `mutating: false`,
    // so it ran at T0 with no confirmation gate. The registry binding now lists
    // it in `mutateIntents` and this spec follows.
    compensation: {
      kind: 'none',
      reason:
        'The customer has been booked in and the slot is taken; cancelling is a separate action they are told about.',
    },
    handler: 'AiProviderOpenShiftsService',
  },
  {
    id: 'schedule.check_multi_service_block_availability',
    aliases: ['check_multi_service_block_availability'],
    domain: 'schedule',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description:
      'Check whether several services can be booked back to back in one visit.',
    variables: {},
    examples: [
      'can I get a massage and a facial together',
      'is a spa day available friday',
    ],
    confirm: 'never',
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.check_package_line_availability',
    aliases: ['check_package_line_availability'],
    domain: 'schedule',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Check whether every service in a package can be scheduled.',
    variables: {},
    examples: [
      'can I book the whole bridal package',
      'is the bundle available next week',
    ],
    confirm: 'never',
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.draft_waitlist_offer_message',
    aliases: ['draft_waitlist_offer_message'],
    domain: 'schedule',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description:
      'Draft a message offering a freed slot to waitlisted customers.',
    variables: {},
    examples: [
      'draft an offer for this cancellation',
      'write a waitlist message for the gap',
    ],
    confirm: 'never',
    handler: 'AiProviderOpenShiftsService',
  },
  {
    id: 'schedule.earliest_slot_all_services',
    aliases: ['earliest_slot_all_services'],
    domain: 'schedule',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Find the earliest slot available across every service.',
    variables: {},
    examples: [
      'when is your next free slot',
      'earliest availability for anything',
    ],
    confirm: 'never',
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.explain_multi_service_settings',
    aliases: ['explain_multi_service_settings'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain how multi-service visits are currently scheduled.',
    variables: {},
    examples: [
      'how do we schedule spa days',
      'explain our multi service rules',
    ],
    confirm: 'never',
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.explain_resource_conflict',
    aliases: ['explain_resource_conflict'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Explain why a resource is double-booked.',
    variables: {},
    examples: ['why is room 2 conflicting', 'explain this resource clash'],
    confirm: 'never',
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.explain_why_no_slots',
    aliases: ['explain_why_no_slots'],
    domain: 'schedule',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Explain why no appointment slots are available.',
    variables: {},
    examples: ['why is nothing available', 'why can I not book friday'],
    confirm: 'never',
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.list_my_time_off_requests',
    aliases: ['list_my_time_off_requests'],
    domain: 'schedule',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List the time-off requests made by the requesting provider.',
    variables: {},
    examples: ['what time off have I asked for', 'show my leave requests'],
    confirm: 'never',
    handler: 'AiProviderTimeOffService',
  },
  {
    id: 'schedule.list_rebooking_candidates',
    aliases: ['list_rebooking_candidates'],
    domain: 'schedule',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List customers who could fill a freed slot.',
    variables: {},
    examples: [
      'who could take this cancelled slot',
      'list rebooking candidates',
    ],
    confirm: 'never',
    handler: 'AiProviderOpenShiftsService',
  },
  {
    id: 'schedule.list_resource_conflicts',
    aliases: ['list_resource_conflicts'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List scheduling conflicts on shared resources.',
    variables: {},
    examples: ['show me resource conflicts', 'what rooms are double booked'],
    confirm: 'never',
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.list_scheduling_resources',
    aliases: ['list_scheduling_resources'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List the rooms, chairs and equipment that can be scheduled.',
    variables: {},
    examples: ['what resources do we have', 'list our rooms and equipment'],
    confirm: 'never',
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.list_service_resource_requirements',
    aliases: ['list_service_resource_requirements'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List which resources each service needs.',
    variables: {},
    examples: [
      'what does a massage need',
      'list service resource requirements',
    ],
    confirm: 'never',
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.list_time_off_requests',
    aliases: ['list_time_off_requests'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List time-off requests awaiting a decision.',
    variables: {},
    examples: ['who has asked for time off', 'show pending leave requests'],
    confirm: 'never',
    handler: 'AiProviderTimeOffService',
  },
  {
    id: 'schedule.list_waitlist_for_my_services',
    aliases: ['list_waitlist_for_my_services'],
    domain: 'schedule',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description:
      'List customers waiting for the services this provider offers.',
    variables: {},
    examples: ['who is on my waitlist', 'show waitlist for my services'],
    confirm: 'never',
    handler: 'AiProviderOpenShiftsService',
  },
  {
    id: 'schedule.my_resource_assignments',
    aliases: ['my_resource_assignments'],
    domain: 'schedule',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'List the resources assigned to the requesting provider.',
    variables: {},
    examples: ['which room am I in', 'what resources am I assigned'],
    confirm: 'never',
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.providers_available_later_days',
    aliases: ['providers_available_later_days'],
    domain: 'schedule',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'List providers with availability on later days.',
    variables: {},
    examples: ['who is free later this week', 'any availability next week'],
    confirm: 'never',
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.suggest_waitlist_for_gap',
    aliases: ['suggest_waitlist_for_gap'],
    domain: 'schedule',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T0',
    description: 'Suggest which waitlisted customers best fit a gap.',
    variables: {},
    examples: [
      'who should I offer this gap to',
      'suggest someone for the 3pm gap',
    ],
    confirm: 'never',
    handler: 'AiProviderOpenShiftsService',
  },
  {
    id: 'schedule.approve_time_off',
    aliases: ['approve_time_off_request'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Approve a time-off request, blocking the provider calendar.',
    variables: {},
    examples: ['approve Gevorg leave request', 'approve that time off'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'The provider has been told the leave is approved and may have made plans on it.',
    },
    handler: 'AiProviderTimeOffService',
  },
  {
    id: 'schedule.deny_time_off',
    aliases: ['deny_time_off_request'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Deny a time-off request.',
    variables: {},
    examples: ['deny that leave request', 'reject Gevorg time off'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'The provider has been told the request was denied; reversing it is a new decision.',
    },
    handler: 'AiProviderTimeOffService',
  },
  {
    id: 'schedule.cancel_time_off',
    aliases: ['cancel_time_off_request'],
    domain: 'schedule',
    surfaces: ['provider'],
    tiers: { provider: ['client', 'staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Withdraw a time-off request the provider made.',
    variables: {},
    examples: ['cancel my leave request', 'withdraw my time off request'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'manual',
      reason:
        'Resubmitting is a new request that re-enters the approval queue.',
    },
    handler: 'AiProviderTimeOffService',
  },
  {
    id: 'schedule.assign_resource_hours',
    aliases: ['assign_resource_hours'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Set the hours a resource is available.',
    variables: {},
    examples: [
      'set room 2 hours to 9 to 5',
      'assign hours for the massage chair',
    ],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'schedule.assign_resource_hours',
      captures: ['resourceId', 'previousHours'],
    },
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.block_resource_unavailable',
    aliases: ['block_resource_unavailable'],
    domain: 'schedule',
    surfaces: ['provider', 'dashboard'],
    tiers: {
      provider: ['client', 'staff', 'manager', 'owner'],
      dashboard: ['staff', 'manager', 'owner'],
    },
    risk: 'T1',
    description: 'Mark a resource as unavailable for a period.',
    variables: {},
    examples: [
      'room 2 is out of action tomorrow',
      'block the chair for maintenance',
    ],
    confirm: 'always',
    compensation: {
      kind: 'inverse',
      command: 'schedule.block_resource_unavailable',
      captures: ['resourceId', 'previousAvailability'],
    },
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.configure_multi_service_scheduling_mode',
    aliases: ['configure_multi_service_scheduling_mode'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Change how multi-service visits are sequenced.',
    variables: {},
    examples: [
      'book spa services back to back',
      'change multi service scheduling mode',
    ],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'schedule.configure_multi_service_scheduling_mode',
      captures: ['previousMode'],
    },
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.create_resource',
    aliases: ['create_resource'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T1',
    description:
      'Add a room, chair or piece of equipment that can be scheduled.',
    variables: {},
    examples: ['add a new treatment room', 'create a resource called Chair 3'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'schedule.deactivate_resource',
      captures: ['resourceId'],
    },
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.deactivate_resource',
    aliases: ['deactivate_resource'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Retire a resource so it can no longer be scheduled.',
    variables: {},
    examples: ['retire room 2', 'stop scheduling the old chair'],
    confirm: 'always',
    compensation: {
      kind: 'manual',
      reason:
        'Existing bookings may already depend on the resource; restoring it needs a conflict check.',
    },
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.update_resource',
    aliases: ['update_resource'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Change the details of a schedulable resource.',
    variables: {},
    examples: ['rename room 2 to Studio', 'change the chair capacity'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'schedule.update_resource',
      captures: ['resourceId', 'previousValues'],
    },
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.set_service_resource_requirements',
    aliases: ['set_service_resource_requirements'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T1',
    description:
      'Declare which resources a service needs in order to be booked.',
    variables: {},
    examples: [
      'massages need a treatment room',
      'set resource requirements for facials',
    ],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'schedule.set_service_resource_requirements',
      captures: ['serviceId', 'previousRequirements'],
    },
    handler: 'AiScheduleResourcesService',
  },
  {
    id: 'schedule.holiday_mode',
    aliases: ['holiday_mode'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T3',
    description: 'Close the business for a period, blocking all booking.',
    variables: {},
    examples: ['we are closed next week', 'turn on holiday mode for christmas'],
    confirm: 'always',
    compensation: {
      kind: 'manual',
      reason:
        'Turning holiday mode off does not restore bookings that were declined while it was on.',
    },
    handler: 'AiSchedulingService',
  },
  {
    id: 'schedule.onboard_provider',
    aliases: ['onboard_provider_schedule'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T1',
    description: 'Set up a new provider working schedule.',
    variables: {},
    examples: ['set up Mary schedule', 'onboard the new stylist hours'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'schedule.onboard_provider',
      captures: ['employeeId', 'previousSchedule'],
    },
    handler: 'AiSchedulingService',
  },
  {
    id: 'schedule.rebalance_capacity',
    aliases: ['rebalance_capacity'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T3',
    description: 'Redistribute booking capacity across providers.',
    variables: {},
    examples: ['rebalance the team capacity', 'spread bookings more evenly'],
    confirm: 'always',
    compensation: {
      kind: 'manual',
      reason:
        'Rebalancing moves many bookings at once; restoring them needs per-booking pre-state.',
    },
    handler: 'AiSchedulingService',
  },
  {
    id: 'schedule.swap_schedules',
    aliases: ['swap_schedules'],
    domain: 'schedule',
    surfaces: ['dashboard'],
    tiers: { dashboard: ['staff', 'manager', 'owner'] },
    risk: 'T3',
    description: 'Swap the working schedules of two providers.',
    variables: {},
    examples: [
      'swap Gevorg and Mary shifts',
      'exchange their schedules this week',
    ],
    confirm: 'always',
    compensation: {
      kind: 'inverse',
      command: 'schedule.swap_schedules',
      captures: ['employeeIds', 'previousSchedules'],
    },
    handler: 'AiSchedulingService',
  },
] as const;
