import type { AiEvalLocale } from './eval/ai-command-eval.types.js';
import type { ClinicPatientChartIntent } from './ai-clinic-patient-chart.util.js';
import type { PatientChartSummaryFocus } from '../patient-clinical-profiles/patient-chart-summary.util.js';

export interface ClinicPatientChartEvalScenario {
  id: string;
  prompt: string;
  locale: AiEvalLocale;
  expectedAction: ClinicPatientChartIntent;
  rescueReason?: string;
  paramsPartial?: Record<string, unknown>;
  focus?: PatientChartSummaryFocus[];
  needsMultilingual?: boolean;
}

/** Armenian/Russian dashboard patient chart summaries (i18n-clinic-v2-ai-3). */
export const CLINIC_PATIENT_CHART_MULTILINGUAL_CLASSIFIER_RULES = `- Armenian/Russian patient chart read summaries (dashboard only):
  - explain_patient_chart: hy «բացատրիր հիվանդի քարտը», «ցույց տուր ալերգիաները և վերջին այցերը», «ինչ սպասող արդյունքներ ունի քարտում»; ru «объясни карту пациента», «покажи аллергии и визиты», «какие ожидающие результаты в карте». Requires customerName or customerId. READ chart summary — NOT lookup_customer, NOT list_test_orders, NOT list_bookings.
  - Optional focus: allergies, visits, results, orders — infer from prompt nouns (ալերգիա/аллергия, այց/визит, սպասող արդյունք/ожидающие результаты, բաց լաբորատոր/открытые анализы).`;

export const MULTILINGUAL_CLINIC_PATIENT_CHART_EVAL_SCENARIOS: ClinicPatientChartEvalScenario[] =
  [
    {
      id: 'hy-maria-chart',
      locale: 'hy',
      prompt: 'Բացատրիր Մարիայի հիվանդի քարտը',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Մարիա' },
      needsMultilingual: true,
    },
    {
      id: 'hy-allergies-visits-maria',
      locale: 'hy',
      prompt: 'Ցույց տուր ալերգիաները և վերջին այցերը Մարիայի համար',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Մարիա' },
      focus: ['allergies', 'visits'],
      needsMultilingual: true,
    },
    {
      id: 'hy-pending-results-maria',
      locale: 'hy',
      prompt: 'Ինչ սպասող լաբորատոր արդյունքներ ունի Մարիան իր քարտում',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Մարիա' },
      focus: ['results'],
      needsMultilingual: true,
    },
    {
      id: 'hy-summarize-john',
      locale: 'hy',
      prompt: 'Ամփոփիր հիվանդի քարտը Ջոնի համար',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Ջոն' },
      needsMultilingual: true,
    },
    {
      id: 'hy-allergies-visits-sofia',
      locale: 'hy',
      prompt: 'Պատմիր Սոֆիայի ալերգիաների և վերջին այցերի մասին',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Սոֆիա' },
      focus: ['allergies', 'visits'],
      needsMultilingual: true,
    },
    {
      id: 'hy-chart-allergies-anna',
      locale: 'hy',
      prompt: 'Բացատրիր ալերգիաները Աննայի հիվանդային քարտում',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Աննա' },
      focus: ['allergies'],
      needsMultilingual: true,
    },
    {
      id: 'hy-chart-summary-maria',
      locale: 'hy',
      prompt: 'Ցույց տուր Մարիայի քարտի ամփոփումը',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Մարիա' },
      needsMultilingual: true,
    },
    {
      id: 'hy-what-chart-shows',
      locale: 'hy',
      prompt: 'Ինչ է ցույց տալիս Մարիայի հիվանդի քարտը',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Մարիա' },
      needsMultilingual: true,
    },
    {
      id: 'hy-review-chart-pending',
      locale: 'hy',
      prompt: 'Վերանայիր Մարիայի քարտը՝ ալերգիաներ և սպասող արդյունքներ',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Մարիա' },
      focus: ['allergies', 'results'],
      needsMultilingual: true,
    },
    {
      id: 'hy-open-labs-chart',
      locale: 'hy',
      prompt: 'Մարիայի հիվանդի քարտ՝ վերջին այցեր և բաց լաբորատոր պատվերներ',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Մարիա' },
      focus: ['visits', 'results', 'orders'],
      needsMultilingual: true,
    },
    {
      id: 'hy-question-chart-james',
      locale: 'hy',
      prompt: 'Կարո՞ղ ես բացատրել Ջեյմսի հիվանդի քարտը',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Ջեյմս' },
      needsMultilingual: true,
    },
    {
      id: 'hy-recent-visits-only',
      locale: 'hy',
      prompt: 'Ցուցակավորիր Մարիայի վերջին այցերը նրա հիվանդի քարտից',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Մարիա' },
      focus: ['visits'],
      needsMultilingual: true,
    },
    {
      id: 'ru-maria-chart',
      locale: 'ru',
      prompt: 'Объясни карту пациента Марии',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Мария' },
      needsMultilingual: true,
    },
    {
      id: 'ru-allergies-visits-maria',
      locale: 'ru',
      prompt: 'Покажи аллергии и последние визиты для Марии',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Мария' },
      focus: ['allergies', 'visits'],
      needsMultilingual: true,
    },
    {
      id: 'ru-pending-results-maria',
      locale: 'ru',
      prompt: 'Какие ожидающие лабораторные результаты есть у Марии в карте',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Мария' },
      focus: ['results'],
      needsMultilingual: true,
    },
    {
      id: 'ru-summarize-john',
      locale: 'ru',
      prompt: 'Резюмируй карту пациента для Джона',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Джон' },
      needsMultilingual: true,
    },
    {
      id: 'ru-allergies-visits-sofia',
      locale: 'ru',
      prompt: 'Расскажи об аллергиях и недавних визитах Софии',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'София' },
      focus: ['allergies', 'visits'],
      needsMultilingual: true,
    },
    {
      id: 'ru-chart-allergies-anna',
      locale: 'ru',
      prompt: 'Объясни аллергии в карте пациента Анны',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Анна' },
      focus: ['allergies'],
      needsMultilingual: true,
    },
    {
      id: 'ru-chart-summary-maria',
      locale: 'ru',
      prompt: 'Покажи сводку карты Марии',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Мария' },
      needsMultilingual: true,
    },
    {
      id: 'ru-what-chart-shows',
      locale: 'ru',
      prompt: 'Что показывает карта пациента Марии',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Мария' },
      needsMultilingual: true,
    },
    {
      id: 'ru-review-chart-pending',
      locale: 'ru',
      prompt: 'Просмотри карту Марии — аллергии и ожидающие результаты',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Мария' },
      focus: ['allergies', 'results'],
      needsMultilingual: true,
    },
    {
      id: 'ru-open-labs-chart',
      locale: 'ru',
      prompt: 'Карта пациента Марии — последние визиты и открытые анализы',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Мария' },
      focus: ['visits', 'results', 'orders'],
      needsMultilingual: true,
    },
    {
      id: 'ru-question-chart-james',
      locale: 'ru',
      prompt: 'Можешь объяснить карту пациента для Джеймса',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Джеймс' },
      needsMultilingual: true,
    },
    {
      id: 'ru-recent-visits-only',
      locale: 'ru',
      prompt: 'Перечисли последние визиты Марии из ее карты пациента',
      expectedAction: 'explain_patient_chart',
      rescueReason: 'explain_patient_chart',
      paramsPartial: { customerName: 'Мария' },
      focus: ['visits'],
      needsMultilingual: true,
    },
  ];
