/**
 * AI-ROADMAP §72 — build the command embedding cache.
 *
 * `narrowShortlist` needs a vector per command. There are 696, they change only
 * when a spec changes, and embedding them costs ~70k tokens once (fractions of
 * a cent on `text-embedding-3-small`). So they are computed here and committed,
 * not fetched at boot.
 *
 * **256 dimensions, not the default 1,536.** At full width the cache is a ~10MB
 * checked-in file; 256 is ample for ranking a few hundred short texts, and the
 * runtime query must request the same width or the cosine is meaningless.
 * `EMBEDDING_DIMENSIONS` is the single place that decides.
 *
 *   AI_BUILD_COMMAND_EMBEDDINGS=1 npm run build:ai-embeddings
 */
import fs from 'node:fs';
import path from 'node:path';
import OpenAI from 'openai';
import { COMMAND_SPECS } from './ai-command-spec.registry.js';
import {
  commandMatchText,
  commandMatchTextHash,
  EMBEDDING_DIMENSIONS,
  EMBEDDING_MODEL,
} from './ai-command-shortlist.util.js';

const ENABLED = process.env.AI_BUILD_COMMAND_EMBEDDINGS === '1';
const OUT = path.join(__dirname, 'ai-command-embeddings.json');

(ENABLED ? describe : describe.skip)('command embedding cache', () => {
  jest.setTimeout(600_000);

  it('embeds every command and writes the cache', async () => {
    const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    const vectors: Record<string, number[]> = {};

    // Batched: the embeddings endpoint accepts an array, so 696 texts is a
    // handful of requests rather than 696.
    const BATCH = 96;
    for (let i = 0; i < COMMAND_SPECS.length; i += BATCH) {
      const slice = COMMAND_SPECS.slice(i, i + BATCH);
      const res = await openai.embeddings.create({
        model: EMBEDDING_MODEL,
        input: slice.map((s) => commandMatchText(s)),
        dimensions: EMBEDDING_DIMENSIONS,
      });
      slice.forEach((spec, j) => {
        const v = res.data[j]?.embedding;
        if (v?.length) vectors[spec.id] = v.map((n) => Number(n.toFixed(5)));
      });
    }

    expect(Object.keys(vectors)).toHaveLength(COMMAND_SPECS.length);

    fs.writeFileSync(
      OUT,
      `${JSON.stringify(
        {
          _comment:
            'Generated by ai-command-embeddings.build.spec.ts. Rebuild after changing any spec description or examples: AI_BUILD_COMMAND_EMBEDDINGS=1 npm run build:ai-embeddings',
          model: EMBEDDING_MODEL,
          dimensions: EMBEDDING_DIMENSIONS,
          commandCount: COMMAND_SPECS.length,
          // e2e-bug.390 — fingerprint of the text every vector was built from,
          // checked by ai-command-embeddings.staleness.spec.ts.
          sourceHash: commandMatchTextHash(COMMAND_SPECS),
          vectors,
        },
        null,
        0,
      )}\n`,
    );
    const kb = Math.round(fs.statSync(OUT).size / 1024);
    console.log(`[embeddings] wrote ${COMMAND_SPECS.length} vectors, ${kb}KB`);
  });
});
