/**
 * AI-ROADMAP Phase 1 - sixth domain slice: `booking` (registry `public-booking`).
 *
 * 66 registry entries - the largest slice so far and the most read-heavy: 40
 * reads to 26 mutations. It is the customer-facing surface, and §28 measured
 * customer as 69% of all traffic at the worst completion rate, so these are the
 * commands the north-star metric is mostly made of.
 *
 * Three commands look like writes and are registered as reads. All three were
 * checked against their handlers before speccing, and all three are correct:
 * `book_another_service` and `complete_intake_and_book` return a `navigate`
 * target rather than creating anything, and `add_booking_to_calendar` builds a
 * calendar link. Naming is not evidence - e2e-bug.377 was found by reading the
 * handler, and so was the absence of a defect here.
 */
import type { CommandSpec } from './ai-command-spec.types.js';

export const BOOKING_COMMAND_SPECS: readonly CommandSpec[] = [
  {
    id: 'booking.add_to_calendar',
    aliases: ['add_booking_to_calendar'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Give the customer a calendar link for their booking.',
    variables: {},
    examples: ['add this to my calendar', 'send me a calendar invite'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.book_another_service',
    aliases: ['book_another_service'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description:
      'Route the customer to book an additional service. Returns a navigation target; creates nothing.',
    variables: {},
    examples: ['I want to book something else too', 'add another service'],
    confirm: 'never',
    // Registered READ and correct: the handler returns `navigate`, not a booking.
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.help',
    aliases: ['booking_help'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Explain how booking works on the public page.',
    variables: {},
    examples: ['how do I book', 'help me make a booking'],
    confirm: 'never',
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.business_info',
    aliases: ['business_info'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description:
      'Answer questions about the business - hours, address, contact.',
    variables: {},
    examples: ['what are your opening hours', 'where are you'],
    confirm: 'never',
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.check_availability',
    aliases: ['check_availability'],
    domain: 'booking',
    surfaces: ['dashboard', 'provider', 'public', 'customer'],
    tiers: {
      dashboard: ['staff', 'manager', 'owner'],
      provider: ['staff', 'manager', 'owner'],
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Check what appointment slots are free.',
    variables: {},
    examples: [
      'what is free on friday',
      'do you have anything tomorrow',
      'is Gevorg open tomorrow morning for Swedish massage',
      'Check availability for Swedish massage on 02/08/2026',
    ],
    confirm: 'never',
    handler: 'AiCommandService',
  },
  {
    id: 'booking.check_multi_service_availability',
    aliases: ['check_multi_service_availability'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Check whether several services can be booked in one visit.',
    variables: {},
    examples: [
      'can I do a massage and facial together',
      'is a spa day possible',
    ],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.check_package_availability',
    aliases: ['check_package_availability'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Check whether a package can be scheduled.',
    variables: {},
    examples: ['can I book the bridal package', 'is the bundle available'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.check_waitlist_status',
    aliases: ['check_waitlist_status'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Report the customer position on a waitlist.',
    variables: {},
    examples: ['where am I on the waitlist', 'any news on my waitlist spot'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.complete_intake_and_book',
    aliases: ['complete_intake_and_book'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description:
      'Route the customer to finish an intake form and then book. Returns a navigation target.',
    variables: {},
    examples: ['finish my intake and book', 'complete the form and book me in'],
    confirm: 'never',
    // Registered READ. The handler returns `navigate`; it calls
    // `ensureCustomerDraft`, which is an idempotent get-or-create of a draft
    // rather than a booking, and draft creation has its own MUT command
    // (`create_intake_draft`).
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.confirm_my_details',
    aliases: ['confirm_my_booking_details'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Show the customer their booking details for confirmation.',
    variables: {},
    examples: ['what are my booking details', 'confirm my appointment details'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_cancel_policy',
    aliases: ['explain_cancel_policy'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Explain the cancellation policy that applies.',
    variables: {},
    examples: ['what is your cancellation policy', 'can I cancel for free'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_clinic_booking_fields',
    aliases: ['explain_clinic_booking_fields'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Explain the extra fields a clinic booking asks for.',
    variables: {},
    examples: [
      'why do you need my date of birth',
      'what are these clinic fields',
    ],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_deposit_forfeiture',
    aliases: ['explain_deposit_forfeiture'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Explain when a deposit is kept rather than refunded.',
    variables: {},
    examples: [
      'do I lose my deposit if I cancel',
      'when is the deposit non refundable',
    ],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_lab_prep',
    aliases: ['explain_lab_prep'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Explain how to prepare for a lab appointment.',
    variables: {},
    examples: ['how do I prepare for the blood test', 'do I need to fast'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_manage_booking_context',
    aliases: ['explain_manage_booking_context'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Explain what can be changed from the manage-booking view.',
    variables: {},
    examples: [
      'what can I change about my booking',
      'what does manage booking do',
    ],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_manage_booking_page',
    aliases: ['explain_manage_booking_page'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Explain how to use the manage-booking page.',
    variables: {},
    examples: ['how do I use this page', 'explain the manage booking screen'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_multi_service_cart',
    aliases: ['explain_multi_service_cart'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Explain what is in the multi-service cart.',
    variables: {},
    examples: ['what is in my cart', 'explain my spa day selection'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_package_savings',
    aliases: ['explain_package_savings'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Explain how much a package saves against booking separately.',
    variables: {},
    examples: ['is the package worth it', 'how much do I save with the bundle'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_package_visit_rules',
    aliases: ['explain_package_visit_rules'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Explain the rules governing package visits.',
    variables: {},
    examples: [
      'how do package visits work',
      'can I use two package visits at once',
    ],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_post_visit_review_prompt',
    aliases: ['explain_post_visit_review_prompt'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Explain the review request sent after a visit.',
    variables: {},
    examples: ['why are you asking me to review', 'what is this review prompt'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_preparation_notes',
    aliases: ['explain_preparation_notes'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Explain how to prepare for an appointment.',
    variables: {},
    examples: ['how should I prepare', 'anything I need to do before'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_provider_availability',
    aliases: ['explain_provider_availability'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Explain when a particular provider works.',
    variables: {},
    examples: ['when does Gevorg work', 'what are their hours'],
    confirm: 'never',
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.explain_public_intake_form',
    aliases: ['explain_public_intake_form'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Explain the intake form shown before booking.',
    variables: {},
    examples: ['what is this form for', 'why do I need to fill this in'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.explain_subscription_vs_one_time',
    aliases: ['explain_subscription_vs_one_time'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Compare subscribing against paying per visit.',
    variables: {},
    examples: [
      'should I subscribe or pay each time',
      'is the membership better value',
    ],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.find_evening_weekend_slots',
    aliases: ['find_evening_weekend_slots'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Find slots outside normal working hours.',
    variables: {},
    examples: ['anything in the evening', 'do you have weekend appointments'],
    confirm: 'never',
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.find_services_under_budget',
    aliases: ['find_services_under_budget'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Find services within a price limit.',
    variables: {},
    examples: ['what can I get for 50', 'services under 100'],
    confirm: 'never',
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.get_intake_flow_status',
    aliases: ['get_intake_flow_status'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Report how far the customer has got through the intake flow.',
    variables: {},
    examples: ['where am I in the form', 'how much of the intake is left'],
    confirm: 'never',
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.get_manage_link',
    aliases: ['get_manage_link'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Give the customer the link to manage their booking.',
    variables: {},
    examples: ['send me the manage link', 'how do I change my booking'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.list_my_appointments',
    aliases: ['list_my_appointments'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'List the customer appointments.',
    variables: {},
    examples: ['what appointments do I have', 'list my bookings'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.list_my_upcoming_appointments',
    aliases: ['list_my_upcoming_appointments'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'List the customer upcoming appointments only.',
    variables: {},
    examples: ['what is coming up', 'my next appointments'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.list_providers',
    aliases: ['list_providers'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'List the providers who work here.',
    variables: {},
    examples: ['who works there', 'list your staff'],
    confirm: 'never',
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.list_public_promotions',
    aliases: ['list_public_promotions'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'List current public offers.',
    variables: {},
    examples: ['any deals on', 'what promotions do you have'],
    confirm: 'never',
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.list_services',
    aliases: ['list_services'],
    domain: 'booking',
    surfaces: ['dashboard', 'public', 'customer'],
    tiers: {
      dashboard: ['staff', 'manager', 'owner'],
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'List the services offered.',
    variables: {},
    examples: ['what do you offer', 'list your services'],
    confirm: 'never',
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.preview_multi_service_cart',
    aliases: ['preview_multi_service_cart'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Preview the multi-service cart before booking.',
    variables: {},
    examples: ['show me my cart', 'preview my spa day'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.recommend_specialists',
    aliases: ['recommend_specialists'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T0',
    description: 'Recommend which provider suits what the customer wants.',
    variables: {},
    examples: ['who is best for colour', 'which stylist should I see'],
    confirm: 'never',
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.recover_lost_manage_link',
    aliases: ['recover_lost_manage_link'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Help a customer who has lost their manage-booking link.',
    variables: {},
    examples: ['I lost the link to my booking', 'resend my booking link'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.share_my_booking',
    aliases: ['share_my_booking'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description:
      'Give the customer something to share their booking with someone else.',
    variables: {},
    examples: [
      'share my booking with my partner',
      'send these details to someone',
    ],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.show_cart_total_duration',
    aliases: ['show_cart_total_duration'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Report how long everything in the cart will take.',
    variables: {},
    examples: ['how long will this all take', 'total duration of my cart'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.sign_in_after_booking',
    aliases: ['sign_in_after_booking'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Explain how to create an account after booking as a guest.',
    variables: {},
    examples: ['how do I make an account now', 'sign me in after booking'],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.sign_in_to_manage_booking',
    aliases: ['sign_in_to_manage_booking'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T0',
    description: 'Explain how to sign in to manage an existing booking.',
    variables: {},
    examples: [
      'how do I sign in to change my booking',
      'log me in to manage it',
    ],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.suggest_package_block',
    aliases: ['suggest_package_block'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T0',
    description: 'Suggest booking package visits as one block.',
    variables: {},
    examples: [
      'can I do all my package visits together',
      'suggest a block for my package',
    ],
    confirm: 'never',
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.add_services_to_cart',
    aliases: ['add_services_to_cart'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T1',
    description: 'Add services to the multi-service cart.',
    variables: {},
    examples: ['add a facial to my cart', 'also book a manicure'],
    confirm: 'never',
    compensation: {
      kind: 'inverse',
      command: 'booking.remove_service_from_cart',
      captures: ['cartId', 'previousItems'],
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.remove_service_from_cart',
    aliases: ['remove_service_from_cart'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T1',
    description: 'Remove a service from the multi-service cart.',
    variables: {},
    examples: ['take the facial out', 'remove that from my cart'],
    confirm: 'never',
    compensation: {
      kind: 'inverse',
      command: 'booking.add_services_to_cart',
      captures: ['cartId', 'previousItems'],
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.book_multi_service',
    aliases: ['book_multi_service'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T2',
    description: 'Book several services in one visit.',
    variables: {
      // `handleBookMultiServiceLogic` -> `resolveServices`. Nothing is
      // required: with no names it falls back to the session cart, and with
      // neither it returns `missing: ['serviceNames']` rather than failing.
      serviceNames: {
        type: 'string[]',
        description:
          'Services to book together. Falls back to names found in the message, then to the session cart.',
        required: false,
        resolver: 'service',
      },
      serviceName: {
        type: 'string',
        description: 'A single service, when only one was named.',
        required: false,
        resolver: 'service',
      },
      blockStartTime: {
        type: 'string',
        description:
          'Start of the chosen time block. Without it the reply sends the customer to the block picker instead of checkout.',
        required: false,
        resolver: 'datetime',
      },
    },
    examples: ['book a massage and a facial', 'book my spa day'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Money moved. Reversing it is a refund - a new financial event, not an undo.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.book_package',
    aliases: ['book_package'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T2',
    description: 'Book the visits that make up a package.',
    variables: {
      // `handleBookPackageLogic` -> `resolvePackageId`. `packageName` is the
      // only way to name a package in words; without one the handler returns
      // `missing: ['packageName']` and sends the customer to the package list.
      packageName: {
        type: 'string',
        description:
          'Package to book. Falls back to a package name found in the message.',
        required: false,
        resolver: 'none',
      },
      bookingFirstAvailable: {
        type: 'boolean',
        description:
          'Take the earliest block the package fits into, instead of asking for a date.',
        required: false,
        resolver: 'none',
      },
      date: {
        type: 'string',
        description: 'Day to book the package block on.',
        required: false,
        resolver: 'date',
      },
      blockStartTime: {
        type: 'string',
        description: 'Start of the chosen block, once one has been picked.',
        required: false,
        resolver: 'datetime',
      },
    },
    examples: ['book my bridal package', 'schedule the bundle'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Money moved. Reversing it is a refund - a new financial event, not an undo.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.book_with_cash',
    aliases: ['book_with_cash'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T2',
    description: 'Book an appointment to be paid for in cash.',
    variables: {},
    examples: [
      'book it and I will pay cash',
      'reserve it, paying at the venue',
    ],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Money moved. Reversing it is a refund - a new financial event, not an undo.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.book_with_gift_card',
    aliases: ['book_with_gift_card'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T2',
    description: 'Book an appointment paid for with a gift card.',
    variables: {
      // `enrichBookWithGiftCardParamsFromPrompt` prefers a supplied
      // `giftCardCode` over the one it extracts from the message, so this is a
      // real input even though the handler itself only reads `_prompt`.
      giftCardCode: {
        type: 'string',
        description:
          'Gift card to pay with. Falls back to a code found in the message; the customer is asked at checkout if neither has one.',
        required: false,
        resolver: 'none',
      },
    },
    examples: ['book it using my gift card', 'pay with the gift card'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Money moved. Reversing it is a refund - a new financial event, not an undo.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.use_subscription_credit',
    aliases: ['use_subscription_credit'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T2',
    description: 'Book a visit against a subscription credit.',
    variables: {
      // `handleUseSubscriptionCreditLogic`. Optional on purpose: with one
      // active subscription the handler picks it, and the id it accepts is one
      // it handed back in an earlier reply, not something a planner invents.
      subscriptionId: {
        type: 'string',
        description:
          'Which membership to draw the credit from. Defaults to the only active one.',
        required: false,
        resolver: 'none',
      },
    },
    examples: ['use my membership credit', 'book with my subscription'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Money moved. Reversing it is a refund - a new financial event, not an undo.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.select_subscription_plan',
    aliases: ['select_subscription_plan'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T2',
    description: 'Choose a subscription plan to join.',
    variables: {
      // `handleSelectSubscriptionPlanLogic`. With no name it selects the first
      // plan on offer, so `required: true` would block a prompt the handler
      // already answers.
      planName: {
        type: 'string',
        description:
          'Plan to join. Defaults to the first plan available; an unmatched name comes back as a clarification listing the real ones.',
        required: false,
        resolver: 'none',
      },
      serviceId: {
        type: 'string',
        description:
          'Narrow the plans on offer to the ones covering one service.',
        required: false,
        resolver: 'service',
      },
    },
    examples: ['I want the gold plan', 'pick the monthly membership'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Money moved. Reversing it is a refund - a new financial event, not an undo.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.cancel_all_upcoming',
    aliases: ['cancel_all_upcoming_bookings'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T3',
    description: 'Cancel every upcoming booking the customer has.',
    variables: {
      // tech-debt C2 — `handleCancelAllUpcomingBookingsLogic`. `_prompt`,
      // `conversationHistory` and `sessionCustomerId` are pipeline- or
      // session-injected and deliberately not declared.
      //
      // T3 and destructive: without `bookingIds` this cancels *every* upcoming
      // booking the customer has, so the list is the difference between "some"
      // and "all".
      confirm: {
        type: 'boolean',
        description:
          'Proceed with the cancellation. Without it the command previews what would be cancelled and asks.',
        required: false,
        resolver: 'none',
      },
      bookingIds: {
        type: 'string[]',
        description:
          'Restrict the cancellation to these bookings. Omit to cancel every upcoming booking.',
        required: false,
        resolver: 'appointment',
      },
    },
    examples: ['cancel everything', 'cancel all my appointments'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'The customer has been told the booking is cancelled and the slot may already be taken.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.cancel_with_token',
    aliases: ['cancel_booking_with_token'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T1',
    description: 'Cancel a booking using a manage-booking link.',
    variables: {},
    examples: ['cancel my booking', 'I need to cancel'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'The customer has been told the booking is cancelled and the slot may already be taken.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.cancel_my_subscription',
    aliases: ['cancel_my_subscription'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T2',
    description: 'Cancel the customer own subscription.',
    variables: {
      // `handleCancelMySubscriptionLogic`. Not required — with one active
      // membership it cancels that one, and with several it asks. Marking it
      // required would make "cancel my membership" undeliverable for the
      // common case, which is e2e-bug.399's shape.
      subscriptionId: {
        type: 'string',
        description:
          'Which membership to cancel. Defaults to the only active one; with more than one the customer is asked which.',
        required: false,
        resolver: 'none',
      },
    },
    examples: ['cancel my membership', 'stop my subscription'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'Cancelling stops billing and confirms to the customer; resubscribing is a new agreement.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.cancel_package_visit_self',
    aliases: ['cancel_package_visit_self'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T1',
    description: 'Cancel one visit from a package.',
    variables: {},
    examples: [
      'cancel my package visit on friday',
      'drop one of my package sessions',
    ],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'The customer has been told the booking is cancelled and the slot may already be taken.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.cancel_package_visit_with_token',
    aliases: ['cancel_package_visit_with_token'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T1',
    description: 'Cancel a package visit using a manage-booking link.',
    variables: {},
    examples: ['cancel this package visit', 'cancel the session in my link'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'The customer has been told the booking is cancelled and the slot may already be taken.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.reschedule_with_token',
    aliases: ['reschedule_booking_with_token'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T1',
    description: 'Move a booking using a manage-booking link.',
    variables: {},
    examples: ['move my booking to friday', 'reschedule my appointment'],
    confirm: 'always',
    compensation: {
      kind: 'inverse',
      command: 'booking.reschedule_with_token',
      captures: ['bookingId', 'originalStart'],
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.reschedule_package_lines',
    aliases: ['reschedule_package_lines'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T3',
    description: 'Move several package visits at once.',
    variables: {},
    examples: ['move all my package visits', 'reschedule the whole package'],
    confirm: 'always',
    compensation: {
      kind: 'manual',
      reason:
        'Moves several bookings at once; restoring them needs per-visit pre-state.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.reschedule_package_visit_self',
    aliases: ['reschedule_package_visit_self'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T1',
    description: 'Move one visit from a package.',
    variables: {},
    examples: ['move my package visit to tuesday', 'reschedule that session'],
    confirm: 'always',
    compensation: {
      kind: 'inverse',
      command: 'booking.reschedule_package_visit_self',
      captures: ['bookingId', 'originalStart'],
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.reschedule_package_visit_with_token',
    aliases: ['reschedule_package_visit_with_token'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T1',
    description: 'Move a package visit using a manage-booking link.',
    variables: {},
    examples: ['reschedule this package visit', 'move the session in my link'],
    confirm: 'always',
    compensation: {
      kind: 'inverse',
      command: 'booking.reschedule_package_visit_with_token',
      captures: ['bookingId', 'originalStart'],
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.change_provider_on_reschedule',
    aliases: ['change_provider_on_reschedule'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T1',
    description: 'Change which provider will carry out a rescheduled booking.',
    variables: {},
    examples: [
      'can I see someone else instead',
      'change my stylist for that booking',
    ],
    confirm: 'always',
    compensation: {
      kind: 'inverse',
      command: 'booking.change_provider_on_reschedule',
      captures: ['bookingId', 'previousEmployeeId'],
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.join_waitlist',
    aliases: ['join_waitlist'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T1',
    description: 'Add the customer to the waitlist for a fully-booked slot.',
    variables: {},
    examples: ['put me on the waitlist', 'let me know if something frees up'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'inverse',
      command: 'booking.join_waitlist',
      captures: ['waitlistId'],
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.leave_visit_review',
    aliases: ['leave_visit_review'],
    domain: 'booking',
    surfaces: ['customer', 'public'],
    tiers: {
      customer: ['client'],
      public: ['client', 'staff', 'manager', 'owner'],
    },
    risk: 'T1',
    description: 'Leave a review for a completed visit.',
    variables: {},
    examples: ['leave a 5 star review', 'review my last visit'],
    confirm: 'always',
    compensation: {
      kind: 'none',
      reason:
        'A review may already be visible to other customers and to the provider.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.notify_running_late',
    aliases: ['notify_running_late'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T1',
    description: 'Tell the business the customer is running late.',
    variables: {},
    examples: ['I am running 10 minutes late', 'tell them I will be late'],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'none',
      reason: 'The business has been told; the message cannot be unsent.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.report_problem',
    aliases: ['report_booking_problem'],
    domain: 'booking',
    surfaces: ['customer'],
    tiers: { customer: ['client'] },
    risk: 'T1',
    description: 'Report a problem with a booking to the business.',
    variables: {},
    examples: [
      'the time on my booking is wrong',
      'report a problem with my appointment',
    ],
    confirm: 'if-ambiguous',
    compensation: {
      kind: 'manual',
      reason:
        'Raises a support case that a person acts on; withdrawing it needs the same person.',
    },
    handler: 'AiSelfServiceBookingService',
  },
  {
    id: 'booking.create_intake_draft',
    aliases: ['create_intake_draft'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T1',
    description: 'Start a draft intake form for a customer.',
    variables: {},
    examples: ['start my intake form', 'begin the pre visit questions'],
    confirm: 'never',
    compensation: {
      kind: 'inverse',
      command: 'booking.create_intake_draft',
      captures: ['draftId'],
    },
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.start_pre_visit_intake',
    aliases: ['start_pre_visit_intake'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T1',
    description: 'Begin the pre-visit intake flow.',
    variables: {},
    examples: ['start the pre visit intake', 'begin my clinic form'],
    confirm: 'never',
    compensation: {
      kind: 'inverse',
      command: 'booking.start_pre_visit_intake',
      captures: ['intakeId'],
    },
    handler: 'PublicBookingAssistantService',
  },
  {
    id: 'booking.submit_intake_answers',
    aliases: ['submit_intake_answers'],
    domain: 'booking',
    surfaces: ['public', 'customer'],
    tiers: {
      public: ['client', 'staff', 'manager', 'owner'],
      customer: ['client'],
    },
    risk: 'T2',
    description: 'Submit the answers a customer gave on an intake form.',
    variables: {
      // `handleSubmitIntakeAnswersLogic`. `sessionIntakeId` is the fallback
      // and is session-injected, so only the explicit form is declared.
      intakeId: {
        type: 'string',
        description:
          'Which intake form the answers belong to. Falls back to the intake already open in the session.',
        required: false,
        resolver: 'none',
      },
    },
    examples: ['submit my intake answers', 'I have finished the form'],
    confirm: 'always',
    compensation: {
      kind: 'inverse',
      command: 'booking.submit_intake_answers',
      captures: ['intakeId', 'previousAnswers'],
    },
    handler: 'PublicBookingAssistantService',
  },
] as const;
