/** Dashboard integrations and notification settings classifier rules. */
export const INTEGRATIONS_DASHBOARD_CLASSIFIER_RULES = `- configure_push_recipients / configure_notification_settings / configure_whatsapp_integration / test_push / notification_history / toggle_business_email_on_customer_change: dashboard notification settings (Sprint 35). configure_notification_settings is salon channel/reminder toggles on Settings → Notifications — NOT customer enable_notifications. configure_whatsapp_integration is Meta WhatsApp credentials/templates on Settings → WhatsApp — NOT test_push or test_webhook. test_push is NOT test_webhook.
- toggle_business_email_on_customer_change: MUTATE — owner/business email alert when a customer cancels or reschedules online (ongoing preference). Triggers: "notify me whenever a customer cancels", "alert me when customers reschedule", "enable email when customers cancel". Sets notifyBusinessOnCustomerBookingChange. NOT propose_notify_customers / notify_cancelled_customers (one-off message TO a customer about their cancelled booking), NOT configure_notification_settings (channel/reminder toggles), NOT enable_notifications (customer reminder prefs).
- enable_notifications / appointment_reminder_preferences: customer notification and reminder prefs (Sprint 35). NOT order_status_notifications (gift card orders).
- list_webhooks / create_webhook / test_webhook / rotate_api_key / list_zapier_triggers / configure_zapier / configure_openai_integration / run_accounting_export / configure_zendesk / create_support_ticket / sync_customer_to_zendesk / configure_marketing_registration_email / list_integration_health / explain_integration_health / explain_support_inbox: integrations and back-office (Sprint 32). configure_openai_integration is Settings → OpenAI platform vs BYOK — NOT explain_ai_settings (read-only), NOT rotate_api_key (Booking REST keys). explain_support_inbox: READ — "Do I have any open support tickets?" / unread customer messages — honest "not listable via AI yet" (NOT list_agent_tasks, NOT create_support_ticket).
- delete_webhook: MUTATE — remove a webhook subscription. Optional webhookId (uuid) or url to pick the target; clarifies when several exist. Use for "delete the webhook for https://...", "remove webhook <id>". NOT create_webhook, NOT test_webhook.
- toggle_webhook: MUTATE — enable, disable, pause, or resume a webhook subscription without deleting it. Requires enabled boolean (or enable/disable phrasing); optional webhookId or url. Use for "disable the booking webhook", "re-enable webhook <id>". NOT configure_zapier (Zapier toggle), NOT delete_webhook.
- contact_support / open_ticket_for_order: customer Zendesk support (Sprint 32).
- create_api_key: MUTATE — mint a new API key without revoking anything (optional apiKeyName). NOT rotate_api_key (creates new AND revokes an old key together).
- revoke_api_key: MUTATE — revoke an existing API key only, no new key created. Requires keyId or apiKeyName. NOT rotate_api_key (creates a replacement too).
- configure_distribution_channels: MUTATE — enable/configure Reserve with Google, Meta (Facebook/Instagram) booking button, Telegram, or WhatsApp booking distribution channels on Settings → Distribution. Fields: googleReserveEnabled/googleMerchantId/googlePartnerNotes, metaBookingEnabled/facebookPageId/facebookPageUrl/instagramUsername, telegramEnabled/telegramBotUsername, whatsappBookingEnabled/whatsappBusinessPhone. NOT configure_whatsapp_integration (Meta WhatsApp API credentials/templates for notifications, a different feature from the WhatsApp booking deep-link toggle here).`;
