import type { ClassificationSurface } from './ai-classification-engine.types.js';

/** n99-2.2 — on-screen entity context resolves deictic prompts without clarify. */
export const N99_SCREEN_GROUNDING_SCENARIOS = [
  {
    id: 'dashboard-en-book-this',
    surface: 'dashboard' as ClassificationSurface,
    prompt: 'book this for tomorrow at 3pm',
    action: 'create_booking',
    params: { date: '2026-06-09', timeSlot: '15:00' },
    screenContext: {
      serviceName: 'Haircut',
      employeeName: 'Sam Rivera',
      employeeId: 'emp-1',
    },
    expectFilled: { serviceName: 'Haircut', employeeName: 'Sam Rivera' },
  },
  {
    id: 'dashboard-en-cancel-it',
    surface: 'dashboard' as ClassificationSurface,
    prompt: 'cancel this booking',
    action: 'cancel_bookings',
    params: {},
    screenContext: { bookingId: 'bk-screen-1', customerName: 'Maria Lopez' },
    expectFilled: { bookingId: 'bk-screen-1', customerName: 'Maria Lopez' },
  },
  {
    id: 'dashboard-en-remind-her',
    surface: 'dashboard' as ClassificationSurface,
    prompt: 'remind her about tomorrow',
    action: 'send_reminder',
    params: { date: '2026-06-09' },
    screenContext: { customerName: 'Maria Lopez', customerId: 'cust-9' },
    expectFilled: { customerName: 'Maria Lopez', customerId: 'cust-9' },
  },
  {
    id: 'dashboard-en-reschedule-it',
    surface: 'dashboard' as ClassificationSurface,
    prompt: 'reschedule it to Friday at 2pm',
    action: 'reschedule_booking',
    params: { date: '2026-06-13', timeSlot: '14:00' },
    screenContext: { bookingId: 'bk-88', serviceName: 'Massage' },
    expectFilled: { bookingId: 'bk-88', serviceName: 'Massage' },
  },
  {
    id: 'dashboard-hy-book-this',
    surface: 'dashboard' as ClassificationSurface,
    prompt: 'ամրագրել սա վաղը',
    action: 'create_booking',
    params: { date: '2026-06-09' },
    screenContext: { serviceName: 'Massage', employeeName: 'Anna Smith' },
    expectFilled: { serviceName: 'Massage', employeeName: 'Anna Smith' },
  },
  {
    id: 'dashboard-ru-cancel-this',
    surface: 'dashboard' as ClassificationSurface,
    prompt: 'отмени это',
    action: 'cancel_bookings',
    params: {},
    screenContext: { bookingId: 'bk-42', customerName: 'Maria Lopez' },
    expectFilled: { bookingId: 'bk-42' },
  },
  {
    id: 'provider-en-mark-paid-this',
    surface: 'provider_mobile' as ClassificationSurface,
    prompt: 'mark this as paid',
    action: 'mark_paid',
    params: {},
    screenContext: { bookingId: 'bk-prov-1', customerName: 'John Doe' },
    expectFilled: { bookingId: 'bk-prov-1', customerName: 'John Doe' },
  },
  {
    id: 'provider-en-cancel-it',
    surface: 'provider_mobile' as ClassificationSurface,
    prompt: 'cancel it',
    action: 'cancel_bookings',
    params: {},
    screenContext: { bookingId: 'bk-prov-2' },
    expectFilled: { bookingId: 'bk-prov-2' },
  },
  {
    id: 'customer-en-book-this',
    surface: 'customer' as ClassificationSurface,
    prompt: 'book this tomorrow',
    action: 'book_appointment',
    params: { date: '2026-06-09' },
    screenContext: { serviceName: 'Facial', employeeName: 'Lena Park' },
    expectFilled: { serviceName: 'Facial', employeeName: 'Lena Park' },
  },
  {
    id: 'customer-en-cancel-it',
    surface: 'customer' as ClassificationSurface,
    prompt: 'cancel it please',
    action: 'cancel_booking',
    params: {},
    screenContext: { bookingId: 'bk-cust-1' },
    expectFilled: { bookingId: 'bk-cust-1' },
  },
  {
    id: 'public-en-book-this-slot',
    surface: 'public' as ClassificationSurface,
    prompt: 'book this',
    action: 'book_appointment',
    params: {},
    screenContext: {
      serviceName: 'Haircut',
      employeeName: 'Alex Kim',
      date: '2026-06-09',
      timeSlot: '10:00',
    },
    expectFilled: {
      serviceName: 'Haircut',
      employeeName: 'Alex Kim',
      date: '2026-06-09',
      timeSlot: '10:00',
    },
  },
  {
    id: 'public-en-check-this',
    surface: 'public' as ClassificationSurface,
    prompt: 'is this slot still available?',
    action: 'check_availability',
    params: {},
    screenContext: {
      serviceName: 'Color',
      employeeName: 'Sam',
      date: '2026-06-09',
      timeSlot: '14:00',
    },
    expectFilled: {
      serviceName: 'Color',
      employeeName: 'Sam',
      date: '2026-06-09',
      timeSlot: '14:00',
    },
  },
  {
    id: 'dashboard-calendar-selection',
    surface: 'dashboard' as ClassificationSurface,
    prompt: 'book massage here tomorrow 10am',
    action: 'create_booking',
    params: { serviceName: 'Massage', date: '2026-06-09', timeSlot: '10:00' },
    screenContext: {
      selectionDate: '2026-06-09',
      selectionEmployeeId: 'emp-7',
      employeeName: 'Gevorg Gasparyan',
    },
    expectFilled: {
      selectionDate: '2026-06-09',
      selectionEmployeeId: 'emp-7',
      employeeName: 'Gevorg Gasparyan',
    },
  },
  {
    id: 'dashboard-passive-screen-fill',
    surface: 'dashboard' as ClassificationSurface,
    prompt: 'send reminder for tomorrow',
    action: 'send_reminder',
    params: { date: '2026-06-09' },
    screenContext: { customerName: 'Maria Lopez', bookingId: 'bk-9' },
    expectFilled: { customerName: 'Maria Lopez', bookingId: 'bk-9' },
  },
] as const;

export const N99_SCREEN_GROUNDING_TRIM_SCENARIOS = [
  {
    id: 'trim-customer-from-screen',
    action: 'send_reminder',
    params: { date: '2026-06-09' },
    screenContext: { customerName: 'Maria Lopez' },
    issues: [{ field: 'customerName', message: 'Which customer?' }],
    expectTrimmedFields: ['customerName'],
  },
  {
    id: 'trim-booking-from-screen',
    action: 'cancel_bookings',
    params: {},
    screenContext: { bookingId: 'bk-1' },
    issues: [{ field: 'bookingId', message: 'Which booking?' }],
    expectTrimmedFields: ['bookingId'],
  },
] as const;
