/** Dashboard retail/finance classifier rules. */
export const RETAIL_FINANCE_DASHBOARD_CLASSIFIER_RULES = `- list_products / create_product / link_product_to_service / adjust_inventory / add_retail_sale_to_booking / remove_retail_line / record_expense / list_expenses / summarize_pl / commission_report / payout_export: inventory, retail POS, and finance (Sprint 33).
- suggest_retail_upsell / add_retail_to_my_booking: provider retail at chair (Sprint 33).
- update_inventory_product: MUTATE — edit an existing product's name/SKU/retail price/unit cost/reorder level, or toggle active status. Requires productName or productId plus at least one field. NOT create_product (new row), NOT adjust_inventory (stock quantity only).
- delete_inventory_product: MUTATE — remove a product from the active catalog (soft — deactivates it). Requires productName or productId.
- unlink_inventory_product: MUTATE — remove a product-to-service link so the product no longer auto-deducts for that service. Requires linkId, or both productName and serviceName. NOT link_product_to_service (creates the link).
- set_recommended_products: MUTATE — bulk-replace the full list of checkout-recommended products for a service or category in one call. Requires serviceName (or categoryId) plus productIds or productNames. "Recommend shampoo and conditioner for the haircut service" → set_recommended_products, serviceName=haircut, productNames=["shampoo","conditioner"].
- delete_expense: MUTATE — delete a recorded expense. Requires expenseId, or category/description to match. NOT record_expense (creates one).
- create_commission_rule: MUTATE — set up a commission rule (percent or flat amount) for an employee and/or service. Requires value; optional employeeName, serviceName, type=percent|flat (default percent).
- delete_commission_rule: MUTATE — remove a commission rule. Requires ruleId, or employeeName/serviceName to match.
- export_analytics_report: MUTATE — generate the business analytics report (staff performance, service popularity, P&L) as a CSV or printable HTML document. Optional from/to date range, locationId, format=csv|pdf (default csv). NOT summarize_pl (single P&L narration only, no exportable file), NOT payout_export (commission payouts only).
- summarize_reviews: READ — summarize customer review ratings and counts, overall or per employee. Optional employeeId to scope to one provider. NOT list_provider_reviews (public-facing per-provider review list on the booking site).
- summarize_adoption_funnel: READ — summarize the consumer app adoption funnel (install → sign-in → book → rebook step counts and conversion) over a period. Optional periodDays (7-90, default 30). NOT summarize_new_registrations (customer sign-up count only, no app funnel steps).`;
