import type { CommandSurface } from './ai-command-registry.types.js';

export interface SemanticParaphraseScenario {
  id: string;
  prompt: string;
  surface: CommandSurface;
  expectedAction: string;
  expectedParamHints?: Record<string, unknown>;
  locale?: 'en' | 'hy' | 'ru';
  /** Classifier action that should trigger semantic escalation. */
  classifyAction?: string;
  classifyConfidence?: number;
}

/** Paraphrase corpus for semantic matcher (acc-3.16). */
export const SEMANTIC_PARAPHRASE_SCENARIOS: SemanticParaphraseScenario[] = [
  {
    id: 'en-gap-soonest-booking',
    prompt: 'Book massage tomorrow on whoever has a gap soonest',
    surface: 'dashboard',
    expectedAction: 'create_booking',
    expectedParamHints: { bookingFirstAvailable: true },
    classifyAction: 'unknown',
    classifyConfidence: 0.2,
  },
  {
    id: 'en-whichever-provider-free',
    prompt: 'Schedule with whichever provider is free first tomorrow afternoon',
    surface: 'dashboard',
    expectedAction: 'create_booking',
    expectedParamHints: { bookingFirstAvailable: true },
    classifyAction: 'unknown',
    classifyConfidence: 0.25,
  },
  {
    id: 'en-next-open-slot',
    prompt: 'Grab the next open slot for a haircut on any stylist',
    surface: 'dashboard',
    expectedAction: 'create_booking',
    expectedParamHints: { bookingFirstAvailable: true },
    classifyAction: 'unknown',
    classifyConfidence: 0.3,
  },
  {
    id: 'en-earliest-opening',
    prompt: 'Put me in the earliest opening you have this week',
    surface: 'dashboard',
    expectedAction: 'create_booking',
    expectedParamHints: { bookingFirstAvailable: true },
    classifyAction: 'unknown',
    classifyConfidence: 0.22,
  },
  {
    id: 'en-asap-any-slot',
    prompt: 'Need an appointment ASAP on any available slot',
    surface: 'dashboard',
    expectedAction: 'create_booking',
    expectedParamHints: { bookingFirstAvailable: true },
    classifyAction: 'unknown',
    classifyConfidence: 0.18,
  },
  {
    id: 'en-who-has-gap',
    prompt: 'Who has a gap soonest tomorrow for massage',
    surface: 'dashboard',
    expectedAction: 'check_providers_for_service',
    classifyAction: 'unknown',
    classifyConfidence: 0.2,
  },
  {
    id: 'en-who-can-perform',
    prompt: 'Which specialist can perform color and has time Friday',
    surface: 'dashboard',
    expectedAction: 'check_providers_for_service',
    classifyAction: 'unknown',
    classifyConfidence: 0.28,
  },
  {
    id: 'en-team-availability',
    prompt: 'See who on the team is open tomorrow morning',
    surface: 'dashboard',
    expectedAction: 'check_providers_for_service',
    classifyAction: 'unknown',
    classifyConfidence: 0.24,
  },
  {
    id: 'en-implied-trim',
    prompt: 'My hair is getting pretty long, need a trim soon',
    surface: 'dashboard',
    expectedAction: 'create_booking',
    classifyAction: 'unknown',
    classifyConfidence: 0.2,
  },
  {
    id: 'en-implied-schedule-hours',
    prompt: 'They need regular work time on the calendar next week',
    surface: 'dashboard',
    expectedAction: 'create_direct_schedule',
    classifyAction: 'unknown',
    classifyConfidence: 0.22,
  },
  {
    id: 'en-nearest-slot-haircut',
    prompt: 'Book the nearest open slot for a haircut tomorrow',
    surface: 'dashboard',
    expectedAction: 'book_nearest_slot',
    expectedParamHints: { bookingFirstAvailable: true },
    classifyAction: 'unknown',
    classifyConfidence: 0.2,
  },
  {
    id: 'en-soonest-massage-slot',
    prompt: 'Grab the soonest available massage appointment this week',
    surface: 'dashboard',
    expectedAction: 'book_nearest_slot',
    expectedParamHints: { bookingFirstAvailable: true },
    classifyAction: 'unknown',
    classifyConfidence: 0.22,
  },
  {
    id: 'en-earliest-color-opening',
    prompt: 'Book the nearest available slot for color services this week',
    surface: 'dashboard',
    expectedAction: 'book_nearest_slot',
    expectedParamHints: { bookingFirstAvailable: true },
    classifyAction: 'unknown',
    classifyConfidence: 0.24,
  },
  {
    id: 'en-next-free-lashes',
    prompt: 'Grab the soonest free slot for lashes as soon as possible',
    surface: 'dashboard',
    expectedAction: 'book_nearest_slot',
    expectedParamHints: { bookingFirstAvailable: true },
    classifyAction: 'unknown',
    classifyConfidence: 0.21,
  },
  {
    id: 'en-first-open-stylist',
    prompt: 'Find the nearest open stylist slot on your schedule',
    surface: 'dashboard',
    expectedAction: 'book_nearest_slot',
    expectedParamHints: { bookingFirstAvailable: true },
    classifyAction: 'unknown',
    classifyConfidence: 0.23,
  },
  {
    id: 'hy-nearest-slot',
    prompt: 'ամրագրիր մոտակա ազատ ժամը մերսման համար վաղը',
    surface: 'dashboard',
    expectedAction: 'book_nearest_slot',
    expectedParamHints: { bookingFirstAvailable: true },
    locale: 'hy',
    classifyAction: 'unknown',
    classifyConfidence: 0.2,
  },
  {
    id: 'ru-nearest-slot',
    prompt: 'Забронируй ближайший свободный слот как можно скорее',
    surface: 'dashboard',
    expectedAction: 'book_nearest_slot',
    expectedParamHints: { bookingFirstAvailable: true },
    locale: 'ru',
    classifyAction: 'unknown',
    classifyConfidence: 0.2,
  },
  {
    id: 'hy-gap-soonest',
    prompt: 'Վաղը մասաժըի համար ամենամոտ ազատ ժամը գրանցիր',
    surface: 'dashboard',
    expectedAction: 'create_booking',
    expectedParamHints: { bookingFirstAvailable: true },
    classifyAction: 'unknown',
    classifyConfidence: 0.2,
  },
  {
    id: 'ru-gap-soonest',
    prompt: 'Запиши на ближайшее свободное время на массаж завтра',
    surface: 'dashboard',
    expectedAction: 'create_booking',
    expectedParamHints: { bookingFirstAvailable: true },
    classifyAction: 'unknown',
    classifyConfidence: 0.2,
  },
  {
    id: 'hy-who-free',
    prompt: 'Ով է ազատ վաղը մասաժի համար',
    surface: 'dashboard',
    expectedAction: 'check_providers_for_service',
    classifyAction: 'unknown',
    classifyConfidence: 0.2,
  },
  {
    id: 'ru-who-free',
    prompt: 'Кто свободен завтра для стрижки',
    surface: 'dashboard',
    expectedAction: 'check_providers_for_service',
    classifyAction: 'unknown',
    classifyConfidence: 0.2,
  },
  {
    id: 'en-high-confidence-skip',
    prompt: 'Show me today appointments',
    surface: 'dashboard',
    expectedAction: 'show_appointments',
    classifyAction: 'show_appointments',
    classifyConfidence: 0.92,
  },
];
