import {
  PIPELINE_MUTATING_ACTIONS_PIPE_MARKER,
  PIPELINE_SCHEDULE_RESOLVED_INTENTS,
} from './command-pipeline-mutating-actions.fixtures.js';

export {
  PIPELINE_MUTATING_ACTIONS_PIPE_MARKER,
  PIPELINE_SCHEDULE_RESOLVED_INTENTS,
};

/**
 * Dashboard intents that must not auto-execute below confidence.low (pipe-1.9.1).
 * Includes schedule mutations resolved by the understand pipeline.
 */
export const DASHBOARD_PIPELINE_MUTATING_ACTIONS = new Set<string>([
  'create_booking',
  'create_service',
  'create_services',
  'cancel_bookings',
  'update_bookings',
  'bulk_smart_cancel',
  'hide_appointments_from_calendar',
  'unhide_appointments_from_calendar',
  'fill_slot_from_waitlist',
  'reschedule_booking',
  'fill_unused_slots',
  'apply_schedule',
  'create_direct_schedule',
  'clear_schedule',
  'block_schedule',
  'setup_week_schedule',
  'swap_schedules',
  'rebalance_capacity',
  'holiday_mode',
  'onboard_provider_schedule',
  'create_schedule_template',
  'mark_no_shows',
  'no_show_recovery',
  'payment_sweep',
  'day_replan',
  'sick_day_replan',
  'import_services_from_menu',
  'update_service_prices',
  'staff_service_matrix',
  'create_booking_subscription_credit',
  'create_booking_cash',
  'create_package_booking',
  'create_multi_service_booking',
  'cancel_package_visit',
  'cancel_multi_service_group',
  'reschedule_package_visit',
  'reschedule_multi_service_group',
  'mark_paid',
  'assign_booking_resource',
  'create_service_category',
  'bulk_create_catalog',
  'update_service',
  'unassign_employee_services',
  'transfer_employee_services',
  'deactivate_service',
  'create_package',
  'update_package',
  'deactivate_package',
  'duplicate_package',
  'create_subscription_plan',
  'update_subscription_plan',
  'deactivate_subscription_plan',
  'assign_subscription_to_customer',
  'configure_gift_card_products',
  'create_gift_card_bundle',
  'configure_multi_service_settings',
  'set_service_compatibility',
  'extend_subscription',
  'cancel_subscription_admin',
  'merge_customers',
  'export_customer_data',
  'delete_customer_data',
  'send_reengagement_message',
  'tag_customer',
  'request_gift_card_cancel',
  'request_gift_card_modify',
  'privacy_export',
  'privacy_delete',
  'create_resource',
  'update_resource',
  'deactivate_resource',
  'assign_resource_hours',
  'configure_multi_service_scheduling_mode',
  'block_resource_unavailable',
  'configure_cash_payments',
  'configure_business_currency',
  'configure_business_tax',
  'configure_privacy_retention',
  'configure_granular_consent',
  'enable_hipaa_mode',
  'configure_hipaa_session_timeout',
  'admin_delete_customer_data',
  'report_data_breach',
  'send_breach_notification',
  'configure_stacked_tax_rules',
  'set_service_tax_rate',
  'configure_business_languages',
  'configure_business_date_format',
  'configure_package_localized_names',
  'configure_tour_service',
  'configure_clinic_service',
  'apply_clinic_playbook',
  'configure_recommendation_product',
  'link_recommended_products',
  'apply_tour_playbook',
  'bulk_strip_disabled_locale_translations',
  'migrate_dashboard_date_display',
  'notify_patient_result_ready',
  'create_test_order',
  'create_catalog_test_order',
  'push_lab_booking_to_patient',
  'staff_book_lab_collection',
  'enter_test_result',
  'release_test_result',
  'bulk_update_service_currency',
  'adjust_gift_card_balance',
  'extend_gift_card_expiry',
  'refund_gift_card_order',
  'collect_cash_confirm',
  'assign_card_creator',
  'assign_delivery_staff',
  'mark_shipped',
  'mark_delivered',
  'cancel_gift_card_order',
  'extend_cancel_window',
  'start_card_preparation',
  'mark_card_ready',
  'accept_delivery',
  'mark_out_for_delivery',
  'capture_delivery_proof',
  'notify_delay',
  'enter_shipping_address',
  'create_webhook',
  'delete_webhook',
  'toggle_webhook',
  'rotate_api_key',
  'configure_zapier',
  'run_accounting_export',
  'configure_zendesk',
  'create_support_ticket',
  'sync_customer_to_zendesk',
  'configure_marketing_registration_email',
  'contact_support',
  'open_ticket_for_order',
  'configure_marketing_automation',
  'trigger_reengagement',
  'toggle_annual_billing',
  'configure_push_recipients',
  'test_push',
  'toggle_business_email_on_customer_change',
  'retry_offline_action',
  'dismiss_push',
  'enable_notifications',
]);

export function isDashboardPipelineMutatingAction(action: string): boolean {
  return DASHBOARD_PIPELINE_MUTATING_ACTIONS.has(action);
}

export function isPipelineScheduleResolvedIntent(
  action: string,
): action is (typeof PIPELINE_SCHEDULE_RESOLVED_INTENTS)[number] {
  return (PIPELINE_SCHEDULE_RESOLVED_INTENTS as readonly string[]).includes(
    action,
  );
}

/** Block auto-execute when a mutating intent is below confidence.low (pipe-1.9.1). */
export function shouldBlockLowConfidencePipelineMutate(
  action: string,
  confidence: number,
  lowThreshold: number,
): boolean {
  return (
    isDashboardPipelineMutatingAction(action) && confidence < lowThreshold
  );
}
