import type { CanonicalPhrasingBankDocument } from './intent-phrasing-bank.types.js';

/**
 * Canonical phrasing bank — per-intent EN/HY/RU utterances (acc-3.12 / pipe-1.4.1).
 * Add new rows here (data only). Generic phrases — no entity names.
 * Eval cases with useSemanticIntentMatch merge in at runtime via intent-anchor.bank.ts.
 */
export const CANONICAL_PHRASING_BANK: CanonicalPhrasingBankDocument = {
  version: 1,
  entries: [
    {
      id: 'en-book-first-available',
      action: 'create_booking',
      phrase: 'book the first available appointment slot',
      locale: 'en',
      surfaces: ['dashboard', 'customer'],
      paramHints: { bookingFirstAvailable: true },
      conceptGroups: [
        ['book', 'schedule', 'reserve', 'get', 'grab', 'want', 'need', 'put'],
        ['first', 'earliest', 'soonest', 'nearest', 'next', 'asap', 'gap'],
        ['available', 'free', 'open', 'opening', 'slot', 'time', 'appointment'],
      ],
    },
    {
      id: 'en-compound-check-book-asap',
      action: 'create_booking',
      phrase: 'who has availability tomorrow evening and book asap',
      locale: 'en',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { bookingFirstAvailable: true },
      conceptGroups: [
        ['availability', 'providers', 'free'],
        ['book', 'asap', 'nearest', 'soonest'],
        ['tomorrow', 'evening', 'massage', 'service', 'and'],
      ],
    },
    {
      id: 'en-book-gap-soonest',
      action: 'create_booking',
      phrase: 'whoever has a gap soonest book on any provider',
      locale: 'en',
      surfaces: ['dashboard', 'customer'],
      paramHints: { bookingFirstAvailable: true, allProviders: true },
      conceptGroups: [
        ['book', 'schedule', 'reserve', 'get', 'grab', 'whoever', 'whichever'],
        ['gap', 'soonest', 'earliest', 'first', 'nearest', 'next', 'asap'],
        ['available', 'free', 'open', 'provider', 'specialist', 'any'],
      ],
    },
    {
      id: 'en-asap-booking',
      action: 'create_booking',
      phrase: 'schedule as soon as possible on any open slot',
      locale: 'en',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { bookingFirstAvailable: true },
      conceptGroups: [
        ['book', 'schedule', 'reserve', 'get', 'grab', 'need'],
        [
          'asap',
          'soon',
          'soonest',
          'earliest',
          'urgent',
          'quickly',
          'possible',
        ],
        ['slot', 'time', 'appointment', 'available', 'open', 'free', 'any'],
      ],
    },
    {
      id: 'en-nearest-free-time',
      action: 'create_booking',
      phrase: 'move appointment to nearest free time on the calendar',
      locale: 'en',
      surfaces: ['dashboard', 'customer'],
      paramHints: { bookingFirstAvailable: true },
      conceptGroups: [
        ['move', 'reschedule', 'shift', 'change'],
        ['nearest', 'earliest', 'soonest', 'next', 'first'],
        ['free', 'available', 'open', 'time', 'slot'],
      ],
    },
    {
      id: 'ru-book-or-alternative',
      action: 'create_booking',
      phrase: 'book tomorrow evening or saturday whichever is sooner',
      locale: 'ru',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { bookingFirstAvailable: true },
      conceptGroups: [
        ['забронир', 'запиш', 'заказ', 'оформ'],
        ['или', 'суббот', 'вечер', 'завтра'],
        ['стрижк', 'услуг', 'время', 'слот', 'массаж'],
      ],
    },
    {
      id: 'en-implied-haircut-need',
      action: 'create_booking',
      phrase: 'my hair is getting pretty long need a trim soon',
      locale: 'en',
      surfaces: ['dashboard', 'customer', 'public'],
      conceptGroups: [
        ['hair', 'trim', 'cut', 'long', 'shaggy', 'roots', 'color'],
        ['need', 'want', 'time', 'due', 'overdue', 'getting'],
        ['soon', 'appointment', 'book', 'schedule', 'visit'],
      ],
    },
    {
      id: 'en-implied-wellness-need',
      action: 'create_booking',
      phrase: 'overdue for a wellness visit need a session soon',
      locale: 'en',
      surfaces: ['dashboard', 'customer', 'public'],
      conceptGroups: [
        [
          'hair',
          'nails',
          'chipped',
          'trim',
          'cut',
          'long',
          'roots',
          'color',
          'facial',
          'massage',
          'manicure',
          'beard',
          'brows',
          'dental',
          'physio',
          'shaping',
          'touch',
          'cleaning',
          'unkempt',
          'unruly',
          'tense',
        ],
        [
          'need',
          'want',
          'due',
          'overdue',
          'months',
          'getting',
          'feel',
          'could',
          'use',
        ],
        ['soon', 'visit', 'session', 'appointment', 'weekend', 'before'],
      ],
    },
    {
      id: 'hy-book-first-available',
      action: 'create_booking',
      phrase: 'ամենաառաջին ազատ ժամանակին գրանցել',
      locale: 'hy',
      surfaces: ['dashboard', 'customer'],
      paramHints: { bookingFirstAvailable: true },
      conceptGroups: [
        ['գրանց', 'ամրագր', 'պատվիր', 'վերցն'],
        ['առաջին', 'մոտակա', 'հաջորդ', 'շուտ', 'ամենամոտ'],
        ['ազատ', 'ժամ', 'ժամանակ', 'տեղ'],
      ],
    },
    {
      id: 'ru-book-first-available',
      action: 'create_booking',
      phrase: 'записать на ближайшее свободное время',
      locale: 'ru',
      surfaces: ['dashboard', 'customer'],
      paramHints: { bookingFirstAvailable: true },
      conceptGroups: [
        ['запис', 'забронир', 'заказ', 'оформ'],
        ['ближайш', 'перв', 'следующ', 'скор'],
        ['свободн', 'время', 'слот', 'окно'],
      ],
    },
    {
      id: 'hy-implied-trim-need',
      action: 'create_booking',
      phrase: 'մազերս երկար են դարձել շուտով կտրվածքի կարիք ունեմ',
      locale: 'hy',
      surfaces: ['dashboard', 'customer'],
      conceptGroups: [
        ['մազ', 'կտրվածք', 'երկար', 'շուտ'],
        ['կարիք', 'պետք', 'ուզում'],
        ['գրանց', 'ամրագր', 'ժամ'],
      ],
    },
    {
      id: 'ru-implied-trim-need',
      action: 'create_booking',
      phrase: 'волосы стали длинными нужна стрижка скоро',
      locale: 'ru',
      surfaces: ['dashboard', 'customer'],
      conceptGroups: [
        ['волос', 'стрижк', 'длинн'],
        ['нужн', 'пора', 'скоро'],
        ['запис', 'забронир', 'время'],
      ],
    },
    {
      id: 'hy-implied-wellness-need',
      action: 'create_booking',
      phrase: 'ժամանակն է մանիկյուրի և շտկման կարիք ունեմ շուտով',
      locale: 'hy',
      surfaces: ['dashboard', 'customer', 'public'],
      conceptGroups: [
        [
          'եղունգ',
          'կոտրվ',
          'մանիկյուր',
          'գույն',
          'ռեգեն',
          'դեմք',
          'մերսում',
          'մեջք',
          'մորուք',
          'հաճ',
          'ատամ',
          'մաքրում',
        ],
        [
          'կարիք',
          'պետք',
          'ուզում',
          'ժամանակ',
          'հնաց',
          'լարված',
          'խլմուկ',
          'խաչաձև',
          'շատ',
          'սեսիա',
        ],
        ['շուտ', 'այց', 'սեսիա', 'շաբաթ', 'ամիս', 'վերջ', 'թարմաց'],
      ],
    },
    {
      id: 'ru-implied-wellness-need',
      action: 'create_booking',
      phrase: 'давно не была на маникюре нужно записаться скоро',
      locale: 'ru',
      surfaces: ['dashboard', 'customer', 'public'],
      conceptGroups: [
        [
          'ногт',
          'маникюр',
          'слом',
          'окраш',
          'корн',
          'освеж',
          'лиц',
          'массаж',
          'бород',
          'бров',
          'зуб',
          'чистк',
        ],
        [
          'нужн',
          'пора',
          'давно',
          'хочу',
          'напряж',
          'неряшл',
          'неровн',
          'очень',
          'освеж',
        ],
        ['скоро', 'визит', 'сесси', 'недел', 'месяц', 'выходн', 'снова'],
      ],
    },
    {
      id: 'en-book-nearest-slot',
      action: 'book_nearest_slot',
      phrase: 'book the nearest available time slot',
      locale: 'en',
      surfaces: ['dashboard', 'customer'],
      paramHints: { bookingFirstAvailable: true },
      conceptGroups: [
        ['book', 'find', 'get', 'reserve', 'schedule', 'grab'],
        ['nearest', 'soonest', 'earliest', 'first', 'next', 'asap', 'gap'],
        ['slot', 'time', 'appointment', 'opening', 'available', 'free'],
      ],
    },
    {
      id: 'hy-book-nearest-slot',
      action: 'book_nearest_slot',
      phrase: 'ամրագրիր մոտակա ազատ slot-ը',
      locale: 'hy',
      surfaces: ['dashboard', 'customer'],
      paramHints: { bookingFirstAvailable: true },
      conceptGroups: [
        ['գրանց', 'ամրագր', 'վերցն'],
        ['մոտակա', 'առաջին', 'հաջորդ', 'շուտ', 'ամենամոտ'],
        ['ազատ', 'ժամ', 'slot', 'տեղ', 'massage', 'երեկո', 'վաղ'],
      ],
    },
    {
      id: 'translit-book-nearest-slot',
      action: 'book_nearest_slot',
      phrase: 'amsagrum blizhayshee massage vecherom',
      locale: 'translit',
      surfaces: ['dashboard', 'customer'],
      paramHints: { bookingFirstAvailable: true },
      conceptGroups: [
        ['amsagrum', 'zabronir', 'zapis', 'amsagir'],
        ['blizhaysh', 'perviy', 'skoreysh', 'moytaka', 'blizhayshee'],
        ['massage', 'slot', 'vecher', 'vagh', 'vecherom'],
      ],
    },
    {
      id: 'ru-book-nearest-slot',
      action: 'book_nearest_slot',
      phrase: 'запиши ближайший свободный слот',
      locale: 'ru',
      surfaces: ['dashboard', 'customer'],
      paramHints: { bookingFirstAvailable: true },
      conceptGroups: [
        ['запис', 'забронир', 'оформ'],
        ['ближайш', 'перв', 'следующ', 'скор'],
        ['свободн', 'слот', 'время', 'окно'],
      ],
    },
    {
      id: 'en-check-who-free',
      action: 'check_providers_for_service',
      phrase: 'who is free tomorrow for a service',
      locale: 'en',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true },
      conceptGroups: [
        ['who', 'which', 'anyone', 'anybody', 'team'],
        [
          'free',
          'available',
          'open',
          'doing',
          'performing',
          'can',
          'has',
          'availability',
          'slot',
          'time',
        ],
        ['tomorrow', 'today', 'week', 'afternoon', 'morning', 'evening', 'for'],
      ],
    },
    {
      id: 'en-free-slots-for-service',
      action: 'check_providers_for_service',
      phrase: 'any free slots for facial on friday afternoon',
      locale: 'en',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true },
      conceptGroups: [
        ['free', 'available', 'open', 'any', 'slots', 'slot'],
        ['for', 'on', 'friday', 'monday', 'tomorrow', 'afternoon', 'service'],
        ['who', 'which', 'anyone', 'facial', 'massage', 'highlights'],
      ],
    },
    {
      id: 'en-implied-availability-opening',
      action: 'check_providers_for_service',
      phrase: 'wondering if anyone can fit me in for a service soon',
      locale: 'en',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true },
      conceptGroups: [
        [
          'wondering',
          'trying',
          'hoping',
          'curious',
          'looking',
          'need',
          'chance',
          'someone',
          'anybody',
          'anyone',
          'staff',
          'team',
          'members',
          'floor',
          'before',
          'not',
          'sure',
          'see',
          'want',
          'there',
          'which',
        ],
        [
          'fit',
          'opening',
          'openings',
          'room',
          'squeeze',
          'handle',
          'take',
          'time',
          'slot',
          'can',
          'has',
          'doing',
          'clients',
          'package',
          'blowouts',
          'highlights',
          'facial',
          'brows',
          'shaping',
          'color',
          'makeup',
          'trim',
          'lashes',
          'massage',
        ],
        [
          'tomorrow',
          'today',
          'week',
          'friday',
          'saturday',
          'thursday',
          'morning',
          'evening',
          'night',
          'tonight',
          'afternoon',
          'service',
        ],
      ],
    },
    {
      id: 'hy-implied-availability-opening',
      action: 'check_providers_for_service',
      phrase: 'հետաքրքրում է՝ արդյոք մեկը ազատ է վաղը ծառայության համար',
      locale: 'hy',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true },
      conceptGroups: [
        [
          'հետաքրքր',
          'հույս',
          'փորձ',
          'չգիտ',
          'փնտր',
          'նախքան',
          'որոշ',
          'մեկ',
          'թիմ',
          'հարկ',
          'մասնագետ',
          'ինչ',
        ],
        [
          'ազատ',
          'տեղ',
          'slot',
          'կարող',
          'ունի',
          'հասանելի',
          'մերսում',
          'կտրվածք',
          'դեմք',
          'հաճ',
          'գույն',
          'թարմացում',
          'highlight',
          'blowout',
          'spa',
          'package',
          'հասկանալ',
        ],
        [
          'վաղը',
          'այսօր',
          'շաբաթ',
          'ուրբաթ',
          'շաբաթ',
          'հինգշաբթ',
          'առավոտ',
          'երեկո',
          'գիշեր',
          'կեսօր',
          'ծառայ',
        ],
      ],
    },
    {
      id: 'ru-implied-availability-opening',
      action: 'check_providers_for_service',
      phrase:
        'надеюсь кто-то из персонала сможет сделать услугу завтра вечером',
      locale: 'ru',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true },
      conceptGroups: [
        [
          'интерес',
          'наде',
          'пыта',
          'ищу',
          'прежде',
          'неувер',
          'уверен',
          'кто',
          'коман',
          'смен',
          'мастер',
          'персонал',
          'кого',
        ],
        [
          'окно',
          'свобод',
          'мест',
          'слот',
          'может',
          'есть',
          'сделать',
          'массаж',
          'стрижк',
          'лиц',
          'бров',
          'окраш',
          'окрашиван',
          'мелир',
          'укладк',
          'spa',
          'ресниц',
          'highlight',
          'мелир',
          'вечер',
          'ноч',
        ],
        [
          'завтра',
          'сегодня',
          'недел',
          'пятниц',
          'суббот',
          'четверг',
          'утр',
          'вечер',
          'ноч',
          'днем',
          'услуг',
        ],
      ],
    },
    {
      id: 'en-check-who-can-do',
      action: 'check_providers_for_service',
      phrase: 'who can do this service and has an open slot',
      locale: 'en',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true },
      conceptGroups: [
        ['who', 'which', 'anyone', 'anybody'],
        ['can', 'able', 'perform', 'do', 'give', 'offer', 'provide'],
        ['check', 'see', 'find', 'show', 'look', 'list'],
        ['slot', 'time', 'available', 'free', 'open', 'service'],
      ],
    },
    {
      id: 'en-check-any-provider',
      action: 'check_providers_for_service',
      phrase: 'check any provider availability for the service',
      locale: 'en',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true },
      conceptGroups: [
        ['check', 'see', 'find', 'show', 'look'],
        ['provider', 'specialist', 'stylist', 'therapist', 'staff', 'any'],
        ['available', 'free', 'open', 'slot', 'time', 'service'],
      ],
    },
    {
      id: 'hy-check-who-free',
      action: 'check_providers_for_service',
      phrase: 'ով է ազատ վաղը համար ծառայության',
      locale: 'hy',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true },
      conceptGroups: [
        ['ով', 'ովքեր', 'մասնագետ', 'չգիտ'],
        ['ազատ', 'հասանելի', 'կարող', 'անում', 'գույն'],
        ['վաղը', 'այսօր', 'ժամ', 'ծառայ', 'կեսօր'],
      ],
    },
    {
      id: 'ru-check-who-free',
      action: 'check_providers_for_service',
      phrase: 'кто свободен завтра для услуги',
      locale: 'ru',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true },
      conceptGroups: [
        ['кто', 'какой', 'мастер', 'специалист', 'уверен'],
        ['свободн', 'доступн', 'может', 'делает', 'окраш'],
        ['завтра', 'сегодня', 'время', 'услуг', 'днем'],
      ],
    },
    {
      id: 'translit-check-who-free',
      action: 'check_providers_for_service',
      phrase: 'kto svoboden zavtra vecherom dlya uslugi',
      locale: 'translit',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true },
      conceptGroups: [
        ['kto', 'kakoy', 'master', 'spetsialist'],
        ['svobod', 'dostup', 'mozhet', 'svoboden'],
        [
          'zavtra',
          'vecherom',
          'dlya',
          'uslugi',
          'permanent',
          'lashes',
          'massage',
        ],
      ],
    },
    {
      id: 'hy-check-any-provider',
      action: 'check_providers_for_service',
      phrase: 'ով մասնագետն է ազատ վաղը ծառայության համար',
      locale: 'hy',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true },
      conceptGroups: [
        ['ով', 'մասնագետ', 'ցանկ'],
        ['ազատ', 'հասանելի', 'կարող'],
        ['վաղը', 'ծառայ', 'ժամ'],
      ],
    },
    {
      id: 'ru-check-any-provider',
      action: 'check_providers_for_service',
      phrase: 'проверь кто из мастеров свободен завтра для услуги',
      locale: 'ru',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true },
      conceptGroups: [
        ['провер', 'покаж', 'найд', 'кто', 'мастер'],
        ['свободн', 'доступн', 'может'],
        ['завтра', 'услуг', 'время'],
      ],
    },
    {
      id: 'en-set-work-hours',
      action: 'create_direct_schedule',
      phrase: 'set work hours for the provider on weekdays',
      locale: 'en',
      surfaces: ['dashboard'],
      conceptGroups: [
        ['schedule', 'hours', 'shift', 'work', 'working', 'roster'],
        ['set', 'create', 'add', 'open', 'block', 'plan'],
        ['weekday', 'monday', 'tuesday', 'week', 'day', 'time'],
      ],
    },
    {
      id: 'en-implied-work-time',
      action: 'create_direct_schedule',
      phrase: 'they need regular work time on the calendar',
      locale: 'en',
      surfaces: ['dashboard'],
      conceptGroups: [
        ['work', 'working', 'shift', 'hours', 'schedule', 'roster'],
        ['need', 'want', 'regular', 'usual', 'normal'],
        ['calendar', 'week', 'day', 'time', 'provider', 'staff'],
      ],
    },
    {
      id: 'en-implied-shift-roster',
      action: 'create_direct_schedule',
      phrase: 'new hire needs standard shifts on the roster next month',
      locale: 'en',
      surfaces: ['dashboard'],
      conceptGroups: [
        [
          'hire',
          'staff',
          'team',
          'member',
          'stylist',
          'shift',
          'hours',
          'blocks',
          'work',
        ],
        [
          'need',
          'usual',
          'regular',
          'normal',
          'standard',
          'recurring',
          'operating',
          'coverage',
          'block',
        ],
        [
          'roster',
          'calendar',
          'grid',
          'schedule',
          'week',
          'weekday',
          'weekdays',
          'month',
          'planner',
          'morning',
          'friday',
          'afternoons',
          'coming',
          'through',
        ],
      ],
    },
    {
      id: 'hy-implied-work-time',
      action: 'create_direct_schedule',
      phrase: 'կանոնավոր աշխատանքային ժամանակի կարիք ունի օրացույցում',
      locale: 'hy',
      surfaces: ['dashboard'],
      conceptGroups: [
        ['աշխատանք', 'ժամ', 'հերթ', 'գրաֆիկ', 'աշխատակից'],
        ['կարիք', 'կանոնավոր', 'սովորական', 'նորմալ'],
        ['օրացույց', 'շաբաթ', 'օր', 'ժամանակ'],
      ],
    },
    {
      id: 'ru-implied-work-time',
      action: 'create_direct_schedule',
      phrase: 'нужно регулярное рабочее время в расписании',
      locale: 'ru',
      surfaces: ['dashboard'],
      conceptGroups: [
        ['рабоч', 'час', 'смен', 'график', 'сотрудник'],
        ['нужн', 'регуляр', 'обычн', 'нормальн'],
        ['календар', 'расписан', 'недел', 'день', 'время'],
      ],
    },
    {
      id: 'hy-implied-shift-roster',
      action: 'create_direct_schedule',
      phrase: 'նոր աշխատողին հերթացուցակում ստանդարտ հերթեր են պետք',
      locale: 'hy',
      surfaces: ['dashboard'],
      conceptGroups: [
        ['նոր', 'աշխատող', 'աշխատակից', 'հերթ', 'աշխատանք', 'բլոկ'],
        [
          'պետք',
          'կարիք',
          'ստանդարտ',
          'կրկնվող',
          'նորմալ',
          'ապահովում',
          'ավելացնել',
        ],
        [
          'հերթացուցակ',
          'գրաֆիկ',
          'պլաներ',
          'օրացույց',
          'շաբաթ',
          'ամիս',
          'առավոտ',
          'կեսօր',
          'ուրբաթ',
        ],
      ],
    },
    {
      id: 'ru-implied-shift-roster',
      action: 'create_direct_schedule',
      phrase: 'новому сотруднику нужны стандартные смены в графике',
      locale: 'ru',
      surfaces: ['dashboard'],
      conceptGroups: [
        ['нов', 'сотрудник', 'смен', 'рабоч', 'блок'],
        [
          'нужн',
          'стандарт',
          'повтор',
          'повторяющ',
          'обычн',
          'покрыт',
          'постав',
        ],
        [
          'график',
          'планировщ',
          'календар',
          'расписан',
          'недел',
          'месяц',
          'утр',
          'после',
          'пятниц',
        ],
      ],
    },
    {
      id: 'hy-set-work-hours',
      action: 'create_direct_schedule',
      phrase: 'սահմանել աշխատանքային ժամերը հաջորդ շաբաթվա համար',
      locale: 'hy',
      surfaces: ['dashboard'],
      conceptGroups: [
        [
          'աշխատանք',
          'ժամ',
          'գրաֆիկ',
          'հերթ',
          'աշխատանքային',
          'նորմալ',
          'պլաներ',
        ],
        ['սահման', 'ավելացն', 'բաց', 'կազմել', 'շաբլոն', 'հերթացուցակ'],
        ['շաբաթ', 'օր', 'ժամ', 'առաջիկա', 'համար'],
      ],
    },
    {
      id: 'ru-set-work-hours',
      action: 'create_direct_schedule',
      phrase: 'установить рабочие часы на следующую неделю',
      locale: 'ru',
      surfaces: ['dashboard'],
      conceptGroups: [
        ['рабоч', 'час', 'график', 'смен', 'обычн', 'нормальн', 'планиров'],
        ['установ', 'добав', 'откры', 'настро', 'шаблон'],
        ['недел', 'день', 'время', 'грядущ'],
      ],
    },
    {
      id: 'en-book-any-provider',
      action: 'create_booking',
      phrase: 'book with any available provider tomorrow',
      locale: 'en',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { allProviders: true, anyProviderBooking: true },
      conceptGroups: [
        ['book', 'schedule', 'reserve', 'create', 'grab'],
        ['any', 'whichever', 'whoever', 'whatever'],
        ['provider', 'stylist', 'specialist', 'staff', 'employee', 'therapist'],
        ['available', 'free', 'tomorrow', 'week', 'massage', 'facial'],
      ],
    },
    {
      id: 'hy-book-any-provider',
      action: 'create_booking',
      phrase: 'amragir masajets yets yets azat masnaget',
      locale: 'hy',
      surfaces: ['dashboard', 'customer'],
      paramHints: { allProviders: true, anyProviderBooking: true },
      conceptGroups: [
        ['գրանց', 'ամրագր', 'պատվիր', 'վերցն'],
        ['ցանկացած', 'յուրաքանչյուր', 'ով', 'վոր'],
        ['ազատ', 'մասնագետ', 'մասաժ', 'վաղ', 'հետ'],
      ],
    },
    {
      id: 'ru-book-any-provider',
      action: 'create_booking',
      phrase: 'zapishi na massazh s lyubym svobodnym masterom',
      locale: 'ru',
      surfaces: ['dashboard', 'customer'],
      paramHints: { allProviders: true, anyProviderBooking: true },
      conceptGroups: [
        ['запиш', 'запис', 'забронир', 'оформ'],
        ['люб', 'любой', 'какой', 'кого'],
        ['свободн', 'мастер', 'массаж', 'завтра', 'услуг'],
      ],
    },
    {
      id: 'en-recommend-best-rated',
      action: 'recommend_specialists',
      phrase: 'best rated specialists for massage this week',
      locale: 'en',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { recommendSpecialists: true },
      conceptGroups: [
        ['best', 'top', 'highest', 'highly', 'rated', 'rating', 'reviewed'],
        ['specialist', 'provider', 'stylist', 'therapist', 'doctor', 'masseur'],
        [
          'suggest',
          'recommend',
          'show',
          'who',
          'massage',
          'week',
          'service',
          'haircut',
          'highlights',
          'facial',
          'brows',
          'lashes',
        ],
      ],
    },
    {
      id: 'hy-recommend-best',
      action: 'recommend_specialists',
      phrase: 'arajarkir lavaguyn masnagetnerin mersman hamar',
      locale: 'hy',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { recommendSpecialists: true },
      conceptGroups: [
        ['առաջարկիր', 'arajark', 'nayir'],
        ['լավագույն', 'մասնագետներին', 'masnaget', 'mersman'],
        ['համար', 'orva', 'shabat'],
      ],
    },
    {
      id: 'ru-recommend-best',
      action: 'recommend_specialists',
      phrase: 'porekomenduy luchshih masterov dlya massazha',
      locale: 'ru',
      surfaces: ['dashboard', 'customer', 'public'],
      paramHints: { recommendSpecialists: true },
      conceptGroups: [
        ['порекомен', 'предлож', 'найди', 'лучш', 'top'],
        ['master', 'specialist', 'массаж', 'masseur'],
        ['uslugi', 'dlya', 'mesyac', 'nedel', 'для'],
      ],
    },
    {
      id: 'en-metric-booking-revenue',
      action: 'summarize_bookings',
      phrase: 'calculate total earnings for today',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { bookingMetric: 'revenue' },
      conceptGroups: [
        ['calculate', 'compute', 'how', 'much', 'total', 'show', 'tell'],
        ['earnings', 'revenue', 'income', 'sales', 'money', 'earn', 'made'],
        ['today', 'week', 'month', 'yesterday', 'period'],
      ],
    },
    {
      id: 'hy-metric-booking-revenue',
      action: 'summarize_bookings',
      phrase: 'orva yndhanur yekamut',
      locale: 'hy',
      surfaces: ['dashboard'],
      paramHints: { bookingMetric: 'revenue' },
      conceptGroups: [
        ['ընդհանուր', 'ekamut', 'եկամուտ', 'hashvark', 'qan'],
        ['orva', 'aysor', 'օրվա', 'shabat', 'amis'],
      ],
    },
    {
      id: 'ru-metric-booking-revenue',
      action: 'summarize_bookings',
      phrase: 'skolko my zarabotili za segodnya',
      locale: 'ru',
      surfaces: ['dashboard'],
      paramHints: { bookingMetric: 'revenue' },
      conceptGroups: [
        ['сколько', 'итого', 'общ', 'выручк', 'доход', 'заработ'],
        ['сегодня', 'месяц', 'недел', 'заработали', 'за'],
      ],
    },
    {
      id: 'en-metric-booking-count',
      action: 'summarize_bookings',
      phrase: 'how many appointments do we have today',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { bookingMetric: 'count' },
      conceptGroups: [
        ['how', 'many', 'count', 'number', 'total'],
        ['appointments', 'bookings'],
        ['today', 'week', 'month', 'any', 'empty', 'quiet'],
      ],
    },
    {
      id: 'en-metric-booking-upcoming',
      action: 'summarize_bookings',
      phrase: 'upcoming bookings for today',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { bookingMetric: 'upcoming' },
      conceptGroups: [
        ['upcoming', 'coming', 'later', 'rest'],
        ['bookings', 'appointments', 'today', 'day'],
      ],
    },
    {
      id: 'en-metric-booking-busiest',
      action: 'summarize_bookings',
      phrase: 'who is the busiest provider this week',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { bookingMetric: 'busiest_provider' },
      conceptGroups: [
        ['busiest', 'most', 'packed', 'bookings', 'appointments', 'fully'],
        ['provider', 'staff', 'specialist', 'stylist'],
        ['week', 'today', 'month'],
      ],
    },
    {
      id: 'en-metric-booking-no-shows',
      action: 'summarize_bookings',
      phrase: 'how many no shows this month',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { bookingMetric: 'no_shows' },
      conceptGroups: [
        ['no-show', 'noshow', 'noshows'],
        ['how', 'many', 'count', 'summarize'],
        ['month', 'week', 'today'],
      ],
    },
    {
      id: 'en-metric-booking-cancelled',
      action: 'summarize_bookings',
      phrase: 'summarize cancelled appointments today',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { bookingMetric: 'cancelled' },
      conceptGroups: [
        ['cancel', 'cancelled', 'canceled'],
        ['appointments', 'bookings', 'summarize'],
        ['today', 'week', 'month'],
      ],
    },
    {
      id: 'en-metric-booking-unpaid',
      action: 'summarize_bookings',
      phrase: 'list unpaid appointments this week',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { bookingMetric: 'unpaid' },
      conceptGroups: [
        ['unpaid', 'not', 'paid', 'pending', 'payment'],
        ['appointments', 'bookings', 'list'],
        ['week', 'today', 'month'],
      ],
    },
    {
      id: 'en-metric-booking-overview',
      action: 'summarize_bookings',
      phrase: 'booking overview for today',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { bookingMetric: 'overview' },
      conceptGroups: [
        ['overview', 'summary', 'breakdown', 'stats'],
        ['bookings', 'appointments'],
        ['today', 'week'],
      ],
    },
    {
      id: 'en-metric-staff-revenue',
      action: 'summarize_staff',
      phrase: 'top specialists by revenue last month',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { staffMetric: 'most_revenue' },
      conceptGroups: [
        ['top', 'which', 'who', 'highest', 'most'],
        ['specialist', 'provider', 'stylist', 'therapist', 'staff'],
        ['revenue', 'earnings', 'earned', 'sales', 'income', 'brought'],
        ['month', 'week', 'today', 'time'],
      ],
    },
    {
      id: 'en-metric-staff-busiest',
      action: 'summarize_staff',
      phrase: 'which stylist is busiest today',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { staffMetric: 'busiest' },
      conceptGroups: [
        ['busiest', 'most', 'packed', 'appointments'],
        ['stylist', 'provider', 'specialist', 'staff'],
        ['today', 'week'],
      ],
    },
    {
      id: 'en-metric-staff-bookings',
      action: 'summarize_staff',
      phrase: 'who has the most bookings this week',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { staffMetric: 'most_bookings' },
      conceptGroups: [
        ['most', 'bookings', 'appointments'],
        ['who', 'which', 'provider', 'staff', 'specialist'],
        ['week', 'today', 'month'],
      ],
    },
    {
      id: 'en-metric-service-most-booked',
      action: 'summarize_services',
      phrase: 'most popular service this month',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { serviceMetric: 'most_booked' },
      conceptGroups: [
        ['most', 'popular', 'booked', 'top', 'best', 'busiest'],
        ['service', 'services'],
        ['month', 'week', 'performing'],
      ],
    },
    {
      id: 'en-metric-service-revenue',
      action: 'summarize_services',
      phrase: 'which service earned the most revenue',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { serviceMetric: 'top_revenue' },
      conceptGroups: [
        ['revenue', 'earned', 'sales', 'money'],
        ['service', 'services', 'which'],
        ['most', 'top', 'week', 'month'],
      ],
    },
    {
      id: 'en-metric-service-least',
      action: 'summarize_services',
      phrase: 'least booked service',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { serviceMetric: 'least_booked' },
      conceptGroups: [
        ['least', 'worst', 'popular', 'booked', 'performing'],
        ['service', 'services'],
      ],
    },
    {
      id: 'en-metric-customer-no-shows',
      action: 'summarize_customers',
      phrase: 'customers with the most no shows',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { customerMetric: 'most_no_shows' },
      conceptGroups: [
        ['customers', 'clients'],
        ['no', 'show', 'noshow', 'most'],
        ['find', 'show', 'list'],
      ],
    },
    {
      id: 'en-metric-customer-at-risk',
      action: 'summarize_customers',
      phrase: 're engage inactive customers',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { customerMetric: 'at_risk' },
      conceptGroups: [
        ['re', 'engage', 'win', 'back', 'inactive', 'lapsed', 'churn', 'risk'],
        ['customers', 'clients'],
      ],
    },
    {
      id: 'en-metric-customer-spenders',
      action: 'summarize_customers',
      phrase: 'top spenders this year',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { customerMetric: 'top_spenders' },
      conceptGroups: [
        ['top', 'spenders', 'paid', 'spend', 'spent', 'highest', 'biggest'],
        ['customers', 'clients', 'who', 'payers'],
        ['year', 'month'],
      ],
    },
    {
      id: 'en-metric-customer-new',
      action: 'summarize_customers',
      phrase: 'new customers from last month',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { customerMetric: 'new_customers' },
      conceptGroups: [
        ['new', 'recent', 'first', 'time', 'never'],
        ['customers', 'clients'],
        ['month', 'week'],
      ],
    },
    {
      id: 'en-metric-customer-vip',
      action: 'summarize_customers',
      phrase: 'vip loyal customers',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { customerMetric: 'vip' },
      conceptGroups: [
        ['vip', 'loyal', 'best', 'top'],
        ['customers', 'clients'],
      ],
    },
    {
      id: 'en-metric-appointment-expensive',
      action: 'show_appointments',
      phrase: 'most expensive appointment today',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { appointmentMetric: 'most_expensive' },
      conceptGroups: [
        ['most', 'expensive', 'highest', 'price', 'priciest', 'costs'],
        ['appointment', 'appointments'],
        ['today', 'week'],
      ],
    },
    {
      id: 'en-metric-appointment-longest',
      action: 'show_appointments',
      phrase: 'longest appointment this week',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { appointmentMetric: 'longest' },
      conceptGroups: [
        ['longest', 'most', 'time', 'takes'],
        ['appointment', 'appointments'],
        ['week', 'today'],
      ],
    },
    {
      id: 'en-metric-appointment-earliest',
      action: 'show_appointments',
      phrase: 'earliest appointment tomorrow',
      locale: 'en',
      surfaces: ['dashboard'],
      paramHints: { appointmentMetric: 'earliest' },
      conceptGroups: [
        ['earliest', 'first'],
        ['appointment', 'appointments'],
        ['tomorrow', 'today', 'week'],
      ],
    },
  ],
};
