import { ANDROID_POST_NOTIFICATIONS_MIN_SDK } from './push-reachability.fixtures.js';

export { ANDROID_POST_NOTIFICATIONS_MIN_SDK };

export const ANDROID_POST_BOOKING_PERMISSION_SCENARIOS = [
  {
    id: 'android-13-after-first-booking',
    platform: 'android' as const,
    sdkInt: 33,
    completedBookingCount: 1,
    permission: 'prompt' as const,
    alreadyRequested: false,
    expected: true,
  },
  {
    id: 'unknown-sdk-prompt-first-booking',
    platform: 'android' as const,
    sdkInt: undefined,
    completedBookingCount: 1,
    permission: 'prompt' as const,
    alreadyRequested: false,
    expected: true,
  },
  {
    id: 'android-pre-13-default-on',
    platform: 'android' as const,
    sdkInt: 32,
    completedBookingCount: 1,
    permission: 'prompt' as const,
    alreadyRequested: false,
    expected: false,
  },
  {
    id: 'already-granted',
    platform: 'android' as const,
    sdkInt: 34,
    completedBookingCount: 1,
    permission: 'full' as const,
    alreadyRequested: false,
    expected: false,
  },
  {
    id: 'second-booking',
    platform: 'android' as const,
    sdkInt: 34,
    completedBookingCount: 2,
    permission: 'prompt' as const,
    alreadyRequested: false,
    expected: false,
  },
  {
    id: 'already-requested',
    platform: 'android' as const,
    sdkInt: 34,
    completedBookingCount: 1,
    permission: 'prompt' as const,
    alreadyRequested: true,
    expected: false,
  },
  {
    id: 'denied-after-booking',
    platform: 'android' as const,
    sdkInt: 34,
    completedBookingCount: 1,
    permission: 'denied' as const,
    alreadyRequested: false,
    expected: false,
  },
  {
    id: 'skip-ios',
    platform: 'ios' as const,
    sdkInt: 34,
    completedBookingCount: 1,
    permission: 'prompt' as const,
    alreadyRequested: false,
    expected: false,
  },
] as const;

export const ANDROID_DEFAULT_ON_FIRST_OPEN_SCENARIOS = [
  {
    id: 'android-pre-13-granted-first-open',
    platform: 'android' as const,
    isNative: true,
    isFcmBuild: true,
    alreadyRegistered: false,
    permissionReceive: 'granted' as const,
    sdkInt: 32,
    expectReachability: true,
  },
  {
    id: 'unknown-sdk-granted-first-open',
    platform: 'android' as const,
    isNative: true,
    isFcmBuild: true,
    alreadyRegistered: false,
    permissionReceive: 'granted' as const,
    sdkInt: undefined,
    expectReachability: true,
  },
  {
    id: 'android-13-prompt-skips-default-on',
    platform: 'android' as const,
    isNative: true,
    isFcmBuild: true,
    alreadyRegistered: false,
    permissionReceive: 'prompt' as const,
    sdkInt: 33,
    expectReachability: false,
  },
  {
    id: 'skip-when-already-registered',
    platform: 'android' as const,
    isNative: true,
    isFcmBuild: true,
    alreadyRegistered: true,
    permissionReceive: 'granted' as const,
    sdkInt: 32,
    expectReachability: false,
  },
  {
    id: 'skip-ios',
    platform: 'ios' as const,
    isNative: true,
    isFcmBuild: true,
    alreadyRegistered: false,
    permissionReceive: 'granted' as const,
    sdkInt: undefined,
    expectReachability: false,
  },
] as const;

export const ANDROID_DEFAULT_ON_REACHABLE_SCENARIOS = [
  {
    id: 'pre-13-by-sdk',
    platform: 'android' as const,
    sdkInt: 32,
    permissionReceive: 'granted' as const,
    expected: true,
  },
  {
    id: 'unknown-sdk-granted',
    platform: 'android' as const,
    sdkInt: undefined,
    permissionReceive: 'granted' as const,
    expected: true,
  },
  {
    id: 'android-13-prompt-not-default-on',
    platform: 'android' as const,
    sdkInt: 33,
    permissionReceive: 'prompt' as const,
    expected: false,
  },
  {
    id: 'android-13-by-sdk',
    platform: 'android' as const,
    sdkInt: 34,
    permissionReceive: 'granted' as const,
    expected: false,
  },
] as const;
