import type { ConsumerCopy } from './consumer-copy.types.js';
import type { ConsumerLocale } from './tenant-locale.js';

const DOCUMENT_CATEGORIES = {
  lab_report: 'Lab report',
  referral_letter: 'Referral letter',
  imaging_report: 'Imaging report',
  other: 'Other',
} as const;

export const CONSUMER_COPY_EN: ConsumerCopy = {
  cancelBooking: 'Cancel appointment',
  cancelBookingConfirm: 'Cancel this appointment?',
  cancelBookingFailed: 'Could not cancel appointment',
  rescheduleBooking: 'Reschedule',
  pickNewTime: 'Pick a new time',
  loadingSlots: 'Loading times…',
  noSlotsThisDay: 'No times available this day',
  confirmReschedule: 'Confirm reschedule',
  submitting: 'Saving…',
  rescheduleBookingFailed: 'Could not reschedule',
  rescheduleSummary: 'New time: {date} at {time}',
  rescheduleSuccessDetail: 'Rescheduled from {from} to {to}.',
  rescheduleCountHint: 'Rescheduled {count} of {max} times',
  rescheduleUpdatedTitle: 'Appointment updated',
  reschedulePreviousLabel: 'Previous',
  rescheduleNewLabel: 'New',
  manageBookingTitle: 'Manage appointment',
  manageBookingInvalidLink: 'This manage link is invalid or expired.',
  manageBookingSignInHint: 'Sign in to manage from your account.',
  signIn: 'Sign in',
  signInWithGoogle: 'Sign in with Google',
  cancelPackageVisit: 'Cancel package visit',
  cancelPackageVisitConfirm: 'Cancel all appointments in this package visit?',
  cancelPackageVisitFailed: 'Could not cancel package visit',
  reschedulePackageVisit: 'Reschedule package visit',
  reschedulePackageVisitSummary: 'New block: {date} at {time} ({count} services)',
  reschedulePackageVisitSuccess: 'Package visit rescheduled from {from} to {to}.',
  packageNoBlock: 'No package block available',
  bookingStatusCancelled: 'Cancelled',
  bookingStatusCompleted: 'Completed',
  bookingStatusConfirmed: 'Confirmed',
  packageVisitAppointmentCount: '{count} appointments',
  bookingConfirmed: 'Booking confirmed!',
  bookingConfirmedHint: 'You can manage this appointment from your account.',
  youMightAlsoLike: 'You might also like',
  dismissRecommendations: 'Dismiss recommendations',
  learnMore: 'Learn more',
  viewAppointments: 'View appointments',
  bookAnotherService: 'Book another service',
  checkoutSubtotal: 'Subtotal',
  checkoutTotalDue: 'Due now',
  taxIncluded: 'included',
  myResultsTab: 'Results',
  myResultsTitle: 'My results',
  myResultsEmpty:
    'No released lab results yet. Results appear here after your clinic releases them.',
  myResultsReleasedOn: 'Released',
  myResultsUnnamed: 'Lab result',
  myResultsMeasurement: 'Test',
  myResultsValue: 'Result',
  myResultsReferenceRange: 'Reference range',
  myResultsFlag: 'Flag',
  myResultsLoadFailed: 'Could not load your lab results',
  myResultsSignInPrompt: 'Sign in to view your lab results at {name}.',
  myLabToBookTitle: 'Lab to book',
  myLabToBookTab: 'Lab to book',
  myLabToBookSignInPrompt: 'Sign in to view pending lab collection requests at {name}.',
  homeLabToBookShortcut: 'Lab collection to book',
  homeLabToBookShortcutPending: 'Lab collection to book ({count} pending)',
  myLabToBookEmpty: 'No pending lab collection appointments.',
  myLabToBookCollectionService: 'Book: {service}',
  myLabToBookRequestedOn: 'Requested {date}',
  myLabToBookBookCollection: 'Book collection',
  myLabToBookLoadFailed: 'Could not load lab booking requests',
  myLabToBookUnnamedOrder: 'Lab order',
  myDocumentsTitle: 'My documents',
  myDocumentsEmpty:
    'No documents shared with you yet. Your clinic releases documents here when they are ready.',
  myDocumentsOpenDocument: 'Open PDF',
  myDocumentsUnnamed: 'Document',
  myDocumentsLoadFailed: 'Could not load your documents',
  myDocumentsCategoryLine: '{category} · {date}',
  myDocumentCategories: { ...DOCUMENT_CATEGORIES },
  resultStatusNotReceived: 'Not received',
  resultStatusPending: 'Pending',
  resultStatusWaitingCompletion: 'Waiting completion',
  resultStatusCompleted: 'Completed',
  resultStatusReviewed: 'Reviewed',
  resultStatusAutomaticallyReviewed: 'Automatically reviewed',
  resultStatusReleased: 'Released',
  resultStatusRejected: 'Rejected',
  measurementFlagNormal: 'Normal',
  measurementFlagAbnormal: 'Abnormal',
  measurementFlagHigh: 'High',
  measurementFlagLow: 'Low',
  measurementFlagInconclusive: 'Inconclusive',
  measurementFlagIndeterminate: 'Indeterminate',
  measurementFlagTestNotComplete: 'Test not completed',
  measurementFlagNotApplicable: 'Not applicable',
  measurementFlagSeeDetails: 'See details',
  publicIntakeCheckoutTitle: 'Optional pre-visit questionnaire',
  publicIntakeCheckoutSubtitle:
    'Answer a few questions before checkout to help the lab prepare for your visit.',
  publicIntakeSkip: 'Skip for now',
  publicIntakeStart: 'Start questionnaire',
  publicIntakeContinue: 'Continue',
  publicIntakeAnswerLabel: 'Your answer',
  publicIntakeUntitledQuestion: 'Question',
  publicIntakeLoadFailed: 'Could not load intake form.',
  publicIntakeSubmitFailed: 'Could not save your answer.',
  publicIntakeContinueToBooking: 'Continue to booking',
  patientAlertsRegionLabel: 'Clinic alerts',
  patientAlertsViewAction: 'View',
  patientAlertsDismiss: 'Dismiss',
  patientAlertTitleReleased: 'New lab result',
  patientAlertTitleIntake: 'Pre-visit intake incomplete',
  patientAlertTitleLabBooking: 'Lab collection to book',
  patientAlertBodyReleased: '{testName} is ready to view.',
  patientAlertBodyIntake: '{questionnaireTitle} still needs answers before your visit.',
  patientAlertBodyLabBooking:
    'Book your {collectionServiceName} for ordered labs ({orderDisplayNames}).',
};

export const CONSUMER_COPY_HY: ConsumerCopy = {
  cancelBooking: 'Չեղարկել ամրագրումը',
  cancelBookingConfirm: 'Չեղարկել այս հանդիպումը՞։ Սա չի կարող հետարկվել։',
  cancelBookingFailed: 'Չհաջողվեց չեղարկել հանդիպումը',
  rescheduleBooking: 'Փոխել ժամանակը',
  pickNewTime: 'Ընտրեք նոր ամսաթիվ և ժամ',
  loadingSlots: 'Բեռնվում են հասանելի ժամերը…',
  noSlotsThisDay: 'Այս օրը հասանելի ժամեր չկան',
  confirmReschedule: 'Հաստատել նոր ժամանակը',
  submitting: 'Ուղարկվում է…',
  rescheduleBookingFailed: 'Չհաջողվեց փոխել ժամանակը',
  rescheduleSummary: 'Նոր ժամ՝ {date} ժամը {time}',
  rescheduleSuccessDetail: 'Տեղափոխվել է {from}-ից դեպի {to}',
  rescheduleCountHint: '{count}/{max} վերապլանավորում օգտագործված է',
  rescheduleUpdatedTitle: 'Ամրագրումը թարմացվել է',
  reschedulePreviousLabel: 'Նախորդ',
  rescheduleNewLabel: 'Նոր',
  manageBookingTitle: 'Կառավարեք ձեր հանդիպումը',
  manageBookingInvalidLink: 'Այս հղումը անվավեր է կամ ժամկետանց',
  manageBookingSignInHint:
    'Մուտք գործեք նույն էլ. փոստով, որով կատարել եք ամրագրումը',
  signIn: 'Մուտք գործել',
  signInWithGoogle: 'Մուտք գործել Google-ով',
  cancelPackageVisit: 'Չեղարկել ամբողջ փաթեթային այցը',
  cancelPackageVisitConfirm:
    'Չեղարկել այս փաթեթային այցի բոլոր հանդիպումները՞։ Սա չի կարող հետարկվել։',
  cancelPackageVisitFailed: 'Չհաջողվեց չեղարկել փաթեթային այցը',
  reschedulePackageVisit: 'Վերապլանավորել ամբողջ այցը',
  reschedulePackageVisitSummary:
    'Տեղափոխել բոլոր {count} ծառայությունները դեպի {date}՝ սկսած {time}-ից',
  reschedulePackageVisitSuccess: 'Այցը տեղափոխվեց {from}-ից դեպի {to}',
  packageNoBlock: 'Այս փաթեթի համար հասանելի այց չի գտնվել',
  bookingStatusCancelled: 'Չեղարկված',
  bookingStatusCompleted: 'Ավարտված',
  bookingStatusConfirmed: 'Հաստատված',
  packageVisitAppointmentCount: '{count} հանդիպում այս այցում',
  bookingConfirmed: 'Ամրագրումը կատարված է',
  bookingConfirmedHint: 'Կարող եք կառավարել այս ամրագրումը ձեր հաշվից',
  youMightAlsoLike: 'Դուք կարող եք նաև հավանել',
  dismissRecommendations: 'Թաքցնել առաջարկները',
  learnMore: 'Իմանալ ավելին',
  viewAppointments: 'Դիտել ամրագրումները',
  bookAnotherService: 'Ամրագրել ևս մեկը',
  checkoutSubtotal: 'Ենթագումար',
  checkoutTotalDue: 'Վճարման ենթակա',
  taxIncluded: 'ներառված',
  myResultsTab: 'Արդյունքներ',
  myResultsTitle: 'Իմ արդյունքները',
  myResultsEmpty:
    'Ազատված լաբորատոր արդյունքներ դեռ չկան։ Դրանք կհայտնվեն այստեղ, երբ կլինիկան ազատի արդյունքները։',
  myResultsReleasedOn: 'Ազատված',
  myResultsUnnamed: 'Լաբորատոր արդյունք',
  myResultsMeasurement: 'Թեստ',
  myResultsValue: 'Արդյունք',
  myResultsReferenceRange: 'Նորմայի միջակայք',
  myResultsFlag: 'Դրոշ',
  myResultsLoadFailed: 'Չհաջողվեց բեռնել լաբորատոր արդյունքները',
  myResultsSignInPrompt: 'Մուտք գործեք՝ {name}-ում լաբորատոր արդյունքները դիտելու համար',
  myLabToBookTitle: 'Ամրագրելիք լաբորատոր հավաքումներ',
  myLabToBookTab: 'Լաբ. հավաքում',
  myLabToBookSignInPrompt: 'Մուտք գործեք՝ {name}-ում սպասող լաբորատոր հավաքման հարցումները տեսնելու համար։',
  homeLabToBookShortcut: 'Ամրագրել լաբորատոր հավաքում',
  homeLabToBookShortcutPending: 'Ամրագրել լաբորատոր հավաքում ({count} սպասող)',
  myLabToBookEmpty: 'Սպասող լաբորատոր հավաքման ամրագրումներ չկան։',
  myLabToBookCollectionService: 'Ամրագրել՝ {service}',
  myLabToBookRequestedOn: 'Հարցում՝ {date}',
  myLabToBookBookCollection: 'Ամրագրել հավաքում',
  myLabToBookLoadFailed: 'Չհաջողվեց բեռնել լաբորատոր ամրագրումների հարցումները',
  myLabToBookUnnamedOrder: 'Լաբորատոր պատվեր',
  myDocumentsTitle: 'Իմ փաստաթղթերը',
  myDocumentsEmpty:
    'Դեռ փաստաթղթեր չեն հրապարակվել։ Դրանք կհայտնվեն այստեղ, երբ կլինիկան ազատի դրանք։',
  myDocumentsOpenDocument: 'Բացել PDF',
  myDocumentsUnnamed: 'Փաստաթուղթ',
  myDocumentsLoadFailed: 'Չհաջողվեց բեռնել փաստաթղթերը',
  myDocumentsCategoryLine: '{category} · {date}',
  myDocumentCategories: {
    lab_report: 'Լաբորատոր հաշվետվություն',
    referral_letter: 'Ուղղորդում',
    imaging_report: 'Ուղղորդված պատկեր',
    other: 'Այլ',
  },
  resultStatusNotReceived: 'Չի ստացվել',
  resultStatusPending: 'Սպասման մեջ',
  resultStatusWaitingCompletion: 'Սպասում է ավարտին',
  resultStatusCompleted: 'Ավարտված',
  resultStatusReviewed: 'Վերանայված',
  resultStatusAutomaticallyReviewed: 'Ավտոմատ վերանայված',
  resultStatusReleased: 'Հրապարակված',
  resultStatusRejected: 'Մերժված',
  measurementFlagNormal: 'Նորմալ',
  measurementFlagAbnormal: 'Աննորմալ',
  measurementFlagHigh: 'Բարձր',
  measurementFlagLow: 'Ցածր',
  measurementFlagInconclusive: 'Անորոշելի',
  measurementFlagIndeterminate: 'Անորոշ',
  measurementFlagTestNotComplete: 'Թեստը ավարտված չէ',
  measurementFlagNotApplicable: 'Կիրառելի չէ',
  measurementFlagSeeDetails: 'Տես մանրամասները',
  publicIntakeCheckoutTitle: 'Նախապոստ այցի ընտրովի հարցաթերթիկ',
  publicIntakeCheckoutSubtitle:
    'Պատասխանեք մի քանի հարցի՝ գրանցումից առաջ, որպեսզի լաբորատորիան պատրաստվի ձեր այցին։',
  publicIntakeSkip: 'Բաց թողնել',
  publicIntakeStart: 'Սկսել հարցաթերթիկը',
  publicIntakeContinue: 'Շարունակել',
  publicIntakeAnswerLabel: 'Ձեր պատասխանը',
  publicIntakeUntitledQuestion: 'Անվերնագիր հարց',
  publicIntakeLoadFailed: 'Չհաջողվեց բեռնել հարցաթերթիկը։',
  publicIntakeSubmitFailed: 'Չհաջողվեց պահպանել պատասխանը։',
  publicIntakeContinueToBooking: 'Շարունակել գրանցումը',
  patientAlertsRegionLabel: 'Կլինիկայի ծանուցումներ',
  patientAlertsViewAction: 'Դիտել',
  patientAlertsDismiss: 'Փակել',
  patientAlertTitleReleased: 'Նոր լաբորատոր արդյունք',
  patientAlertTitleIntake: 'Նախայցային հարցաթերթիկը incomplete է',
  patientAlertTitleLabBooking: 'Լաբորատոր հավաքում ամրագրել',
  patientAlertBodyReleased: '{testName}-ը պատրաստ է դիտման համար։',
  patientAlertBodyIntake: '{questionnaireTitle}-ը դեռ պահանջում է պատասխաններ այցից առաջ։',
  patientAlertBodyLabBooking:
    'Ամրագրեք {collectionServiceName} պատվիրած թեստերի համար ({orderDisplayNames})։',
};

export const CONSUMER_COPY_RU: ConsumerCopy = {
  cancelBooking: 'Отменить запись',
  cancelBookingConfirm: 'Отменить эту запись? Это нельзя отменить.',
  cancelBookingFailed: 'Не удалось отменить запись',
  rescheduleBooking: 'Перенести',
  pickNewTime: 'Выберите новую дату и время',
  loadingSlots: 'Загрузка доступного времени…',
  noSlotsThisDay: 'На этот день нет свободного времени',
  confirmReschedule: 'Подтвердить новое время',
  submitting: 'Отправка…',
  rescheduleBookingFailed: 'Не удалось перенести запись',
  rescheduleSummary: 'Новое время: {date} в {time}',
  rescheduleSuccessDetail: 'Перенесено с {from} на {to}.',
  rescheduleCountHint: 'Использовано переносов: {count} из {max}',
  rescheduleUpdatedTitle: 'Запись обновлена',
  reschedulePreviousLabel: 'Было',
  rescheduleNewLabel: 'Стало',
  manageBookingTitle: 'Управление записью',
  manageBookingInvalidLink: 'Ссылка недействительна или истекла.',
  manageBookingSignInHint:
    'Войдите с тем же email, который использовали при оформлении, чтобы отменить или перенести запись.',
  signIn: 'Войти',
  signInWithGoogle: 'Войти через Google',
  cancelPackageVisit: 'Отменить весь пакетный визит',
  cancelPackageVisitConfirm:
    'Отменить все записи в этом пакетном визите? Это нельзя отменить.',
  cancelPackageVisitFailed: 'Не удалось отменить пакетный визит',
  reschedulePackageVisit: 'Перенести весь визит',
  reschedulePackageVisitSummary:
    'Перенести все {count} услуг на {date}, начало в {time}',
  reschedulePackageVisitSuccess: 'Визит перенесён с {from} на {to}.',
  packageNoBlock: 'Нет доступного визита в один день для этого пакета',
  bookingStatusCancelled: 'Отменена',
  bookingStatusCompleted: 'Завершена',
  bookingStatusConfirmed: 'Подтверждена',
  packageVisitAppointmentCount: '{count} записей в этом визите',
  bookingConfirmed: 'Запись подтверждена',
  bookingConfirmedHint: 'Вы можете управлять этой записью в своём аккаунте.',
  youMightAlsoLike: 'Вам также может понравиться',
  dismissRecommendations: 'Скрыть рекомендации',
  learnMore: 'Подробнее',
  viewAppointments: 'Мои записи',
  bookAnotherService: 'Записаться ещё раз',
  checkoutSubtotal: 'Промежуточный итог',
  checkoutTotalDue: 'К оплате',
  taxIncluded: 'включено',
  myResultsTab: 'Результаты',
  myResultsTitle: 'Мои результаты',
  myResultsEmpty:
    'Пока нет выпущенных результатов анализов. Они появятся здесь после того, как клиника их опубликует.',
  myResultsReleasedOn: 'Выпущен',
  myResultsUnnamed: 'Результат анализа',
  myResultsMeasurement: 'Тест',
  myResultsValue: 'Результат',
  myResultsReferenceRange: 'Референсный диапазон',
  myResultsFlag: 'Флаг',
  myResultsLoadFailed: 'Не удалось загрузить результаты анализов',
  myResultsSignInPrompt: 'Войдите, чтобы просмотреть результаты анализов в {name}.',
  myLabToBookTitle: 'Записи на забор',
  myLabToBookTab: 'Запись на забор',
  myLabToBookSignInPrompt: 'Войдите, чтобы увидеть ожидающие записи на забор в {name}.',
  homeLabToBookShortcut: 'Записаться на забор',
  homeLabToBookShortcutPending: 'Записаться на забор ({count} ожидают)',
  myLabToBookEmpty: 'Нет ожидающих записей на забор.',
  myLabToBookCollectionService: 'Записаться: {service}',
  myLabToBookRequestedOn: 'Запрошено {date}',
  myLabToBookBookCollection: 'Записаться на забор',
  myLabToBookLoadFailed: 'Не удалось загрузить запросы на запись',
  myLabToBookUnnamedOrder: 'Лабораторный заказ',
  myDocumentsTitle: 'Мои документы',
  myDocumentsEmpty:
    'Пока нет документов, доступных вам. Клиника публикует их здесь, когда они готовы.',
  myDocumentsOpenDocument: 'Открыть PDF',
  myDocumentsUnnamed: 'Документ',
  myDocumentsLoadFailed: 'Не удалось загрузить документы',
  myDocumentsCategoryLine: '{category} · {date}',
  myDocumentCategories: {
    lab_report: 'Лабораторный отчёт',
    referral_letter: 'Направление',
    imaging_report: 'Отчёт по визуализации',
    other: 'Другое',
  },
  resultStatusNotReceived: 'Не получен',
  resultStatusPending: 'В ожидании',
  resultStatusWaitingCompletion: 'Ожидание завершения',
  resultStatusCompleted: 'Завершён',
  resultStatusReviewed: 'Проверен',
  resultStatusAutomaticallyReviewed: 'Проверен автоматически',
  resultStatusReleased: 'Опубликован',
  resultStatusRejected: 'Отклонён',
  measurementFlagNormal: 'Норма',
  measurementFlagAbnormal: 'Отклонение',
  measurementFlagHigh: 'Выше нормы',
  measurementFlagLow: 'Ниже нормы',
  measurementFlagInconclusive: 'Неоднозначно',
  measurementFlagIndeterminate: 'Неопределённо',
  measurementFlagTestNotComplete: 'Тест не завершён',
  measurementFlagNotApplicable: 'Не применимо',
  measurementFlagSeeDetails: 'Подробнее',
  publicIntakeCheckoutTitle: 'Необязательная анкета перед визитом',
  publicIntakeCheckoutSubtitle:
    'Ответьте на несколько вопросов до оформления записи, чтобы лаборатория могла подготовиться.',
  publicIntakeSkip: 'Пропустить',
  publicIntakeStart: 'Начать анкету',
  publicIntakeContinue: 'Продолжить',
  publicIntakeAnswerLabel: 'Ваш ответ',
  publicIntakeUntitledQuestion: 'Вопрос без названия',
  publicIntakeLoadFailed: 'Не удалось загрузить анкету.',
  publicIntakeSubmitFailed: 'Не удалось сохранить ответ.',
  publicIntakeContinueToBooking: 'Перейти к оформлению',
  patientAlertsRegionLabel: 'Уведомления клиники',
  patientAlertsViewAction: 'Открыть',
  patientAlertsDismiss: 'Скрыть',
  patientAlertTitleReleased: 'Новый результат анализа',
  patientAlertTitleIntake: 'Анкета перед визитом не завершена',
  patientAlertTitleLabBooking: 'Нужно записаться на забор',
  patientAlertBodyReleased: '{testName} готов к просмотру.',
  patientAlertBodyIntake: '{questionnaireTitle} ещё требует ответов перед визитом.',
  patientAlertBodyLabBooking:
    'Запишитесь на {collectionServiceName} для назначенных анализов ({orderDisplayNames}).',
};

const CATALOG: Record<ConsumerLocale, ConsumerCopy> = {
  en: CONSUMER_COPY_EN,
  hy: CONSUMER_COPY_HY,
  ru: CONSUMER_COPY_RU,
};

export function getConsumerCopy(locale: ConsumerLocale): ConsumerCopy {
  return CATALOG[locale];
}

export const CONSUMER_COPY_LOCALES: ConsumerLocale[] = ['en', 'hy', 'ru'];
