import type { ConsumerCopy } from './consumer-copy.types.js';
import type { ConsumerLocale } from './tenant-locale.js';

const DOCUMENT_CATEGORIES = {
  lab_report: 'Lab report',
  referral_letter: 'Referral letter',
  imaging_report: 'Imaging report',
  other: 'Other',
} as const;

/** discover-1.4 / discover-exit-4 — chip catalog synced with backend `ai-consumer-discovery-chips.fixtures.ts`. */
export type ConsumerDiscoveryChipCopyCatalogRow = {
  id:
    | 'discover-chip-under-50-en'
    | 'discover-chip-premium-en'
    | 'discover-chip-evening-weekend-en';
  fixtureId: string;
  domain: 'budget' | 'rank' | 'availability';
  labelKey:
    | 'assistantDiscoverChipUnder50'
    | 'assistantDiscoverChipPremium'
    | 'assistantDiscoverChipEveningWeekend';
  promptKey:
    | 'assistantDiscoverPromptUnder50'
    | 'assistantDiscoverPromptPremium'
    | 'assistantDiscoverPromptEveningWeekend';
  en: { label: string; prompt: string };
  hy: { label: string };
  ru: { label: string };
};

export const CONSUMER_DISCOVERY_CHIP_COPY_CATALOG: readonly ConsumerDiscoveryChipCopyCatalogRow[] =
  [
    {
      id: 'discover-chip-under-50-en',
      fixtureId: 'budget-voice-chip-en',
      domain: 'budget',
      labelKey: 'assistantDiscoverChipUnder50',
      promptKey: 'assistantDiscoverPromptUnder50',
      en: { label: 'Under $50', prompt: 'Services under $50' },
      hy: { label: '$50-ից ցած' },
      ru: { label: 'До $50' },
    },
    {
      id: 'discover-chip-premium-en',
      fixtureId: 'rank-voice-chip-en',
      domain: 'rank',
      labelKey: 'assistantDiscoverChipPremium',
      promptKey: 'assistantDiscoverPromptPremium',
      en: { label: 'Premium services', prompt: 'Premium services' },
      hy: { label: 'Պրեմիում ծառայություններ' },
      ru: { label: 'Премиум услуги' },
    },
    {
      id: 'discover-chip-evening-weekend-en',
      fixtureId: 'avail-voice-chip-en',
      domain: 'availability',
      labelKey: 'assistantDiscoverChipEveningWeekend',
      promptKey: 'assistantDiscoverPromptEveningWeekend',
      en: {
        label: 'Evening or weekend slots',
        prompt: 'Evening or weekend slots for {service}',
      },
      hy: { label: 'Երեկոյան կամ հանգստյան օր' },
      ru: { label: 'Вечер или выходные' },
    },
  ];

type DiscoverChipCopyFields = Pick<
  ConsumerCopy,
  ConsumerDiscoveryChipCopyCatalogRow['labelKey'] |
    ConsumerDiscoveryChipCopyCatalogRow['promptKey']
>;

function buildDiscoverChipCopyFields(locale: ConsumerLocale): DiscoverChipCopyFields {
  const fields = {} as DiscoverChipCopyFields;
  for (const row of CONSUMER_DISCOVERY_CHIP_COPY_CATALOG) {
    fields[row.labelKey] =
      locale === 'en'
        ? row.en.label
        : locale === 'hy'
          ? row.hy.label
          : row.ru.label;
    fields[row.promptKey] = row.en.prompt;
  }
  return fields;
}

export const CONSUMER_DISCOVERY_CHIP_IDS = CONSUMER_DISCOVERY_CHIP_COPY_CATALOG.map(
  (row) => row.id,
);

export const CONSUMER_COPY_EN: ConsumerCopy = {
  cancelBooking: 'Cancel appointment',
  cancelBookingConfirm: 'Cancel this appointment?',
  cancelBookingFailed: 'Could not cancel appointment',
  rescheduleBooking: 'Reschedule',
  pickNewTime: 'Pick a new time',
  loadingSlots: 'Loading times…',
  noSlotsThisDay: 'No times available this day',
  timeSlotMorning: 'Morning',
  timeSlotAfternoon: 'Afternoon',
  timeSlotEvening: 'Evening',
  confirmReschedule: 'Confirm reschedule',
  submitting: 'Saving…',
  rescheduleBookingFailed: 'Could not reschedule',
  rescheduleSummary: 'New time: {date} at {time}',
  rescheduleSuccessDetail: 'Rescheduled from {from} to {to}.',
  rescheduleCountHint: 'Rescheduled {count} of {max} times',
  rescheduleUpdatedTitle: 'Appointment updated',
  reschedulePreviousLabel: 'Previous',
  rescheduleNewLabel: 'New',
  manageBookingTitle: 'Manage appointment',
  manageBookingInvalidLink: 'This manage link is invalid or expired.',
  manageBookingSignInHint: 'Sign in to manage from your account.',
  signIn: 'Sign in',
  signInWithGoogle: 'Sign in with Google',
  cancelPackageVisit: 'Cancel package visit',
  cancelPackageVisitConfirm: 'Cancel all appointments in this package visit?',
  cancelPackageVisitFailed: 'Could not cancel package visit',
  reschedulePackageVisit: 'Reschedule package visit',
  reschedulePackageVisitSummary: 'New block: {date} at {time} ({count} services)',
  reschedulePackageVisitSuccess: 'Package visit rescheduled from {from} to {to}.',
  packageNoBlock: 'No available same-day visit found for this package',
  bookingStatusCancelled: 'Cancelled',
  bookingStatusCompleted: 'Completed',
  bookingStatusConfirmed: 'Confirmed',
  packageVisitAppointmentCount: '{count} appointments',
  bookingConfirmed: 'Booking confirmed!',
  bookingConfirmedHint: 'You can manage this appointment from your account.',
  youMightAlsoLike: 'You might also like',
  dismissRecommendations: 'Dismiss recommendations',
  learnMore: 'Learn more',
  viewAppointments: 'View appointments',
  bookAnotherService: 'Book another service',
  checkoutSubtotal: 'Subtotal',
  checkoutTotalDue: 'Due now',
  checkoutPromoCode: 'Promo or gift card',
  checkoutPromoPlaceholder: 'Enter code',
  checkoutApplyPromo: 'Apply',
  checkoutPromoApplied: 'Applied: {code}',
  checkoutRemovePromo: 'Remove',
  checkoutLoyaltyPoints: 'Loyalty points',
  checkoutLoyaltyBalance: 'Balance: {points} pts ({value})',
  checkoutLoyaltyMaxHint: 'Max {max} pts',
  checkoutUseMaxPoints: 'Use max',
  checkoutPromoDiscount: 'Promo discount',
  checkoutGiftCardDiscount: 'Gift card',
  checkoutLoyaltyDiscount: 'Loyalty points',
  checkoutFreeAfterDiscounts: 'Total',
  checkoutHowToBook: 'How would you like to book?',
  checkoutUseSubscription: 'Use subscription',
  checkoutAppointmentsLeft: 'appointments left',
  checkoutExpiresOn: 'expires',
  checkoutFreeThisVisit: '$0 for this visit',
  checkoutOneTimeAppointment: 'One-time appointment',
  checkoutSubscribeAndSave: 'Subscribe & save',
  checkoutChooseSubscriptionPlan: 'Choose a subscription plan',
  checkoutSaveAmount: 'save {amount}',
  checkoutSubscriptionPlanRequired: 'Please select a subscription plan',
  checkoutUsingSubscriptionHint: '{remaining} visits left after this booking',
  checkoutPlanIncludesHint: 'Plan includes {visits} visits',
  checkoutSelectedTime: 'Selected time',
  checkoutBookingService: 'Service',
  checkoutEdit: 'Edit',
  taxIncluded: 'included',
  myResultsTab: 'Results',
  myResultsTitle: 'My results',
  myResultsEmpty:
    'No released lab results yet. Results appear here after your clinic releases them.',
  myResultsReleasedOn: 'Released',
  myResultsUnnamed: 'Lab result',
  myResultsMeasurement: 'Test',
  myResultsValue: 'Result',
  myResultsReferenceRange: 'Reference range',
  myResultsFlag: 'Flag',
  myResultsLoadFailed: 'Could not load your lab results',
  myResultsSignInPrompt: 'Sign in to view your lab results at {name}.',
  myLabToBookTitle: 'Lab to book',
  myLabToBookTab: 'Lab to book',
  myLabToBookSignInPrompt: 'Sign in to view pending lab collection requests at {name}.',
  homeLabToBookShortcut: 'Lab collection to book',
  homeLabToBookShortcutPending: 'Lab collection to book ({count} pending)',
  myLabToBookEmpty: 'No pending lab collection appointments.',
  myLabToBookCollectionService: 'Book: {service}',
  myLabToBookRequestedOn: 'Requested {date}',
  myLabToBookBookCollection: 'Book collection',
  myLabToBookLoadFailed: 'Could not load lab booking requests',
  myLabToBookUnnamedOrder: 'Lab order',
  myDocumentsTitle: 'My documents',
  myDocumentsEmpty:
    'No documents shared with you yet. Your clinic releases documents here when they are ready.',
  myDocumentsOpenDocument: 'Open PDF',
  myDocumentsUnnamed: 'Document',
  myDocumentsLoadFailed: 'Could not load your documents',
  myDocumentsCategoryLine: '{category} · {date}',
  myDocumentCategories: { ...DOCUMENT_CATEGORIES },
  resultStatusNotReceived: 'Not received',
  resultStatusPending: 'Pending',
  resultStatusWaitingCompletion: 'Waiting completion',
  resultStatusCompleted: 'Completed',
  resultStatusReviewed: 'Reviewed',
  resultStatusAutomaticallyReviewed: 'Automatically reviewed',
  resultStatusReleased: 'Released',
  resultStatusRejected: 'Rejected',
  measurementFlagNormal: 'Normal',
  measurementFlagAbnormal: 'Abnormal',
  measurementFlagHigh: 'High',
  measurementFlagLow: 'Low',
  measurementFlagInconclusive: 'Inconclusive',
  measurementFlagIndeterminate: 'Indeterminate',
  measurementFlagTestNotComplete: 'Test not completed',
  measurementFlagNotApplicable: 'Not applicable',
  measurementFlagSeeDetails: 'See details',
  publicIntakeCheckoutTitle: 'Optional pre-visit questionnaire',
  publicIntakeCheckoutSubtitle:
    'Answer a few questions before checkout to help the lab prepare for your visit.',
  publicIntakeSkip: 'Skip for now',
  publicIntakeStart: 'Start questionnaire',
  publicIntakeContinue: 'Continue',
  publicIntakeAnswerLabel: 'Your answer',
  publicIntakeUntitledQuestion: 'Question',
  publicIntakeLoadFailed: 'Could not load intake form.',
  publicIntakeSubmitFailed: 'Could not save your answer.',
  publicIntakeContinueToBooking: 'Continue to booking',
  patientAlertsRegionLabel: 'Clinic alerts',
  patientAlertsViewAction: 'View',
  patientAlertsDismiss: 'Dismiss',
  patientAlertTitleReleased: 'New lab result',
  patientAlertTitleIntake: 'Pre-visit intake incomplete',
  patientAlertTitleLabBooking: 'Lab collection to book',
  patientAlertBodyReleased: '{testName} is ready to view.',
  patientAlertBodyIntake: '{questionnaireTitle} still needs answers before your visit.',
  patientAlertBodyLabBooking:
    'Book your {collectionServiceName} for ordered labs ({orderDisplayNames}).',
  assistantTitle: 'Booking assistant',
  assistantHint: 'Ask about services, availability, or your appointments.',
  assistantHelpChip: 'Help',
  assistantHelpChipHint: 'Show booking help suggestions',
  assistantGuideExamples: 'Try asking for help:',
  assistantGuideStepOf: 'Step {current} of {total}',
  assistantGuideNextStep: 'Next step',
  assistantGuideOpenInApp: 'Open in app',
  assistantGuideStillStuck: 'Still stuck?',
  assistantPlaceholder: 'Ask anything…',
  assistantThinking: 'Thinking…',
  assistantContinueBooking: 'Continue booking',
  assistantClose: 'Close',
  assistantErrorGeneric: 'Something went wrong. Please try again.',
  assistantExampleAvailable: 'Who is available tomorrow afternoon for {service}?',
  assistantExampleServices: 'What services do you offer?',
  assistantExampleBook: 'Book {service} this Friday',
  assistantExampleLocation: 'Where are you located?',
  assistantFallbackProvider: 'a specialist',
  assistantFallbackService: 'a service',
  assistantFallbackServiceCategory: 'our services',
  assistantExampleGuideBook: 'How do I book an appointment step by step?',
  assistantExampleGuideCheckout: 'Walk me through checkout and payment',
  assistantExampleGuideServices: 'How do I pick a service and provider?',
  assistantExampleGuideLocation: 'Where do I find your address and hours?',
  assistantDiscoverChipsTitle: 'Service discovery',
  ...buildDiscoverChipCopyFields('en'),
  availableProvidersTitle: 'Available providers',
  bookProvider: 'Book',
  voiceStart: 'Voice input',
  voiceStop: 'Stop listening',
  voiceUnsupported: 'Voice input is not supported on this device.',
  voiceDenied: 'Microphone access was denied.',
  voiceNoSpeech: 'No speech detected. Try again.',
  voiceError: 'Voice input failed. Try again.',
  speakReply: 'Listen',
  multiServiceBookedTitle: 'Appointments booked',
  multiServiceBookedHint: 'Your multi-service visit is confirmed.',
  multiServiceWithProvider: 'with {name}',
  multiServiceConfirmAction: 'Confirm booking',
  multiServicePaymentReturnHint:
    'Complete payment in your browser, then return here to confirm your booking.',
  multiServiceCompletePayment: 'Complete payment…',
  multiServiceConfirmPaymentReturn: 'I completed payment',
  multiServiceEntryCta: 'Book multiple services',
  multiServiceSelectHint: 'Select one service, or pick two or more to book together in one visit.',
  multiServiceCart: '{count} services selected',
  multiServiceTotal: '{duration} min · {price}',
  multiServiceContinue: 'Continue with selected services',
  multiServiceAvailabilityTitle: 'Select date & time',
  multiServicePickBlockHint: 'Choose a time block that fits all selected services.',
  multiServiceEditServices: 'Edit services',
  multiServiceEditProvider: 'Change specialist',
  multiServiceConfirmTitle: 'Schedule your services',
  multiServiceScheduleEach: 'Pick a date and time for each service.',
  multiServiceFindingSlots: 'Finding available times…',
  multiServiceCheckoutTitle: 'Confirm your visit',
  uncategorizedServices: 'Other services',
  servicesSection: 'Services',
  selectSpecialist: 'Specialist',
  noTimesAvailable: 'No times available this day.',
  loadAvailableTimesFailed: 'Could not load available times.',
  findAvailableBlockFailed: 'Could not find an available block.',
  validateServiceSelectionFailed: 'Could not validate your service selection.',
  removeService: 'Remove',
  bookAnother: 'Book another',
  totalDue: 'Total due',
  feedbackUp: 'Helpful',
  feedbackDown: 'Not helpful',
  feedbackThanks: 'Thanks — this helps improve the assistant.',
  feedbackReasonSkip: 'Skip',
  feedbackReasonWrongAction: 'Wrong action',
  feedbackReasonWrongDate: 'Wrong date',
  feedbackReasonWrongPerson: 'Wrong person',
  feedbackReasonWrongService: 'Wrong service',
  feedbackReasonDidNotUnderstand: "Didn't understand",
  postBookingSatisfactionTitle: 'How was your booking?',
  postBookingSatisfactionMessage:
    'Your appointment is confirmed. A quick rating helps us improve — only if you have a moment.',
  postBookingSatisfactionGreat: 'Great!',
  postBookingSatisfactionUnhappy: 'Could be better',
  postBookingSatisfactionDismiss: 'Not now',
  postBookingReviewRateTitle: 'Rate your visit',
  postBookingReviewSubmitAction: 'Submit review',
  postBookingReviewSubmitFailed: 'Could not submit your review. Try again later.',
  postBookingSupportTitle: 'Support',
  postBookingSupportSubmitted:
    'Thanks — the salon team has been notified and will follow up by email.',
  postBookingSupportFailed:
    'We could not open a ticket automatically. Tap OK to contact support on the web.',
  postBookingSupportUnavailable:
    'Support is not configured for this salon yet. You can reach them from your confirmation email.',
  rewardsSectionTitle: 'Rewards & offers',
  rewardsLoyaltyBalanceTitle: 'Your rewards balance',
  rewardsLoyaltyBalance: '{amount} available',
  rewardsLoyaltyEarnRate: 'Earn {percent}% back on eligible visits',
  rewardsPromosHint: 'Use these codes when you book:',
  rewardsPromoMinimum: 'Minimum spend {amount}',
  rewardsPromoExpires: 'Expires {date}',
  rewardsBookToRedeem: 'Book to redeem',
  rewardsSignInHint: 'Sign in to see your rewards balance and exclusive offers.',
  widgetNextAppointmentTitle: 'Next appointment',
  widgetNextAppointmentSubtitle: '{date} · {time} with {provider}',
  widgetQuickRebookTitle: 'Book again',
  widgetQuickRebookSubtitle: 'with {provider} · {time}',
  widgetSignedOutTitle: 'Sign in to OptiSchedule Book',
  widgetSignedOutSubtitle: 'See upcoming visits and rebook in one tap',
  notificationPrefsSectionTitle: 'Notification preferences',
  notificationPrefsSectionHint:
    'Choose what push notifications you want. Appointment reminders stay on by default so you do not miss your visit.',
  notificationPrefsRemindersTitle: 'Appointment reminders',
  notificationPrefsRemindersDescription:
    'Confirmations, schedule changes, and reminders before your visit.',
  notificationPrefsOffersTitle: 'Offers & rebook tips',
  notificationPrefsOffersDescription:
    'Promo codes, win-back messages, and nudges to book your usual service again.',
  notificationPrefsNewsTitle: 'Salon news',
  notificationPrefsNewsDescription:
    'Updates, announcements, and occasional engagement messages from the salon.',
  notificationPrefsLoadFailed: 'Could not load notification preferences.',
  notificationPrefsSaveFailed: 'Could not save your preference. Try again.',
  offlineStatusOffline: 'You are offline. Booking changes will sync when you reconnect.',
  offlineStatusSyncing: '{count} change(s) waiting to sync…',
  offlineCachedSalon: 'Showing saved salon info from your last visit.',
  offlineMutationQueued: 'Saved offline — we will sync when you are back online.',
  appGateTitle: 'Update required',
  appGateKillSwitchMessage: 'This app version is temporarily unavailable. Please try again later.',
  appGateUpdateRequiredMessage: 'Please update OptiSchedule Book to continue booking.',
  appGateUpdateNudgeMessage: 'A newer version of OptiSchedule Book is available with improvements.',
  appGateUpdateAction: 'Update in the app store',
  appGateDismissAction: 'Not now',
  analyticsConsentTitle: 'Analytics consent',
  analyticsConsentMessage:
    'Help us improve the app with anonymous usage analytics. No personal data is collected.',
  analyticsConsentAccept: 'Accept',
  analyticsConsentDecline: 'Decline',
  pushPrimingTitle: 'Your slot is confirmed',
  pushPrimingBody:
    'Turn on reminders and we will notify you when bookings are confirmed and before your appointment.',
  pushPrimingAccept: 'Yes, remind me',
  pushPrimingDecline: 'Not now',
  pushProvisionalUpgradeTitle: 'Keep these reminders on?',
  pushProvisionalUpgradeBody:
    'You opened a reminder — turn on full notifications so booking updates appear on your lock screen.',
  pushProvisionalUpgradeAccept: 'Keep reminders on',
  pushProvisionalUpgradeDecline: 'Not now',
  pushSettingsReaskTitle: 'Turn notifications back on',
  pushSettingsReaskBody:
    'We can only remind you about upcoming visits when notifications are enabled in Settings.',
  pushSettingsReaskOpen: 'Open Settings',
  pushSettingsReaskSkip: 'Skip',
  postBookingSignInTitle: 'Save this booking to your account',
  postBookingSignInBody:
    'One tap with Apple or Google — guest bookings merge automatically. You can skip and sign in later.',
  postBookingSignInGoogle: 'Continue with Google',
  postBookingSignInApple: 'Continue with Apple',
  postBookingSignInSkip: 'Maybe later',
  postBookingSignInBusy: 'Signing in…',
  activationPaymentOptionalHint:
    'Pay at your visit — online payment is optional for your first booking.',
  activationPaymentHiccupMessage:
    'Online payment did not complete. You can still confirm and pay at the salon.',
  activationPayAtVenueFallbackAction: 'Confirm and pay at visit instead',
  activationPayAtVenueSelected: 'Pay at visit selected — confirm below to complete your booking.',
  activationConfirmBooking: 'Confirm booking',
  activationPayAtVisitConfirm: 'Confirm — pay at visit',
  bookingDraftResumeConfirm: 'Continue your booking — confirm the time below.',
  bookingDraftResumeSlot: 'Continue your booking — pick a time below.',
  bookingDraftResumeService: 'Continue your unfinished booking below.',
  networkFeedbackCreated: 'Saved',
  networkFeedbackUpdated: 'Updated',
  networkFeedbackDeleted: 'Removed',
  networkFeedbackFailed: 'Something went wrong. Check your connection and try again.',
  networkFeedbackFailedCreate: 'Could not complete request.',
  networkFeedbackFailedUpdate: 'Could not save changes.',
  networkFeedbackFailedDelete: 'Could not remove item.',
  networkRetryAction: 'Try again',
  networkLoadFailed: 'Could not load. Check your connection and try again.',
  growthSectionTitle: 'Book again & share',
  growthRebookTitle: 'Book your last visit again',
  growthRebookSubtitle: '{service} with {provider} · {time}',
  growthRebookAction: 'Rebook now',
  growthShareSalonTitle: 'Share this salon',
  growthShareSalonAction: 'Share link',
  growthShareBookingAction: 'Share booking',
  growthReferTitle: 'Refer a friend',
  growthReferSubtitle: 'Invite friends — you both earn rewards at {businessName}.',
  growthReferAction: 'Send invite',
  growthShareCopied: 'Link copied to clipboard.',
  growthShareUnavailable: 'Sharing is not available on this device.',
  growthShareRewardEarned: 'You earned {reward} for sharing!',
  postBookingTenantReviewAction: 'Rate your visit',
  giftCardNav: 'Gift cards',
  giftCardTitle: 'Buy a gift card',
  giftCardSubtitle: 'Give the gift of self-care — digital or physical delivery.',
  giftCardChooseType: 'What would you like to gift?',
  giftCardTypeMonetary: 'Amount',
  giftCardTypeService: 'Service',
  giftCardTypeBundle: 'Bundle',
  giftCardTypePackage: 'Service package',
  giftCardTypeSubscription: 'Subscription plan',
  giftCardTypeDescMonetary: 'A dollar amount they can spend on any booking.',
  giftCardTypeDescService: 'One or more individual services.',
  giftCardTypeDescBundle: 'A custom mix of services set up by the business.',
  giftCardTypeDescPackage: 'An existing package from this business.',
  giftCardTypeDescSubscription: 'An existing subscription plan.',
  giftCardAmountHint: 'Pick a preset amount or enter your own.',
  giftCardSelectServicesHint: 'Select one or more services to include.',
  giftCardSelectedServices: '{count} services selected',
  giftCardContinueCheckout: 'Continue to checkout',
  giftCardCheckoutTitle: 'Gift card checkout',
  giftCardYourDetails: 'Your details',
  giftCardRecipientSection: 'Recipient',
  giftCardBuyForSelf: 'For myself',
  giftCardBuyAsGift: 'As a gift',
  giftCardPurchaserName: 'Your name',
  giftCardPurchaserEmail: 'Your email (receipt)',
  giftCardRecipientName: 'Recipient name',
  giftCardRecipientEmail: 'Recipient email',
  giftCardRecipientPhone: 'Recipient phone',
  giftCardPersonalMessage: 'Personal message (optional)',
  giftCardDeliverySection: 'Delivery',
  giftCardDeliveryDigital: 'Digital',
  giftCardDeliveryPhysical: 'Physical',
  giftCardAddressLine1: 'Address line 1',
  giftCardAddressLine2: 'Address line 2 (optional)',
  giftCardCity: 'City',
  giftCardPostalCode: 'Postal code',
  giftCardCountry: 'Country',
  giftCardDeliveryInstructions: 'Delivery instructions (optional)',
  giftCardShipping: 'Shipping',
  giftCardTotal: 'Subtotal',
  giftCardTotalDue: 'Due now',
  giftCardPayNow: 'Pay with card',
  giftCardConfirmCashPurchase: 'Confirm purchase',
  giftCardPayCashAtVisit: 'Pay {amount} at your next visit.',
  giftCardSuccessTitle: 'Gift card purchased!',
  giftCardSuccessBody: 'We sent your gift card details by email.',
  giftCardQuoteFailed: 'Could not calculate price.',
  giftCardCheckoutFailed: 'Could not start checkout.',
  giftCardEmailRequired: 'Purchaser email is required.',
  giftCardPurchaserNameRequired: 'Please enter your name.',
  giftCardConsentRequired: 'Please accept the privacy policy.',
  giftCardPaymentFailed: 'Payment confirmation failed.',
  giftCardMyGiftCards: 'My gift cards',
  giftCardMyOrdered: 'Gift cards I purchased',
  giftCardMyRedeemed: 'Gift cards I redeemed',
  giftCardNoOrders: 'No gift card purchases yet.',
  giftCardNoRedeemed: 'No redeemed gift cards yet.',
  giftCardRedeemSectionTitle: 'Redeem a gift you received',
  giftCardClaimTitle: 'Redeem a gift code on your account',
  giftCardClaimHint: 'Paste the code from your email to add it to your account.',
  giftCardClaimPlaceholder: 'Gift code from email',
  giftCardClaimSubmit: 'Redeem code',
  giftCardClaimSuccess: 'Gift claimed successfully.',
  giftCardClaimPackageSuccess: 'Package added to your account.',
  giftCardClaimSubscriptionSuccess: 'Subscription added to your account.',
  giftCardClaimServiceSuccess: 'Service gift saved — use the code at checkout.',
  giftCardClaimBundleSuccess: 'Bundle gift saved — use the code at checkout.',
  giftCardRedeemedHint: 'Redeemed gifts appear here. Use service codes at booking checkout.',
  giftCardBookToUse: 'Book an appointment',
  giftCardCreditsRemaining: 'remaining',
  giftCardClaimedOn: 'Claimed {date}',
  giftCardRedeemedPackageHint: 'Book your package visits from the services page.',
  giftCardRedeemedSubscriptionHint: 'Your subscription is active on this account.',
  giftCardRedeemedServiceHint: 'Apply this code when booking matching services.',
  giftCardBalance: 'balance',
  giftCardActive: 'Active',
  giftCardInactive: 'Inactive',
  giftCardCancelOrder: 'Cancel order',
  giftCardCancelWindow: 'Cancel window',
  giftCardCancelConfirm: 'Request cancellation for this gift card order?',
  giftCardCancelSuccess: 'Cancellation request submitted.',
  giftCardCancelRefunded: 'Order cancelled and refunded.',
  giftCardCancelRefundFailed: 'Cancelled, but refund could not be processed.',
  giftCardRequestStatus: 'Request status',
  giftCardPackageBadge: 'Package',
  giftCardSaveBadge: 'Save {percent}%',
  giftCardSubscribeBadge: 'Subscribe & save',
  giftCardSubscriptionAppointments: 'visits',
  giftCardSubscriptionMonths: 'mo',
  giftCardBundleSelected: 'Bundle selected',
  giftCardBuyGiftCard: 'Buy gift card',
  giftCardStatusCancelled: 'Cancelled',
  giftCardPrivacyConsent: 'I agree to the privacy policy.',
  giftCardPaymentMethod: 'Payment',
  giftCardPayOnline: 'Pay online',
  giftCardPayCashShort: 'Pay at visit',
  packagesTitle: 'Packages',
  packageBadge: 'Package · Save {percent}%',
  packageIncludes: 'Includes: {list}',
  packageValidUntil: 'Offer valid until {date}',
  packageShowDetails: 'View included services',
  packageHideDetails: 'Hide details',
  packageItemSave: 'Save {amount}',
  packageScheduleEach:
    'All included services are booked back-to-back on one visit the same day',
  packageContinueCheckout: 'Continue to checkout',
  schedulePackage: 'Schedule package',
  packageCheckoutTitle: 'Confirm package',
  packageBookedTitle: 'Package booked',
  packageBookedHint: 'Your appointments are confirmed.',
  packageIncludedServices: 'Included services',
  packagePayAndBook: 'Pay & book package',
  packageBook: 'Book package',
  packagePaymentReturnHint:
    'Complete payment in your browser, then return here to confirm your booking.',
  packageCompletePayment: 'Complete payment…',
  packageConfirmPaymentReturn: 'I completed payment',
  chooseSpecialist: 'Choose a specialist',
  specialistAiHint: 'Pick a provider and time, then choose your service.',
  anySpecialist: 'Any available specialist',
  anySpecialistHint: 'Pick a service first — we will match you with an available specialist.',
  selectDateTime: 'Select date & time',
  selectService: 'Select a service',
  nearestSlots: 'Available {date}',
  todayInline: 'Today',
  noSlots: 'No open slots right now',
  chooseThisProfessional: 'Choose this professional',
  providerReviewsTitle: 'Customer reviews',
  providerReviewSummary: '{rating} ({count} reviews)',
  noProviderReviews: 'No reviews yet.',
  availableSlots: 'Available times',
  bookAppointment: 'Book an appointment',
  profileViewDetails: 'Salon profile',
  profileFollowUs: 'Follow us',
  profileLocation: 'Location',
  profileSocialWebsite: 'Website',
  profileSocialInstagram: 'Instagram',
  profileSocialFacebook: 'Facebook',
  profileSocialX: 'X',
  profileSocialTiktok: 'TikTok',
  profileSocialLinkedin: 'LinkedIn',
  profileSocialYoutube: 'YouTube',
  growthBookAnotherWay: 'Book another way',
  growthBookOnline: 'Book online',
  growthBookViaTelegram: 'Book via Telegram',
  growthBookViaWhatsApp: 'Book via WhatsApp',
  growthBookViaFacebook: 'Facebook',
  growthBookViaInstagram: 'Instagram',
  privacyDataTitle: 'Your data & privacy',
  privacyExportMyData: 'Download my data',
  privacyDeleteMyData: 'Delete my account data',
  privacyExportSuccess: 'Your data export has started.',
  privacyExportCopied: 'Your data was copied to the clipboard.',
  privacyDeleteConfirm: 'This permanently removes your profile from this business. Continue?',
  privacyDeleteSuccess: 'Your data has been deleted.',
  privacyActionFailed: 'Something went wrong. Try again later.',
  privacyLoading: 'Working…',
  tourImagePlaceholder: 'Tour',
  tourPricePerPerson: '{price} / person',
  tourPerPersonSuffix: 'per person',
  tourMaxGroup: 'Up to {count}',
  tourGroupSize: 'Group size',
  tourTravelersHint: '1–{max} travelers',
  tourLineTotal: '{unit} × {count} = {total}',
  tourRemainingSpots: '{count} spots left',
  tourDayDeparture: 'Departure',
  tourDifficultyEasy: 'Easy',
  tourDifficultyModerate: 'Moderate',
  tourDifficultyChallenging: 'Challenging',
  clinicServiceTypeConsultation: 'Consultation',
  clinicServiceTypeLabTest: 'Lab test',
  clinicServiceTypeProcedure: 'Procedure',
  clinicFastingRequired: 'Fasting required',
  clinicSymptoms: 'Symptoms or reason for visit',
  clinicSymptomsPlaceholder: 'Describe your symptoms (optional)',
  clinicReferralNotes: 'Referral notes',
  clinicReferralNotesPlaceholder: 'Referring doctor or prior test results (optional)',
  subscriptionsTitle: 'Subscriptions',
  subscriptionsEmpty: 'No subscriptions yet.',
  subscriptionsFallbackName: 'Subscription',
  subscriptionsVisitsLeft: '{remaining} / {included} visits left',
  subscriptionsExpires: 'Expires {date}',
  subscriptionsBookNext: 'Book next visit',
  subscriptionsUsageHistory: 'Usage history',
  subscriptionsNoUsage: 'No usage recorded yet.',
  subscriptionUsagePurchase: 'Plan purchased',
  subscriptionUsageRedeem: 'Visit used',
  subscriptionUsageExpire: 'Expired',
  subscriptionUsageLine: '{action} · {date} · {remaining} left',
  assistantExampleSubscriptions: 'How many visits are left on my subscription?',
  assistantExampleRebook: 'Rebook my last appointment',
  assistantExampleReferral: 'How do I refer a friend?',
  assistantExampleNotifications: 'What notifications will I get?',
  assistantExampleSavedSalons: 'Show my saved salons',
  assistantExampleExportData: 'How do I download my personal data?',
  professionalsEntryCta: 'Choose a specialist first',
  continueBooking: 'Continue booking',
  noServicesForSlot: 'No services available at this time.',
  professionalFallbackName: 'Professional',
  providerNotFound: 'Provider not found.',
  reviewYourRating: 'Your rating',
  reviewCommentPlaceholder: 'Share your experience (optional)',
  reviewSubmit: 'Submit review',
  reviewRatingRequired: 'Select a star rating first.',
  reviewSignInRequired: 'Sign in to leave a review.',
  reviewSubmitted: 'Thanks — your review was submitted.',
  dateLabel: 'Date',
};

export const CONSUMER_COPY_HY: ConsumerCopy = {
  cancelBooking: 'Չեղարկել ամրագրումը',
  cancelBookingConfirm: 'Չեղարկել այս հանդիպումը՞։ Սա չի կարող հետարկվել։',
  cancelBookingFailed: 'Չհաջողվեց չեղարկել հանդիպումը',
  rescheduleBooking: 'Փոխել ժամանակը',
  pickNewTime: 'Ընտրեք նոր ամսաթիվ և ժամ',
  loadingSlots: 'Բեռնվում են հասանելի ժամերը…',
  noSlotsThisDay: 'Այս օրը հասանելի ժամեր չկան',
  timeSlotMorning: 'Առավոտ',
  timeSlotAfternoon: 'Ցերեկ',
  timeSlotEvening: 'Երեկո',
  confirmReschedule: 'Հաստատել նոր ժամանակը',
  submitting: 'Ուղարկվում է…',
  rescheduleBookingFailed: 'Չհաջողվեց փոխել ժամանակը',
  rescheduleSummary: 'Նոր ժամ՝ {date} ժամը {time}',
  rescheduleSuccessDetail: 'Տեղափոխվել է {from}-ից դեպի {to}',
  rescheduleCountHint: '{count}/{max} վերապլանավորում օգտագործված է',
  rescheduleUpdatedTitle: 'Ամրագրումը թարմացվել է',
  reschedulePreviousLabel: 'Նախորդ',
  rescheduleNewLabel: 'Նոր',
  manageBookingTitle: 'Կառավարեք ձեր հանդիպումը',
  manageBookingInvalidLink: 'Այս հղումը անվավեր է կամ ժամկետանց',
  manageBookingSignInHint:
    'Մուտք գործեք նույն էլ. փոստով, որով կատարել եք ամրագրումը',
  signIn: 'Մուտք գործել',
  signInWithGoogle: 'Մուտք գործել Google-ով',
  cancelPackageVisit: 'Չեղարկել ամբողջ փաթեթային այցը',
  cancelPackageVisitConfirm:
    'Չեղարկել այս փաթեթային այցի բոլոր հանդիպումները՞։ Սա չի կարող հետարկվել։',
  cancelPackageVisitFailed: 'Չհաջողվեց չեղարկել փաթեթային այցը',
  reschedulePackageVisit: 'Վերապլանավորել ամբողջ այցը',
  reschedulePackageVisitSummary:
    'Տեղափոխել բոլոր {count} ծառայությունները դեպի {date}՝ սկսած {time}-ից',
  reschedulePackageVisitSuccess: 'Այցը տեղափոխվեց {from}-ից դեպի {to}',
  packageNoBlock: 'Այս փաթեթի համար հասանելի նույնօրյա այց չի գտնվել',
  bookingStatusCancelled: 'Չեղարկված',
  bookingStatusCompleted: 'Ավարտված',
  bookingStatusConfirmed: 'Հաստատված',
  packageVisitAppointmentCount: '{count} հանդիպում այս այցում',
  bookingConfirmed: 'Ամրագրումը կատարված է',
  bookingConfirmedHint: 'Կարող եք կառավարել այս ամրագրումը ձեր հաշվից',
  youMightAlsoLike: 'Դուք կարող եք նաև հավանել',
  dismissRecommendations: 'Թաքցնել առաջարկները',
  learnMore: 'Իմանալ ավելին',
  viewAppointments: 'Դիտել ամրագրումները',
  bookAnotherService: 'Ամրագրել ևս մեկը',
  checkoutSubtotal: 'Ենթագումար',
  checkoutTotalDue: 'Վճարման ենթակա',
  checkoutPromoCode: 'Պրոմո կամ նվեր քարտ',
  checkoutPromoPlaceholder: 'Մուտքագրեք կոդը',
  checkoutApplyPromo: 'Կիրառել',
  checkoutPromoApplied: 'Կիրառված՝ {code}',
  checkoutRemovePromo: 'Հեռացնել',
  checkoutLoyaltyPoints: 'Հավատարմության միավորներ',
  checkoutLoyaltyBalance: 'Մնացորդ՝ {points} միավոր ({value})',
  checkoutLoyaltyMaxHint: 'Առավելագույնը {max} միավոր',
  checkoutUseMaxPoints: 'Առավելագույնը',
  checkoutPromoDiscount: 'Պրոմո զեղչ',
  checkoutGiftCardDiscount: 'Նվեր քարտ',
  checkoutLoyaltyDiscount: 'Հավատարմության միավորներ',
  checkoutFreeAfterDiscounts: 'Ընդամենը',
  checkoutHowToBook: 'Ինչպե՞ս ցանկանում եք ամրագրել',
  checkoutUseSubscription: 'Օգտագործել բաժանորդագրությունը',
  checkoutAppointmentsLeft: 'այցելություն մնաց',
  checkoutExpiresOn: 'վավեր է մինչև',
  checkoutFreeThisVisit: '$0 այս այցի համար',
  checkoutOneTimeAppointment: 'Մեկանգամյա այց',
  checkoutSubscribeAndSave: 'Բաժանորդագրվել և խնայել',
  checkoutChooseSubscriptionPlan: 'Ընտրեք բաժանորդագրության պլան',
  checkoutSaveAmount: 'խնայեք {amount}',
  checkoutSubscriptionPlanRequired: 'Ընտրեք բաժանորդագրության պլան',
  checkoutUsingSubscriptionHint: 'Այս ամրագրումից հետո {remaining} այցելություն կմնա',
  checkoutPlanIncludesHint: 'Պլանը ներառում է {visits} այցելություն',
  checkoutSelectedTime: 'Ընտրված ժամ',
  checkoutBookingService: 'Ծառայություն',
  checkoutEdit: 'Խմբագրել',
  taxIncluded: 'ներառված',
  myResultsTab: 'Արդյունքներ',
  myResultsTitle: 'Իմ արդյունքները',
  myResultsEmpty:
    'Ազատված լաբորատոր արդյունքներ դեռ չկան։ Դրանք կհայտնվեն այստեղ, երբ կլինիկան ազատի արդյունքները։',
  myResultsReleasedOn: 'Ազատված',
  myResultsUnnamed: 'Լաբորատոր արդյունք',
  myResultsMeasurement: 'Թեստ',
  myResultsValue: 'Արդյունք',
  myResultsReferenceRange: 'Նորմայի միջակայք',
  myResultsFlag: 'Դրոշ',
  myResultsLoadFailed: 'Չհաջողվեց բեռնել լաբորատոր արդյունքները',
  myResultsSignInPrompt: 'Մուտք գործեք՝ {name}-ում լաբորատոր արդյունքները դիտելու համար',
  myLabToBookTitle: 'Ամրագրելիք լաբորատոր հավաքումներ',
  myLabToBookTab: 'Լաբ. հավաքում',
  myLabToBookSignInPrompt: 'Մուտք գործեք՝ {name}-ում սպասող լաբորատոր հավաքման հարցումները տեսնելու համար։',
  homeLabToBookShortcut: 'Ամրագրել լաբորատոր հավաքում',
  homeLabToBookShortcutPending: 'Ամրագրել լաբորատոր հավաքում ({count} սպասող)',
  myLabToBookEmpty: 'Սպասող լաբորատոր հավաքման ամրագրումներ չկան։',
  myLabToBookCollectionService: 'Ամրագրել՝ {service}',
  myLabToBookRequestedOn: 'Հարցում՝ {date}',
  myLabToBookBookCollection: 'Ամրագրել հավաքում',
  myLabToBookLoadFailed: 'Չհաջողվեց բեռնել լաբորատոր ամրագրումների հարցումները',
  myLabToBookUnnamedOrder: 'Լաբորատոր պատվեր',
  myDocumentsTitle: 'Իմ փաստաթղթերը',
  myDocumentsEmpty:
    'Դեռ փաստաթղթեր չեն հրապարակվել։ Դրանք կհայտնվեն այստեղ, երբ կլինիկան ազատի դրանք։',
  myDocumentsOpenDocument: 'Բացել PDF',
  myDocumentsUnnamed: 'Փաստաթուղթ',
  myDocumentsLoadFailed: 'Չհաջողվեց բեռնել փաստաթղթերը',
  myDocumentsCategoryLine: '{category} · {date}',
  myDocumentCategories: {
    lab_report: 'Լաբորատոր հաշվետվություն',
    referral_letter: 'Ուղղորդում',
    imaging_report: 'Ուղղորդված պատկեր',
    other: 'Այլ',
  },
  resultStatusNotReceived: 'Չի ստացվել',
  resultStatusPending: 'Սպասման մեջ',
  resultStatusWaitingCompletion: 'Սպասում է ավարտին',
  resultStatusCompleted: 'Ավարտված',
  resultStatusReviewed: 'Վերանայված',
  resultStatusAutomaticallyReviewed: 'Ավտոմատ վերանայված',
  resultStatusReleased: 'Հրապարակված',
  resultStatusRejected: 'Մերժված',
  measurementFlagNormal: 'Նորմալ',
  measurementFlagAbnormal: 'Աննորմալ',
  measurementFlagHigh: 'Բարձր',
  measurementFlagLow: 'Ցածր',
  measurementFlagInconclusive: 'Անորոշելի',
  measurementFlagIndeterminate: 'Անորոշ',
  measurementFlagTestNotComplete: 'Թեստը ավարտված չէ',
  measurementFlagNotApplicable: 'Կիրառելի չէ',
  measurementFlagSeeDetails: 'Տես մանրամասները',
  publicIntakeCheckoutTitle: 'Նախապոստ այցի ընտրովի հարցաթերթիկ',
  publicIntakeCheckoutSubtitle:
    'Պատասխանեք մի քանի հարցի՝ գրանցումից առաջ, որպեսզի լաբորատորիան պատրաստվի ձեր այցին։',
  publicIntakeSkip: 'Բաց թողնել',
  publicIntakeStart: 'Սկսել հարցաթերթիկը',
  publicIntakeContinue: 'Շարունակել',
  publicIntakeAnswerLabel: 'Ձեր պատասխանը',
  publicIntakeUntitledQuestion: 'Անվերնագիր հարց',
  publicIntakeLoadFailed: 'Չհաջողվեց բեռնել հարցաթերթիկը։',
  publicIntakeSubmitFailed: 'Չհաջողվեց պահպանել պատասխանը։',
  publicIntakeContinueToBooking: 'Շարունակել գրանցումը',
  patientAlertsRegionLabel: 'Կլինիկայի ծանուցումներ',
  patientAlertsViewAction: 'Դիտել',
  patientAlertsDismiss: 'Փակել',
  patientAlertTitleReleased: 'Նոր լաբորատոր արդյունք',
  patientAlertTitleIntake: 'Նախայցային հարցաթերթիկը incomplete է',
  patientAlertTitleLabBooking: 'Լաբորատոր հավաքում ամրագրել',
  patientAlertBodyReleased: '{testName}-ը պատրաստ է դիտման համար։',
  patientAlertBodyIntake: '{questionnaireTitle}-ը դեռ պահանջում է պատասխաններ այցից առաջ։',
  patientAlertBodyLabBooking:
    'Ամրագրեք {collectionServiceName} պատվիրած թեստերի համար ({orderDisplayNames})։',
  assistantTitle: 'Ամրագրման օգնական',
  assistantHint: 'Հարցրեք ծառայությունների, ազատ ժամերի կամ ձեր ամրագրումների մասին։',
  assistantHelpChip: 'Օգնություն',
  assistantHelpChipHint: 'Ցույց տալ ամրագրման օգնության առաջարկները',
  assistantGuideExamples: 'Փորձեք օգնության համար հարցնել՝',
  assistantGuideStepOf: 'Քայլ {current}/{total}',
  assistantGuideNextStep: 'Հաջորդ քայլ',
  assistantGuideOpenInApp: 'Բացել հավելվածում',
  assistantGuideStillStuck: 'Դեռ stuck?',
  assistantPlaceholder: 'Գրեք հարց…',
  assistantThinking: 'Մտածում է…',
  assistantContinueBooking: 'Շարունակել ամրագրումը',
  assistantClose: 'Փակել',
  assistantErrorGeneric: 'Ինչ-որ բան սխալ գնաց։ Կրկին փորձեք։',
  assistantExampleAvailable: 'Ով է ազատ վաղը ցերեկյան {service}-ի համար?',
  assistantExampleServices: 'Ինչ ծառայություններ ունեք?',
  assistantExampleBook: 'Ամրագրել {service} այս ուրբաթ',
  assistantExampleLocation: 'Որտե՞ղ եք գտնվում?',
  assistantFallbackProvider: 'մասնագետ',
  assistantFallbackService: 'ծառայություն',
  assistantFallbackServiceCategory: 'մեր ծառայությունները',
  assistantExampleGuideBook: 'Ինչպե՞ս քայլ առ քայլ ամրագրել այց',
  assistantExampleGuideCheckout: 'Ցույց տուր checkout-ի քայլերը',
  assistantExampleGuideServices: 'Ինչպե՞ս ընտրել ծառայություն և մասնագետ',
  assistantExampleGuideLocation: 'Որտեղ գտնեմ հասցեն',
  assistantDiscoverChipsTitle: 'Ծառայությունների որոնում',
  ...buildDiscoverChipCopyFields('hy'),
  availableProvidersTitle: 'Ազատ մասնագետներ',
  bookProvider: 'Ամրագրել',
  voiceStart: 'Ձայնային մուտք',
  voiceStop: 'Դադարեցնել',
  voiceUnsupported: 'Ձայնային մուտքը չի աջակցվում այս սարքում։',
  voiceDenied: 'Խոսափողի թույլտվությունը մերժված է։',
  voiceNoSpeech: 'Խոսք չի հայտնաբերվել։ Կրկին փորձեք։',
  voiceError: 'Ձայնային մուտքը ձախողվեց։ Կրկին փորձեք։',
  speakReply: 'Լսել',
  multiServiceBookedTitle: 'Ամրագրումները հաստատված են',
  multiServiceBookedHint: 'Ձեր բազմածառայության այցը հաստատված է։',
  multiServiceWithProvider: '{name}-ի հետ',
  multiServiceConfirmAction: 'Հաստատել ամրագրումը',
  multiServicePaymentReturnHint:
    'Ավարտեք վճարումը ձեր բրաուզերում, ապա վերադարձեք այստեղ՝ ամրագրումը հաստատելու համար։',
  multiServiceCompletePayment: 'Ավարտել վճարումը…',
  multiServiceConfirmPaymentReturn: 'Վճարումն ավարտեցի',
  multiServiceEntryCta: 'Ամրագրել մի քանի ծառայություն',
  multiServiceSelectHint: 'Ընտրեք մեկ ծառայություն կամ երկու և ավելի՝ մեկ այցում ամրագրելու համար։',
  multiServiceCart: '{count} ծառայություն ընտրված է',
  multiServiceTotal: '{duration} ր · {price}',
  multiServiceContinue: 'Շարունակել ընտրված ծառայություններով',
  multiServiceAvailabilityTitle: 'Ընտրեք ամսաթիվ և ժամ',
  multiServicePickBlockHint: 'Ընտրեք ժամային բլոկ, որը համապատասխանում է բոլոր ծառայություններին։',
  multiServiceEditServices: 'Խմբագրել ծառայությունները',
  multiServiceEditProvider: 'Փոխել մասնագետին',
  multiServiceConfirmTitle: 'Ժամանակացույց ձեր ծառայությունների համար',
  multiServiceScheduleEach: 'Ընտրեք ամսաթիվ և ժամ յուրաքանչյուր ծառայության համար։',
  multiServiceFindingSlots: 'Փնտրվում են ազատ ժամեր…',
  multiServiceCheckoutTitle: 'Հաստատեք ձեր այցը',
  uncategorizedServices: 'Այլ ծառայություններ',
  servicesSection: 'Ծառայություններ',
  selectSpecialist: 'Մասնագետ',
  noTimesAvailable: 'Այս օրը ազատ ժամեր չկան։',
  loadAvailableTimesFailed: 'Չհաջողվեց բեռնել ազատ ժամերը։',
  findAvailableBlockFailed: 'Չհաջողվեց գտնել ազատ բլոկ։',
  validateServiceSelectionFailed: 'Չհաջողվեց ստուգել ծառայությունների ընտրությունը։',
  removeService: 'Հեռացնել',
  bookAnother: 'Ամրագրել ևս մեկ',
  totalDue: 'Ընդամենը',
  feedbackUp: 'Օգտակար',
  feedbackDown: 'Ոչ օգտակար',
  feedbackThanks: 'Շնորհակալություն — դա օգնում է բարելավել օգնականին։',
  feedbackReasonSkip: 'Բաց թողնել',
  feedbackReasonWrongAction: 'Սխալ գործողություն',
  feedbackReasonWrongDate: 'Սխալ ամսաթիվ',
  feedbackReasonWrongPerson: 'Սխալ անձ',
  feedbackReasonWrongService: 'Սխալ ծառայություն',
  feedbackReasonDidNotUnderstand: 'Չհասկացավ',
  postBookingSatisfactionTitle: 'Ինչպե՞ս էր ձեր ամրագրումը',
  postBookingSatisfactionMessage:
    'Ձեր հանդիպումը հաստատված է։ Կարճ գնահատականը օգնում է մեզ բարելավվել — միայն եթե ունեք րոպե։',
  postBookingSatisfactionGreat: 'Հիանալի!',
  postBookingSatisfactionUnhappy: 'Կարող էր ավելի լավ լինել',
  postBookingSatisfactionDismiss: 'Ոչ հիմա',
  postBookingReviewRateTitle: 'Գնահատել այցը',
  postBookingReviewSubmitAction: 'Ուղարկել կարծիքը',
  postBookingReviewSubmitFailed: 'Չհաջողվեց ուղարկել կարծիքը։ Փորձեք ավելի ուշ։',

  postBookingSupportTitle: 'Աջակցություն',
  postBookingSupportSubmitted:
    'Շնորհակալություն — սրահի թիմը տեղեկացվել է և կկապվի էլ. փոստով։',
  postBookingSupportFailed:
    'Չհաջողվեց ավտոմատ կերպով դիմում բացել։ Սեղմեք OK՝ աջակցությունը կայքում բացելու համար։',
  postBookingSupportUnavailable:
    'Այս սրահի համար աջակցությունը դեռ կարգավորված չէ։ Կարող եք կապվել հաստատման էլ. փոստով։',
  rewardsSectionTitle: 'Պարգևներ և առաջարկներ',
  rewardsLoyaltyBalanceTitle: 'Ձեր պարգևների մնացորդը',
  rewardsLoyaltyBalance: '{amount} հասանելի',
  rewardsLoyaltyEarnRate: 'Ստացեք {percent}% bonus հարկավոր այցերից',
  rewardsPromosHint: 'Օգտագործեք այս կոդերը ամրագրելիս.',
  rewardsPromoMinimum: 'Նվազագույն գնում {amount}',
  rewardsPromoExpires: 'Վավեր է մինչև {date}',
  rewardsBookToRedeem: 'Ամրագրել օգտագործելու համար',
  rewardsSignInHint: 'Մուտք գործեք՝ պարգևների մնացորդը և առաջարկները տեսնելու համար.',
  widgetNextAppointmentTitle: 'Հաջորդ հանդիպում',
  widgetNextAppointmentSubtitle: '{date} · {time} · {provider}',
  widgetQuickRebookTitle: 'Կրկին ամրագրել',
  widgetQuickRebookSubtitle: '{provider}-ի հետ',
  widgetSignedOutTitle: 'Մուտք OptiSchedule Book',
  widgetSignedOutSubtitle: 'Տեսեք առաջիկա այցերը և ամրագրեք մեկ հպումով',
  notificationPrefsSectionTitle: 'Ծանուցումների կարգավորումներ',
  notificationPrefsSectionHint:
    'Ընտրեք, թե ինչ push ծանուցումներ եք ցանկանում։ Հանդիպման հիշեցումները լռելյայն միացված են, որպեսզի այցը չկորցնեք։',
  notificationPrefsRemindersTitle: 'Հանդիպման հիշեցումներ',
  notificationPrefsRemindersDescription:
    'Հաստատումներ, փոփոխված ժամանակներ և այցից առաջ հիշեցումներ։',
  notificationPrefsOffersTitle: 'Առաջարկներ և կրկին ամրագրում',
  notificationPrefsOffersDescription:
    'Պրոմո կոդեր, վերադարձի հաղորդագրություններ և սովորական ծառայությունը կրկին ամրագրելու հուշումներ։',
  notificationPrefsNewsTitle: 'Սրահի նորություններ',
  notificationPrefsNewsDescription:
    'Թարմացումներ, հայտարարություններ և երբեմնի ներգրավման հաղորդագրություններ։',
  notificationPrefsLoadFailed: 'Չհաջողվեց բեռնել ծանուցումների կարգավորումները։',
  notificationPrefsSaveFailed: 'Չհաջողվեց պահպանել կարգավորումը։ Կրկին փորձեք։',
  offlineStatusOffline: 'Դուք offline եք։ Փոփոխությունները կհամաժամացվեն կապի վերականգնումից հետո։',
  offlineStatusSyncing: '{count} փոփոխություն սպասում է համաժամացման…',
  offlineCachedSalon: 'Ցուցադրվում է salon-ի պահպանված տեղեկատվությունը։',
  offlineMutationQueued: 'Պահպանվել է offline — կհամաժամացվի կապի վերականգնումից հետո։',
  appGateTitle: 'Պահանջվում է թարմացում',
  appGateKillSwitchMessage: 'Այս տարբերակը ժամանակավորապես անհասանելի է։ Փորձեք ավելի ուշ։',
  appGateUpdateRequiredMessage: 'Թարմացրեք OptiSchedule Book-ը՝ շարունակելու համար։',
  appGateUpdateNudgeMessage: 'OptiSchedule Book-ի նոր տարբերակը հասանելի է բարելավումներով։',
  appGateUpdateAction: 'Թարմացնել store-ում',
  appGateDismissAction: 'Ոչ հիմա',
  analyticsConsentTitle: 'Վերլուծության համաձայնություն',
  analyticsConsentMessage:
    'Օգնեք բարելավել հավելվածը անանուն օգտագործման վերլուծությամբ։ Անձնական տվյալներ չեն հավաքվում։',
  analyticsConsentAccept: 'Ընդունել',
  analyticsConsentDecline: 'Մերժել',
  pushPrimingTitle: 'Ձեր ժամանակահատվածը հաստատված է',
  pushPrimingBody:
    'Միացրեք հիշեցումները, և մենք կտեղեկացնենք ամրագրումների և այցից առաջ։',
  pushPrimingAccept: 'Այո, հիշեցրեք',
  pushPrimingDecline: 'Ոչ հիմա',
  pushProvisionalUpgradeTitle: 'Միացնե՞լ հիշեցումները',
  pushProvisionalUpgradeBody:
    'Դուք բացեցիք հիշեցում — միացրեք ամբողջական ծանուցումները, որպեսզի գրանծման թարմացումները երևան էկրանին։',
  pushProvisionalUpgradeAccept: 'Միացնել հիշեցումները',
  pushProvisionalUpgradeDecline: 'Ոչ հիմա',
  pushSettingsReaskTitle: 'Կրկին միացրեք ծանուցումները',
  pushSettingsReaskBody:
    'Մենք կարող ենք հիշեցնել մոտ approaching այցեր միայն Settings-ում ծանուցումները միացված լինելու դեպքում։',
  pushSettingsReaskOpen: 'Բացել Settings',
  pushSettingsReaskSkip: 'Բաց թողնել',
  postBookingSignInTitle: 'Պահպանեք այս ամրագրումը ձեր հաշվում',
  postBookingSignInBody:
    'Մեկ հպում Apple-ով կամ Google-ով — հյուրի ամրագրումները ավտոմատ միանում են։ Կարող եք բաց թողնել և մուտք գործել ավելի ուշ։',
  postBookingSignInGoogle: 'Շարունակել Google-ով',
  postBookingSignInApple: 'Շարունակել Apple-ով',
  postBookingSignInSkip: 'Ավելի ուշ',
  postBookingSignInBusy: 'Մուտք գործում…',
  activationPaymentOptionalHint:
    'Վճարեք այցի ժամանակ — առցանց վճարումը պարտադիր չէ ձեր առաջին ամրագրման համար։',
  activationPaymentHiccupMessage:
    'Առցանց վճարումը չի ավարտվել։ Դուք դեռ կարող եք հաստատել և վճարել սրահում։',
  activationPayAtVenueFallbackAction: 'Հաստատել և վճարել այցի ժամանակ',
  activationPayAtVenueSelected:
    'Ընտրված է «վճարել այցի ժամանակ» — հաստատեք ստորև՝ ամրագրումն ավարտելու համար։',
  activationConfirmBooking: 'Հաստատել ամրագրումը',
  activationPayAtVisitConfirm: 'Հաստատել — վճարել այցի ժամանակ',
  bookingDraftResumeConfirm: 'Շարունակեք ամրագրումը — հաստատեք ժամանակը ստորև։',
  bookingDraftResumeSlot: 'Շարունակեք ամրագրումը — ընտրեք ժամանակը ստորև։',
  bookingDraftResumeService: 'Շարունակեք ձեր չավարտված ամրագրումը ստորև։',
  networkFeedbackCreated: 'Պահպանված',
  networkFeedbackUpdated: 'Թարմացված',
  networkFeedbackDeleted: 'Հեռացված',
  networkFeedbackFailed: 'Սխալ է տեղի ունեցել։ Ստուգեք կապը և փորձեք կրկին։',
  networkFeedbackFailedCreate: 'Հնարավոր չեղավ ավարտել հարցումը։',
  networkFeedbackFailedUpdate: 'Հնարավոր չեղավ պահպանել փոփոխությունները։',
  networkFeedbackFailedDelete: 'Հնարավոր չեղավ հեռացնել։',
  networkRetryAction: 'Կրկին փորձել',
  networkLoadFailed: 'Չհաջողվեց բեռնել։ Ստուգեք կապը և փորձեք կրկին։',
  growthSectionTitle: 'Կրկին ամրագրել և կիսվել',
  growthRebookTitle: 'Կրկին ամրագրել վերջին այցը',
  growthRebookSubtitle: '{service} · {provider}',
  growthRebookAction: 'Ամրագրել հիմա',
  growthShareSalonTitle: 'Կիսվել սalon-ով',
  growthShareSalonAction: 'Կիսվել հղումով',
  growthShareBookingAction: 'Կիսվել ամրագրումով',
  growthReferTitle: 'Ուղղորդել ընկերոջ',
  growthReferSubtitle: 'Հրավիրեք ընկերներ — {businessName}-ում երկուսդ էլ կստանաք պարգևներ։',
  growthReferAction: 'Ուղարկել հրավեր',
  growthShareCopied: 'Հղումը պատճենված է։',
  growthShareUnavailable: 'Այս սարքում կիսվելը հասանելի չէ։',
  growthShareRewardEarned: 'Կիսվելու համար ստացաք {reward}!',
  postBookingTenantReviewAction: 'Գնահատել այցը',
  giftCardNav: 'Նվեր քարտեր',
  giftCardTitle: 'Գնել նվեր քարտ',
  giftCardSubtitle: 'Նվիրեք ինքնախնամք՝ թվային կամ ֆիզիկական ձևով',
  giftCardChooseType: 'Ի՞նչ եք ցանկանում նվիրել',
  giftCardTypeMonetary: 'Գումար',
  giftCardTypeService: 'Ծառայություն',
  giftCardTypeBundle: 'Փաթեթ',
  giftCardTypePackage: 'Ծառայությունների փաթեթ',
  giftCardTypeSubscription: 'Բաժանորդագրություն',
  giftCardTypeDescMonetary: 'Գումար, որը կարող են օգտագործել ցանկացած ամրագրման համար',
  giftCardTypeDescService: 'Մեկ կամ մի քանի առանձին ծառայություններ',
  giftCardTypeDescBundle: 'Բիզնեսի կողմից կազմված ծառայությունների համադրություն',
  giftCardTypeDescPackage: 'Այս բիզնեսի գոյություն ունեցող փաթեթ',
  giftCardTypeDescSubscription: 'Այս բիզնեսի գոյություն ունեցող բաժանորդագրության պլան',
  giftCardAmountHint: 'Ընտրեք նախընտրելի գումար կամ մուտքագրեք ձեր սեփականը',
  giftCardSelectServicesHint: 'Ընտրեք մեկ կամ մի քանի ծառայություն',
  giftCardSelectedServices: '{count} ծառայություն ընտրված',
  giftCardContinueCheckout: 'Շարունակել վճարմանը',
  giftCardCheckoutTitle: 'Նվեր քարտի վճարում',
  giftCardYourDetails: 'Ձեր տվյալները',
  giftCardRecipientSection: 'Ստացող',
  giftCardBuyForSelf: 'Ինձ համար',
  giftCardBuyAsGift: 'Նվեր',
  giftCardPurchaserName: 'Ձեր անունը',
  giftCardPurchaserEmail: 'Ձեր էլ. փոստը (կտրոն)',
  giftCardRecipientName: 'Ստացողի անուն',
  giftCardRecipientEmail: 'Ստացողի էլ. փոստ',
  giftCardRecipientPhone: 'Ստացողի հեռախոս',
  giftCardPersonalMessage: 'Անհատական հաղորդագրություն (ընտրովի)',
  giftCardDeliverySection: 'Առաքում',
  giftCardDeliveryDigital: 'Թվային',
  giftCardDeliveryPhysical: 'Ֆիզիկական',
  giftCardAddressLine1: 'Հասցե 1',
  giftCardAddressLine2: 'Հասցե 2 (ընտրովի)',
  giftCardCity: 'Քաղաք',
  giftCardPostalCode: 'Փոստային կոդ',
  giftCardCountry: 'Երկիր',
  giftCardDeliveryInstructions: 'Առաքման ցուցումներ (ընտրովի)',
  giftCardShipping: 'Առաքում',
  giftCardTotal: 'Ենթագումար',
  giftCardTotalDue: 'Վճարման ենթակա',
  giftCardPayNow: 'Վճարել քարտով',
  giftCardConfirmCashPurchase: 'Հաստատել գնումը',
  giftCardPayCashAtVisit: 'Վճարեք {amount} հաջորդ այցելության ժամանակ',
  giftCardSuccessTitle: 'Նվեր քարտը գնված է',
  giftCardSuccessBody: 'Մանրամասները ուղարկվել են էլ. փոստով',
  giftCardQuoteFailed: 'Չհաջողվեց հաշվարկել գինը',
  giftCardCheckoutFailed: 'Չհաջողվեց սկսել վճարումը',
  giftCardEmailRequired: 'Գնորդի էլ. փոստը պարտադիր է',
  giftCardPurchaserNameRequired: 'Մուտքագրեք ձեր անունը',
  giftCardConsentRequired: 'Խնդրում ենք ընդունել գաղտնիության քաղաքականությունը',
  giftCardPaymentFailed: 'Վճարման հաստատումը ձախողվեց',
  giftCardMyGiftCards: 'Իմ նվեր քարտերը',
  giftCardMyOrdered: 'Գնված նվեր քարտեր',
  giftCardMyRedeemed: 'Մարած նվեր քարտեր',
  giftCardNoOrders: 'Դեռ նվեր քարտի գնումներ չկան',
  giftCardNoRedeemed: 'Դեռ մարած նվեր քարտեր չկան',
  giftCardRedeemSectionTitle: 'Մարել ստացված նվերը',
  giftCardClaimTitle: 'Մարել նվերի կոդը հաշվում',
  giftCardClaimHint: 'Տեղադրեք էլ. փոստով ստացած կոդը՝ հաշվին ավելացնելու համար',
  giftCardClaimPlaceholder: 'Նվերի կոդ էլ. փոստից',
  giftCardClaimSubmit: 'Մարել կոդը',
  giftCardClaimSuccess: 'Նվերը հաջողությամբ մարվեց',
  giftCardClaimPackageSuccess: 'Փաթեթը ավելացվել է ձեր հաշվին',
  giftCardClaimSubscriptionSuccess: 'Բաժանորդագրությունը ավելացվել է ձեր հաշվին',
  giftCardClaimServiceSuccess: 'Ծառայության նվերը պահված է — օգտագործեք կոդը վճարման ժամանակ',
  giftCardClaimBundleSuccess: 'Փաթեթի նվերը պահված է — օգտագործեք կոդը վճարման ժամանակ',
  giftCardRedeemedHint: 'Մարած նվերները ցուցադրվում են այստեղ',
  giftCardBookToUse: 'Ամրագրել այց',
  giftCardCreditsRemaining: 'մնացել է',
  giftCardClaimedOn: 'Մարվել է {date}',
  giftCardRedeemedPackageHint: 'Ամրագրեք փաթեթի այցելությունները ծառայություններից',
  giftCardRedeemedSubscriptionHint: 'Բաժանորդագրությունը ակտիվ է այս հաշվում',
  giftCardRedeemedServiceHint: 'Օգտագործեք կոդը համապատասխան ծառայություններ ամրագրելիս',
  giftCardBalance: 'մնացորդ',
  giftCardActive: 'Ակտիվ',
  giftCardInactive: 'Անակտիվ',
  giftCardCancelOrder: 'Չեղարկել պատվերը',
  giftCardCancelWindow: 'Չեղարկման ժամկետ',
  giftCardCancelConfirm: 'Չեղարկե՞լ այս նվեր քարտի պատվերը',
  giftCardCancelSuccess: 'Չեղարկման հարցումը ուղարկված է',
  giftCardCancelRefunded: 'Պատվերը չեղարկված է և վերադարձվել է',
  giftCardCancelRefundFailed: 'Չեղարկված է, բայց վերադարձը ձախողվեց',
  giftCardRequestStatus: 'Հարցման կարգավիճակ',
  giftCardPackageBadge: 'Փաթեթ',
  giftCardSaveBadge: 'Խնայեք {percent}%',
  giftCardSubscribeBadge: 'Բաժանորդագրվեք և խնայեք',
  giftCardSubscriptionAppointments: 'այցելություն',
  giftCardSubscriptionMonths: 'ամիս',
  giftCardBundleSelected: 'Փաթեթը ընտրված է',
  giftCardBuyGiftCard: 'Գնել նվեր քարտ',
  giftCardStatusCancelled: 'Չեղարկված',
  giftCardPrivacyConsent: 'Համաձայն եմ գաղտնիության քաղաքականությանը',
  giftCardPaymentMethod: 'Վճարում',
  giftCardPayOnline: 'Առցանց վճարում',
  giftCardPayCashShort: 'Վճարել այցելության ժամանակ',
  packagesTitle: 'Փաթեթներ',
  packageBadge: 'Փաթեթ · Խնայեք {percent}%',
  packageIncludes: 'Ներառում է՝ {list}',
  packageValidUntil: 'Ակցիան վավեր է մինչև {date}',
  packageShowDetails: 'Դիտել ներառված ծառայությունները',
  packageHideDetails: 'Թաքցնել մանրամասները',
  packageItemSave: 'Խնայեք {amount}',
  packageScheduleEach:
    'Բոլոր ներառված ծառայությունները ամրագրվում են հաջորդականությամբ մեկ այցի ընթացքում',
  packageContinueCheckout: 'Շարունակել վճարմանը',
  schedulePackage: 'Ամրագրել փաթեթը',
  packageCheckoutTitle: 'Հաստատել փաթեթը',
  packageBookedTitle: 'Փաթեթը ամրագրված է',
  packageBookedHint: 'Ձեր այցելությունները հաստատված են։',
  packageIncludedServices: 'Ներառված ծառայություններ',
  packagePayAndBook: 'Վճարել և ամրագրել',
  packageBook: 'Ամրագրել փաթեթը',
  packagePaymentReturnHint:
    'Ավարտեք վճարումը բրաուզերում, ապա վերադարձեք այստեղ՝ ամրագրումը հաստատելու համար։',
  packageCompletePayment: 'Ավարտել վճարումը…',
  packageConfirmPaymentReturn: 'Վճարումն ավարտեցի',
  chooseSpecialist: 'Ընտրել մասնագետ',
  specialistAiHint: 'Ընտրեք մասնագետ և ժամ, ապա ծառայությունը։',
  anySpecialist: 'Ցանկացած ազատ մասնագետ',
  anySpecialistHint: 'Սկզբում ընտրեք ծառայություն — մենք կկցենք հասանելի մասնագետի',
  selectDateTime: 'Ընտրեք ամսաթիվ և ժամ',
  selectService: 'Ընտրել ծառայություն',
  nearestSlots: 'Հասանելի {date}',
  todayInline: 'Այսօր',
  noSlots: 'Այս պահին ազատ ժամեր չկան',
  chooseThisProfessional: 'Ընտրել այս մասնագետին',
  providerReviewsTitle: 'Հաճախորդների կարծիքներ',
  providerReviewSummary: '{rating} ({count} կարծիք)',
  noProviderReviews: 'Դեռ կարծիքներ չկան։',
  availableSlots: 'Հասանելի ժամեր',
  bookAppointment: 'Ամրագրել այց',
  profileViewDetails: 'Salon-ի էջ',
  profileFollowUs: 'Հետևեք մեզ',
  profileLocation: 'Հասցե',
  profileSocialWebsite: 'Կայք',
  profileSocialInstagram: 'Instagram',
  profileSocialFacebook: 'Facebook',
  profileSocialX: 'X',
  profileSocialTiktok: 'TikTok',
  profileSocialLinkedin: 'LinkedIn',
  profileSocialYoutube: 'YouTube',
  growthBookAnotherWay: 'Ամրագրել այլ կերպ',
  growthBookOnline: 'Ամրագրել առցանց',
  growthBookViaTelegram: 'Ամրագրել Telegram-ով',
  growthBookViaWhatsApp: 'Ամրագրել WhatsApp-ով',
  growthBookViaFacebook: 'Facebook',
  growthBookViaInstagram: 'Instagram',
  privacyDataTitle: 'Ձեր տվյալներ և գաղտնիություն',
  privacyExportMyData: 'Ներբեռնել իմ տվյալները',
  privacyDeleteMyData: 'Ջնջել իմ հաշվի տվյալները',
  privacyExportSuccess: 'Ձեր տվյալների արտահանումը սկսվել է։',
  privacyExportCopied: 'Ձեր տվյալները պատճենվել են clipboard-ում։',
  privacyDeleteConfirm: 'Սա մշտապես կջնջի ձեր պրոֆիլը այս բիզնեսից։ Շարունակե՞լ։',
  privacyDeleteSuccess: 'Ձեր տվյալները ջնջվել են։',
  privacyActionFailed: 'Ինչ-որ բան սխալ գնաց։ Փորձեք կրկին։',
  privacyLoading: 'Կատարվում է…',
  tourImagePlaceholder: 'Տուր',
  tourPricePerPerson: '{price} / անձ',
  tourPerPersonSuffix: 'մեկ անձի համար',
  tourMaxGroup: 'Մինչև {count}',
  tourGroupSize: 'Խմբի չափ',
  tourTravelersHint: '1–{max} ճանապարհորդ',
  tourLineTotal: '{unit} × {count} = {total}',
  tourRemainingSpots: '{count} տեղ մնաց',
  tourDayDeparture: 'Մեկնում',
  tourDifficultyEasy: 'Հեշտ',
  tourDifficultyModerate: 'Միջին',
  tourDifficultyChallenging: 'Բարդ',
  clinicServiceTypeConsultation: 'Խորհրդատվություն',
  clinicServiceTypeLabTest: 'Լաբորատոր թեստ',
  clinicServiceTypeProcedure: 'Գործընթաց',
  clinicFastingRequired: 'Պահանջվում է ծոմապահություն',
  clinicSymptoms: 'Ախտանիշներ կամ այցի պատճառ',
  clinicSymptomsPlaceholder: 'Նկարագրեք ախտանիշները (ընտրովի)',
  clinicReferralNotes: 'Ուղղորդման նշումներ',
  clinicReferralNotesPlaceholder: 'Ուղղորդող բժիշկ կամ նախորդ թեստեր (ընտրովի)',
  subscriptionsTitle: 'Բաժանորդագրություններ',
  subscriptionsEmpty: 'Բաժանորդագրություններ դեռ չկան։',
  subscriptionsFallbackName: 'Բաժանորդագրություն',
  subscriptionsVisitsLeft: '{remaining} / {included} այց մնաց',
  subscriptionsExpires: 'Ժամկետը {date}',
  subscriptionsBookNext: 'Ամրագրել հաջորդ այցը',
  subscriptionsUsageHistory: 'Օգտագործման պատմություն',
  subscriptionsNoUsage: 'Դեռ գրառումներ չկան։',
  subscriptionUsagePurchase: 'Պլանը գնված է',
  subscriptionUsageRedeem: 'Այցը օգտագործվել է',
  subscriptionUsageExpire: 'Ժամկետը լրացել է',
  subscriptionUsageLine: '{action} · {date} · {remaining} մնաց',
  assistantExampleSubscriptions: 'Քանի այց է մնաց իմ բաժանորդագրությունից?',
  assistantExampleRebook: 'Կրկին ամրագրել վերջին այցը',
  assistantExampleReferral: 'Ինչպե՞ս հրավիրել ընկերոջը',
  assistantExampleNotifications: 'Ինչ ծանուցումներ կստանամ?',
  assistantExampleSavedSalons: 'Ցույց տուր պահպանված սalon-ները',
  assistantExampleExportData: 'Ինչպե՞ս ներբեռնել իմ անձնական տվյալները',
  professionalsEntryCta: 'Նախ ընտրեք մասնագետ',
  continueBooking: 'Շարունակել ամրագրումը',
  noServicesForSlot: 'Այս ժամին հասանելի ծառայություններ չկան։',
  professionalFallbackName: 'Մասնագետ',
  providerNotFound: 'Մասնագետը չի գտնվել։',
  reviewYourRating: 'Ձեր գնահատականը',
  reviewCommentPlaceholder: 'Կիսվեք փորձով (ընտրովի)',
  reviewSubmit: 'Ուղարկել կարծիք',
  reviewRatingRequired: 'Նախ ընտրեք աստղերի գնահատական։',
  reviewSignInRequired: 'Կարծիք թողնելու համար մուտք գործեք։',
  reviewSubmitted: 'Շնորհակալություն — կարծիքը ուղարկված է։',
  dateLabel: 'Ամսաթիվ',
};

export const CONSUMER_COPY_RU: ConsumerCopy = {
  cancelBooking: 'Отменить запись',
  cancelBookingConfirm: 'Отменить эту запись? Это нельзя отменить.',
  cancelBookingFailed: 'Не удалось отменить запись',
  rescheduleBooking: 'Перенести',
  pickNewTime: 'Выберите новую дату и время',
  loadingSlots: 'Загрузка доступного времени…',
  noSlotsThisDay: 'На этот день нет свободного времени',
  timeSlotMorning: 'Утро',
  timeSlotAfternoon: 'День',
  timeSlotEvening: 'Вечер',
  confirmReschedule: 'Подтвердить новое время',
  submitting: 'Отправка…',
  rescheduleBookingFailed: 'Не удалось перенести запись',
  rescheduleSummary: 'Новое время: {date} в {time}',
  rescheduleSuccessDetail: 'Перенесено с {from} на {to}.',
  rescheduleCountHint: 'Использовано переносов: {count} из {max}',
  rescheduleUpdatedTitle: 'Запись обновлена',
  reschedulePreviousLabel: 'Было',
  rescheduleNewLabel: 'Стало',
  manageBookingTitle: 'Управление записью',
  manageBookingInvalidLink: 'Ссылка недействительна или истекла.',
  manageBookingSignInHint:
    'Войдите с тем же email, который использовали при оформлении, чтобы отменить или перенести запись.',
  signIn: 'Войти',
  signInWithGoogle: 'Войти через Google',
  cancelPackageVisit: 'Отменить весь пакетный визит',
  cancelPackageVisitConfirm:
    'Отменить все записи в этом пакетном визите? Это нельзя отменить.',
  cancelPackageVisitFailed: 'Не удалось отменить пакетный визит',
  reschedulePackageVisit: 'Перенести весь визит',
  reschedulePackageVisitSummary:
    'Перенести все {count} услуг на {date}, начало в {time}',
  reschedulePackageVisitSuccess: 'Визит перенесён с {from} на {to}.',
  packageNoBlock: 'Нет доступного визита в этот день для этого пакета',
  bookingStatusCancelled: 'Отменена',
  bookingStatusCompleted: 'Завершена',
  bookingStatusConfirmed: 'Подтверждена',
  packageVisitAppointmentCount: '{count} записей в этом визите',
  bookingConfirmed: 'Запись подтверждена',
  bookingConfirmedHint: 'Вы можете управлять этой записью в своём аккаунте.',
  youMightAlsoLike: 'Вам также может понравиться',
  dismissRecommendations: 'Скрыть рекомендации',
  learnMore: 'Подробнее',
  viewAppointments: 'Мои записи',
  bookAnotherService: 'Записаться ещё раз',
  checkoutSubtotal: 'Промежуточный итог',
  checkoutTotalDue: 'К оплате',
  checkoutPromoCode: 'Промокод или подарочная карта',
  checkoutPromoPlaceholder: 'Введите код',
  checkoutApplyPromo: 'Применить',
  checkoutPromoApplied: 'Применён: {code}',
  checkoutRemovePromo: 'Убрать',
  checkoutLoyaltyPoints: 'Бонусные баллы',
  checkoutLoyaltyBalance: 'Баланс: {points} балл. ({value})',
  checkoutLoyaltyMaxHint: 'Макс. {max} балл.',
  checkoutUseMaxPoints: 'Максимум',
  checkoutPromoDiscount: 'Скидка по промокоду',
  checkoutGiftCardDiscount: 'Подарочная карта',
  checkoutLoyaltyDiscount: 'Бонусные баллы',
  checkoutFreeAfterDiscounts: 'Итого',
  checkoutHowToBook: 'Как вы хотите записаться?',
  checkoutUseSubscription: 'Использовать абонемент',
  checkoutAppointmentsLeft: 'визитов осталось',
  checkoutExpiresOn: 'действует до',
  checkoutFreeThisVisit: '$0 за этот визит',
  checkoutOneTimeAppointment: 'Разовая запись',
  checkoutSubscribeAndSave: 'Абонемент со скидкой',
  checkoutChooseSubscriptionPlan: 'Выберите план абонемента',
  checkoutSaveAmount: 'экономия {amount}',
  checkoutSubscriptionPlanRequired: 'Выберите план абонемента',
  checkoutUsingSubscriptionHint: 'После этой записи останется {remaining} визитов',
  checkoutPlanIncludesHint: 'План включает {visits} визитов',
  checkoutSelectedTime: 'Выбранное время',
  checkoutBookingService: 'Услуга',
  checkoutEdit: 'Изменить',
  taxIncluded: 'включено',
  myResultsTab: 'Результаты',
  myResultsTitle: 'Мои результаты',
  myResultsEmpty:
    'Пока нет выпущенных результатов анализов. Они появятся здесь после того, как клиника их опубликует.',
  myResultsReleasedOn: 'Выпущен',
  myResultsUnnamed: 'Результат анализа',
  myResultsMeasurement: 'Тест',
  myResultsValue: 'Результат',
  myResultsReferenceRange: 'Референсный диапазон',
  myResultsFlag: 'Флаг',
  myResultsLoadFailed: 'Не удалось загрузить результаты анализов',
  myResultsSignInPrompt: 'Войдите, чтобы просмотреть результаты анализов в {name}.',
  myLabToBookTitle: 'Записи на забор',
  myLabToBookTab: 'Запись на забор',
  myLabToBookSignInPrompt: 'Войдите, чтобы увидеть ожидающие записи на забор в {name}.',
  homeLabToBookShortcut: 'Записаться на забор',
  homeLabToBookShortcutPending: 'Записаться на забор ({count} ожидают)',
  myLabToBookEmpty: 'Нет ожидающих записей на забор.',
  myLabToBookCollectionService: 'Записаться: {service}',
  myLabToBookRequestedOn: 'Запрошено {date}',
  myLabToBookBookCollection: 'Записаться на забор',
  myLabToBookLoadFailed: 'Не удалось загрузить запросы на запись',
  myLabToBookUnnamedOrder: 'Лабораторный заказ',
  myDocumentsTitle: 'Мои документы',
  myDocumentsEmpty:
    'Пока нет документов, доступных вам. Клиника публикует их здесь, когда они готовы.',
  myDocumentsOpenDocument: 'Открыть PDF',
  myDocumentsUnnamed: 'Документ',
  myDocumentsLoadFailed: 'Не удалось загрузить документы',
  myDocumentsCategoryLine: '{category} · {date}',
  myDocumentCategories: {
    lab_report: 'Лабораторный отчёт',
    referral_letter: 'Направление',
    imaging_report: 'Отчёт по визуализации',
    other: 'Другое',
  },
  resultStatusNotReceived: 'Не получен',
  resultStatusPending: 'В ожидании',
  resultStatusWaitingCompletion: 'Ожидание завершения',
  resultStatusCompleted: 'Завершён',
  resultStatusReviewed: 'Проверен',
  resultStatusAutomaticallyReviewed: 'Проверен автоматически',
  resultStatusReleased: 'Опубликован',
  resultStatusRejected: 'Отклонён',
  measurementFlagNormal: 'Норма',
  measurementFlagAbnormal: 'Отклонение',
  measurementFlagHigh: 'Выше нормы',
  measurementFlagLow: 'Ниже нормы',
  measurementFlagInconclusive: 'Неоднозначно',
  measurementFlagIndeterminate: 'Неопределённо',
  measurementFlagTestNotComplete: 'Тест не завершён',
  measurementFlagNotApplicable: 'Не применимо',
  measurementFlagSeeDetails: 'Подробнее',
  publicIntakeCheckoutTitle: 'Необязательная анкета перед визитом',
  publicIntakeCheckoutSubtitle:
    'Ответьте на несколько вопросов до оформления записи, чтобы лаборатория могла подготовиться.',
  publicIntakeSkip: 'Пропустить',
  publicIntakeStart: 'Начать анкету',
  publicIntakeContinue: 'Продолжить',
  publicIntakeAnswerLabel: 'Ваш ответ',
  publicIntakeUntitledQuestion: 'Вопрос без названия',
  publicIntakeLoadFailed: 'Не удалось загрузить анкету.',
  publicIntakeSubmitFailed: 'Не удалось сохранить ответ.',
  publicIntakeContinueToBooking: 'Перейти к оформлению',
  patientAlertsRegionLabel: 'Уведомления клиники',
  patientAlertsViewAction: 'Открыть',
  patientAlertsDismiss: 'Скрыть',
  patientAlertTitleReleased: 'Новый результат анализа',
  patientAlertTitleIntake: 'Анкета перед визитом не завершена',
  patientAlertTitleLabBooking: 'Нужно записаться на забор',
  patientAlertBodyReleased: '{testName} готов к просмотру.',
  patientAlertBodyIntake: '{questionnaireTitle} ещё требует ответов перед визитом.',
  patientAlertBodyLabBooking:
    'Запишитесь на {collectionServiceName} для назначенных анализов ({orderDisplayNames}).',
  assistantTitle: 'Помощник по записи',
  assistantHint: 'Спросите об услугах, свободном времени или ваших записях.',
  assistantHelpChip: 'Справка',
  assistantHelpChipHint: 'Показать подсказки по записи',
  assistantGuideExamples: 'Спросите о помощи:',
  assistantGuideStepOf: 'Шаг {current} из {total}',
  assistantGuideNextStep: 'Следующий шаг',
  assistantGuideOpenInApp: 'Открыть в приложении',
  assistantGuideStillStuck: 'Всё ещё не получается?',
  assistantPlaceholder: 'Задайте вопрос…',
  assistantThinking: 'Думаю…',
  assistantContinueBooking: 'Продолжить запись',
  assistantClose: 'Закрыть',
  assistantErrorGeneric: 'Что-то пошло не так. Попробуйте снова.',
  assistantExampleAvailable: 'Кто свободен завтра днём для {service}?',
  assistantExampleServices: 'Какие услуги вы предлагаете?',
  assistantExampleBook: 'Записаться на {service} в эту пятницу',
  assistantExampleLocation: 'Где вы находитесь?',
  assistantFallbackProvider: 'специалист',
  assistantFallbackService: 'услуга',
  assistantFallbackServiceCategory: 'наши услуги',
  assistantExampleGuideBook: 'Как записаться шаг за шагом?',
  assistantExampleGuideCheckout: 'Объясни шаги оформления и оплаты',
  assistantExampleGuideServices: 'Как выбрать услугу и специалиста?',
  assistantExampleGuideLocation: 'Где найти адрес и часы работы?',
  assistantDiscoverChipsTitle: 'Подбор услуг',
  ...buildDiscoverChipCopyFields('ru'),
  availableProvidersTitle: 'Доступные специалисты',
  bookProvider: 'Записаться',
  voiceStart: 'Голосовой ввод',
  voiceStop: 'Остановить',
  voiceUnsupported: 'Голосовой ввод не поддерживается на этом устройстве.',
  voiceDenied: 'Доступ к микрофону запрещён.',
  voiceNoSpeech: 'Речь не распознана. Попробуйте снова.',
  voiceError: 'Голосовой ввод не удался. Попробуйте снова.',
  speakReply: 'Прослушать',
  multiServiceBookedTitle: 'Записи подтверждены',
  multiServiceBookedHint: 'Ваш визит с несколькими услугами подтверждён.',
  multiServiceWithProvider: 'у {name}',
  multiServiceConfirmAction: 'Подтвердить запись',
  multiServicePaymentReturnHint:
    'Завершите оплату в браузере, затем вернитесь сюда, чтобы подтвердить запись.',
  multiServiceCompletePayment: 'Завершить оплату…',
  multiServiceConfirmPaymentReturn: 'Я оплатил(а)',
  multiServiceEntryCta: 'Записаться на несколько услуг',
  multiServiceSelectHint: 'Выберите одну услугу или две и более для записи за один визит.',
  multiServiceCart: 'Выбрано услуг: {count}',
  multiServiceTotal: '{duration} мин · {price}',
  multiServiceContinue: 'Продолжить с выбранными услугами',
  multiServiceAvailabilityTitle: 'Выберите дату и время',
  multiServicePickBlockHint: 'Выберите время, подходящее для всех выбранных услуг.',
  multiServiceEditServices: 'Изменить услуги',
  multiServiceEditProvider: 'Сменить специалиста',
  multiServiceConfirmTitle: 'Расписание ваших услуг',
  multiServiceScheduleEach: 'Выберите дату и время для каждой услуги.',
  multiServiceFindingSlots: 'Ищем свободное время…',
  multiServiceCheckoutTitle: 'Подтвердите визит',
  uncategorizedServices: 'Другие услуги',
  servicesSection: 'Услуги',
  selectSpecialist: 'Специалист',
  noTimesAvailable: 'На этот день нет свободного времени.',
  loadAvailableTimesFailed: 'Не удалось загрузить свободное время.',
  findAvailableBlockFailed: 'Не удалось найти свободный блок.',
  validateServiceSelectionFailed: 'Не удалось проверить выбранные услуги.',
  removeService: 'Удалить',
  bookAnother: 'Записаться снова',
  totalDue: 'К оплате',
  feedbackUp: 'Полезно',
  feedbackDown: 'Не полезно',
  feedbackThanks: 'Спасибо — это помогает улучшить ассистента.',
  feedbackReasonSkip: 'Пропустить',
  feedbackReasonWrongAction: 'Неверное действие',
  feedbackReasonWrongDate: 'Неверная дата',
  feedbackReasonWrongPerson: 'Неверный человек',
  feedbackReasonWrongService: 'Неверная услуга',
  feedbackReasonDidNotUnderstand: 'Не понял',
  postBookingSatisfactionTitle: 'Как прошла запись?',
  postBookingSatisfactionMessage:
    'Запись подтверждена. Короткая оценка поможет нам стать лучше — если есть минутка.',
  postBookingSatisfactionGreat: 'Отлично!',
  postBookingSatisfactionUnhappy: 'Могло быть лучше',
  postBookingSatisfactionDismiss: 'Не сейчас',
  postBookingReviewRateTitle: 'Оценить визит',
  postBookingReviewSubmitAction: 'Отправить отзыв',
  postBookingReviewSubmitFailed: 'Не удалось отправить отзыв. Попробуйте позже.',

  postBookingSupportTitle: 'Поддержка',
  postBookingSupportSubmitted:
    'Спасибо — команда салона получила обращение и ответит по email.',
  postBookingSupportFailed:
    'Не удалось создать обращение автоматически. Нажмите OK, чтобы открыть поддержку на сайте.',
  postBookingSupportUnavailable:
    'Поддержка для этого салона пока не настроена. Свяжитесь с салоном по email из подтверждения.',
  rewardsSectionTitle: 'Бонусы и акции',
  rewardsLoyaltyBalanceTitle: 'Ваш баланс бонусов',
  rewardsLoyaltyBalance: 'Доступно {amount}',
  rewardsLoyaltyEarnRate: 'Получайте {percent}% кэшбэка с подходящих визитов',
  rewardsPromosHint: 'Используйте эти коды при записи:',
  rewardsPromoMinimum: 'Минимальная сумма {amount}',
  rewardsPromoExpires: 'Действует до {date}',
  rewardsBookToRedeem: 'Записаться и использовать',
  rewardsSignInHint: 'Войдите, чтобы видеть баланс бонусов и персональные акции.',
  widgetNextAppointmentTitle: 'Следующая запись',
  widgetNextAppointmentSubtitle: '{date} · {time} · {provider}',
  widgetQuickRebookTitle: 'Записаться снова',
  widgetQuickRebookSubtitle: 'к {provider}',
  widgetSignedOutTitle: 'Войти в OptiSchedule Book',
  widgetSignedOutSubtitle: 'Смотрите визиты и перезапись в одно касание',
  notificationPrefsSectionTitle: 'Настройки уведомлений',
  notificationPrefsSectionHint:
    'Выберите, какие push-уведомления получать. Напоминания о записи включены по умолчанию, чтобы вы не пропустили визит.',
  notificationPrefsRemindersTitle: 'Напоминания о записи',
  notificationPrefsRemindersDescription:
    'Подтверждения, переносы и напоминания перед визитом.',
  notificationPrefsOffersTitle: 'Акции и повторная запись',
  notificationPrefsOffersDescription:
    'Промокоды, сообщения «мы скучаем» и подсказки записаться снова.',
  notificationPrefsNewsTitle: 'Новости салона',
  notificationPrefsNewsDescription:
    'Обновления, объявления и редкие сообщения от салона.',
  notificationPrefsLoadFailed: 'Не удалось загрузить настройки уведомлений.',
  notificationPrefsSaveFailed: 'Не удалось сохранить настройку. Попробуйте снова.',
  offlineStatusOffline: 'Вы offline. Изменения синхронизируются после подключения.',
  offlineStatusSyncing: 'Ожидает синхронизации: {count}',
  offlineCachedSalon: 'Показаны сохранённые данные салона с прошлого визита.',
  offlineMutationQueued: 'Сохранено offline — синхронизируем после подключения.',
  appGateTitle: 'Нужно обновление',
  appGateKillSwitchMessage: 'Эта версия приложения временно недоступна. Попробуйте позже.',
  appGateUpdateRequiredMessage: 'Обновите OptiSchedule Book, чтобы продолжить запись.',
  appGateUpdateNudgeMessage: 'Доступна новая версия OptiSchedule Book с улучшениями.',
  appGateUpdateAction: 'Обновить в магазине',
  appGateDismissAction: 'Не сейчас',
  analyticsConsentTitle: 'Согласие на аналитику',
  analyticsConsentMessage:
    'Помогите улучшить приложение с помощью анонимной аналитики. Личные данные не собираются.',
  analyticsConsentAccept: 'Принять',
  analyticsConsentDecline: 'Отклонить',
  pushPrimingTitle: 'Ваша запись подтверждена',
  pushPrimingBody:
    'Включите напоминания — мы сообщим о подтверждении записи и перед визитом.',
  pushPrimingAccept: 'Да, напомните',
  pushPrimingDecline: 'Не сейчас',
  pushProvisionalUpgradeTitle: 'Оставить напоминания?',
  pushProvisionalUpgradeBody:
    'Вы открыли напоминание — включите полные уведомления, чтобы обновления записи появлялись на экране блокировки.',
  pushProvisionalUpgradeAccept: 'Оставить напоминания',
  pushProvisionalUpgradeDecline: 'Не сейчас',
  pushSettingsReaskTitle: 'Снова включить уведомления',
  pushSettingsReaskBody:
    'Мы сможем напоминать о визитах только если уведомления включены в настройках.',
  pushSettingsReaskOpen: 'Открыть настройки',
  pushSettingsReaskSkip: 'Пропустить',
  postBookingSignInTitle: 'Сохраните запись в аккаунте',
  postBookingSignInBody:
    'Один тап через Apple или Google — гостевые записи объединяются автоматически. Можно пропустить и войти позже.',
  postBookingSignInGoogle: 'Продолжить с Google',
  postBookingSignInApple: 'Продолжить с Apple',
  postBookingSignInSkip: 'Позже',
  postBookingSignInBusy: 'Вход…',
  activationPaymentOptionalHint:
    'Оплата на месте — для первой записи онлайн-оплата необязательна.',
  activationPaymentHiccupMessage:
    'Онлайн-оплата не завершилась. Вы всё равно можете подтвердить запись и оплатить в салоне.',
  activationPayAtVenueFallbackAction: 'Подтвердить и оплатить на месте',
  activationPayAtVenueSelected:
    'Выбрана оплата на месте — подтвердите ниже, чтобы завершить запись.',
  activationConfirmBooking: 'Подтвердить запись',
  activationPayAtVisitConfirm: 'Подтвердить — оплата на месте',
  bookingDraftResumeConfirm: 'Продолжите запись — подтвердите время ниже.',
  bookingDraftResumeSlot: 'Продолжите запись — выберите время ниже.',
  bookingDraftResumeService: 'Продолжите незавершённую запись ниже.',
  networkFeedbackCreated: 'Сохранено',
  networkFeedbackUpdated: 'Обновлено',
  networkFeedbackDeleted: 'Удалено',
  networkFeedbackFailed: 'Что-то пошло не так. Проверьте подключение и попробуйте снова.',
  networkFeedbackFailedCreate: 'Не удалось выполнить запрос.',
  networkFeedbackFailedUpdate: 'Не удалось сохранить изменения.',
  networkFeedbackFailedDelete: 'Не удалось удалить.',
  networkRetryAction: 'Повторить',
  networkLoadFailed: 'Не удалось загрузить. Проверьте подключение и попробуйте снова.',
  growthSectionTitle: 'Записаться снова и поделиться',
  growthRebookTitle: 'Повторить прошлый визит',
  growthRebookSubtitle: '{service} · {provider}',
  growthRebookAction: 'Записаться',
  growthShareSalonTitle: 'Поделиться салоном',
  growthShareSalonAction: 'Поделиться ссылкой',
  growthShareBookingAction: 'Поделиться записью',
  growthReferTitle: 'Пригласить друга',
  growthReferSubtitle: 'Пригласите друзей — вы оба получите бонусы в {businessName}.',
  growthReferAction: 'Отправить приглашение',
  growthShareCopied: 'Ссылка скопирована.',
  growthShareUnavailable: 'Поделиться на этом устройстве нельзя.',
  growthShareRewardEarned: 'Вы получили {reward} за публикацию!',
  postBookingTenantReviewAction: 'Оценить визит',
  giftCardNav: 'Подарочные карты',
  giftCardTitle: 'Купить подарочную карту',
  giftCardSubtitle: 'Подарите заботу о себе — цифровая или физическая доставка.',
  giftCardChooseType: 'Что вы хотите подарить?',
  giftCardTypeMonetary: 'Сумма',
  giftCardTypeService: 'Услуга',
  giftCardTypeBundle: 'Набор',
  giftCardTypePackage: 'Пакет услуг',
  giftCardTypeSubscription: 'Абонемент',
  giftCardTypeDescMonetary: 'Сумма, которую можно потратить на любую запись.',
  giftCardTypeDescService: 'Одна или несколько отдельных услуг.',
  giftCardTypeDescBundle: 'Набор услуг, настроенный бизнесом.',
  giftCardTypeDescPackage: 'Существующий пакет этого бизнеса.',
  giftCardTypeDescSubscription: 'Существующий план абонемента.',
  giftCardAmountHint: 'Выберите сумму или введите свою.',
  giftCardSelectServicesHint: 'Выберите одну или несколько услуг.',
  giftCardSelectedServices: 'Выбрано услуг: {count}',
  giftCardContinueCheckout: 'Перейти к оплате',
  giftCardCheckoutTitle: 'Оплата подарочной карты',
  giftCardYourDetails: 'Ваши данные',
  giftCardRecipientSection: 'Получатель',
  giftCardBuyForSelf: 'Для себя',
  giftCardBuyAsGift: 'В подарок',
  giftCardPurchaserName: 'Ваше имя',
  giftCardPurchaserEmail: 'Ваш email (чек)',
  giftCardRecipientName: 'Имя получателя',
  giftCardRecipientEmail: 'Email получателя',
  giftCardRecipientPhone: 'Телефон получателя',
  giftCardPersonalMessage: 'Личное сообщение (необязательно)',
  giftCardDeliverySection: 'Доставка',
  giftCardDeliveryDigital: 'Цифровая',
  giftCardDeliveryPhysical: 'Физическая',
  giftCardAddressLine1: 'Адрес, строка 1',
  giftCardAddressLine2: 'Адрес, строка 2 (необязательно)',
  giftCardCity: 'Город',
  giftCardPostalCode: 'Почтовый индекс',
  giftCardCountry: 'Страна',
  giftCardDeliveryInstructions: 'Инструкции по доставке (необязательно)',
  giftCardShipping: 'Доставка',
  giftCardTotal: 'Промежуточный итог',
  giftCardTotalDue: 'К оплате',
  giftCardPayNow: 'Оплатить картой',
  giftCardConfirmCashPurchase: 'Подтвердить покупку',
  giftCardPayCashAtVisit: 'Оплатите {amount} при следующем визите.',
  giftCardSuccessTitle: 'Подарочная карта куплена!',
  giftCardSuccessBody: 'Детали отправлены на email.',
  giftCardQuoteFailed: 'Не удалось рассчитать цену.',
  giftCardCheckoutFailed: 'Не удалось начать оплату.',
  giftCardEmailRequired: 'Email покупателя обязателен.',
  giftCardPurchaserNameRequired: 'Введите ваше имя.',
  giftCardConsentRequired: 'Примите политику конфиденциальности.',
  giftCardPaymentFailed: 'Не удалось подтвердить оплату.',
  giftCardMyGiftCards: 'Мои подарочные карты',
  giftCardMyOrdered: 'Купленные карты',
  giftCardMyRedeemed: 'Активированные карты',
  giftCardNoOrders: 'Пока нет покупок подарочных карт.',
  giftCardNoRedeemed: 'Пока нет активированных карт.',
  giftCardRedeemSectionTitle: 'Активировать полученный подарок',
  giftCardClaimTitle: 'Активировать код на аккаунте',
  giftCardClaimHint: 'Вставьте код из email, чтобы добавить на аккаунт.',
  giftCardClaimPlaceholder: 'Код из email',
  giftCardClaimSubmit: 'Активировать код',
  giftCardClaimSuccess: 'Подарок успешно активирован.',
  giftCardClaimPackageSuccess: 'Пакет добавлен на ваш аккаунт.',
  giftCardClaimSubscriptionSuccess: 'Абонемент добавлен на ваш аккаунт.',
  giftCardClaimServiceSuccess: 'Подарок на услугу сохранён — используйте код при оплате.',
  giftCardClaimBundleSuccess: 'Подарок на набор сохранён — используйте код при оплате.',
  giftCardRedeemedHint: 'Активированные подарки отображаются здесь.',
  giftCardBookToUse: 'Записаться',
  giftCardCreditsRemaining: 'осталось',
  giftCardClaimedOn: 'Активирован {date}',
  giftCardRedeemedPackageHint: 'Запишитесь на визиты пакета со страницы услуг.',
  giftCardRedeemedSubscriptionHint: 'Абонемент активен на этом аккаунте.',
  giftCardRedeemedServiceHint: 'Используйте код при записи на подходящие услуги.',
  giftCardBalance: 'баланс',
  giftCardActive: 'Активна',
  giftCardInactive: 'Неактивна',
  giftCardCancelOrder: 'Отменить заказ',
  giftCardCancelWindow: 'Окно отмены',
  giftCardCancelConfirm: 'Запросить отмену этого заказа?',
  giftCardCancelSuccess: 'Запрос на отмену отправлен.',
  giftCardCancelRefunded: 'Заказ отменён и возвращён.',
  giftCardCancelRefundFailed: 'Отменено, но возврат не удался.',
  giftCardRequestStatus: 'Статус запроса',
  giftCardPackageBadge: 'Пакет',
  giftCardSaveBadge: 'Скидка {percent}%',
  giftCardSubscribeBadge: 'Подписка и экономия',
  giftCardSubscriptionAppointments: 'визитов',
  giftCardSubscriptionMonths: 'мес.',
  giftCardBundleSelected: 'Набор выбран',
  giftCardBuyGiftCard: 'Купить подарочную карту',
  giftCardStatusCancelled: 'Отменён',
  giftCardPrivacyConsent: 'Я согласен с политикой конфиденциальности.',
  giftCardPaymentMethod: 'Оплата',
  giftCardPayOnline: 'Онлайн',
  giftCardPayCashShort: 'При визите',
  packagesTitle: 'Пакеты',
  packageBadge: 'Пакет · Экономия {percent}%',
  packageIncludes: 'Включает: {list}',
  packageValidUntil: 'Предложение действует до {date}',
  packageShowDetails: 'Показать услуги',
  packageHideDetails: 'Скрыть детали',
  packageItemSave: 'Экономия {amount}',
  packageScheduleEach:
    'Все услуги пакета записываются подряд в один визит в тот же день',
  packageContinueCheckout: 'Перейти к оплате',
  schedulePackage: 'Записаться на пакет',
  packageCheckoutTitle: 'Подтвердить пакет',
  packageBookedTitle: 'Пакет записан',
  packageBookedHint: 'Ваши записи подтверждены.',
  packageIncludedServices: 'Включённые услуги',
  packagePayAndBook: 'Оплатить и записаться',
  packageBook: 'Записаться на пакет',
  packagePaymentReturnHint:
    'Завершите оплату в браузере, затем вернитесь сюда для подтверждения записи.',
  packageCompletePayment: 'Завершить оплату…',
  packageConfirmPaymentReturn: 'Я оплатил',
  chooseSpecialist: 'Выберите специалиста',
  specialistAiHint: 'Выберите мастера и время, затем услугу.',
  anySpecialist: 'Любой свободный специалист',
  anySpecialistHint: 'Сначала выберите услугу — мы подберём свободного специалиста.',
  selectDateTime: 'Выберите дату и время',
  selectService: 'Выберите услугу',
  nearestSlots: 'Доступно {date}',
  todayInline: 'Сегодня',
  noSlots: 'Сейчас нет свободных слотов',
  chooseThisProfessional: 'Выбрать этого специалиста',
  providerReviewsTitle: 'Отзывы клиентов',
  providerReviewSummary: '{rating} ({count} отзывов)',
  noProviderReviews: 'Пока нет отзывов.',
  availableSlots: 'Доступное время',
  bookAppointment: 'Записаться',
  profileViewDetails: 'Профиль салона',
  profileFollowUs: 'Мы в соцсетях',
  profileLocation: 'Адрес',
  profileSocialWebsite: 'Сайт',
  profileSocialInstagram: 'Instagram',
  profileSocialFacebook: 'Facebook',
  profileSocialX: 'X',
  profileSocialTiktok: 'TikTok',
  profileSocialLinkedin: 'LinkedIn',
  profileSocialYoutube: 'YouTube',
  growthBookAnotherWay: 'Записаться другим способом',
  growthBookOnline: 'Записаться онлайн',
  growthBookViaTelegram: 'Записаться через Telegram',
  growthBookViaWhatsApp: 'Записаться через WhatsApp',
  growthBookViaFacebook: 'Facebook',
  growthBookViaInstagram: 'Instagram',
  privacyDataTitle: 'Ваши данные и конфиденциальность',
  privacyExportMyData: 'Скачать мои данные',
  privacyDeleteMyData: 'Удалить данные аккаунта',
  privacyExportSuccess: 'Экспорт данных начался.',
  privacyExportCopied: 'Данные скопированы в буфер обмена.',
  privacyDeleteConfirm: 'Это навсегда удалит ваш профиль у этого бизнеса. Продолжить?',
  privacyDeleteSuccess: 'Ваши данные удалены.',
  privacyActionFailed: 'Что-то пошло не так. Попробуйте позже.',
  privacyLoading: 'Выполняется…',
  tourImagePlaceholder: 'Тур',
  tourPricePerPerson: '{price} / чел.',
  tourPerPersonSuffix: 'за человека',
  tourMaxGroup: 'До {count}',
  tourGroupSize: 'Размер группы',
  tourTravelersHint: '1–{max} путешественников',
  tourLineTotal: '{unit} × {count} = {total}',
  tourRemainingSpots: '{count} мест осталось',
  tourDayDeparture: 'Отправление',
  tourDifficultyEasy: 'Лёгкий',
  tourDifficultyModerate: 'Средний',
  tourDifficultyChallenging: 'Сложный',
  clinicServiceTypeConsultation: 'Консультация',
  clinicServiceTypeLabTest: 'Лабораторный анализ',
  clinicServiceTypeProcedure: 'Процедура',
  clinicFastingRequired: 'Требуется голодание',
  clinicSymptoms: 'Симптомы или причина визита',
  clinicSymptomsPlaceholder: 'Опишите симптомы (необязательно)',
  clinicReferralNotes: 'Примечания к направлению',
  clinicReferralNotesPlaceholder:
    'Направивший врач или результаты предыдущих анализов (необязательно)',
  subscriptionsTitle: 'Абонементы',
  subscriptionsEmpty: 'Абонементов пока нет.',
  subscriptionsFallbackName: 'Абонемент',
  subscriptionsVisitsLeft: 'Осталось {remaining} / {included} визитов',
  subscriptionsExpires: 'Действует до {date}',
  subscriptionsBookNext: 'Записаться на следующий визит',
  subscriptionsUsageHistory: 'История использования',
  subscriptionsNoUsage: 'Использований пока нет.',
  subscriptionUsagePurchase: 'План куплен',
  subscriptionUsageRedeem: 'Визит использован',
  subscriptionUsageExpire: 'Истёк',
  subscriptionUsageLine: '{action} · {date} · осталось {remaining}',
  assistantExampleSubscriptions: 'Сколько визитов осталось по абонементу?',
  assistantExampleRebook: 'Повторно записаться на прошлый визит',
  assistantExampleReferral: 'Как пригласить друга?',
  assistantExampleNotifications: 'Какие уведомления я получу?',
  assistantExampleSavedSalons: 'Показать мои сохранённые салоны',
  assistantExampleExportData: 'Как скачать мои персональные данные?',
  professionalsEntryCta: 'Сначала выберите специалиста',
  continueBooking: 'Продолжить запись',
  noServicesForSlot: 'На это время нет доступных услуг.',
  professionalFallbackName: 'Специалист',
  providerNotFound: 'Специалист не найден.',
  reviewYourRating: 'Ваша оценка',
  reviewCommentPlaceholder: 'Расскажите о визите (необязательно)',
  reviewSubmit: 'Отправить отзыв',
  reviewRatingRequired: 'Сначала выберите оценку.',
  reviewSignInRequired: 'Войдите, чтобы оставить отзыв.',
  reviewSubmitted: 'Спасибо — отзыв отправлен.',
  dateLabel: 'Дата',
};

const CATALOG: Record<ConsumerLocale, ConsumerCopy> = {
  en: CONSUMER_COPY_EN,
  hy: CONSUMER_COPY_HY,
  ru: CONSUMER_COPY_RU,
};

export function getConsumerCopy(locale: ConsumerLocale): ConsumerCopy {
  return CATALOG[locale];
}

export const CONSUMER_COPY_LOCALES: ConsumerLocale[] = ['en', 'hy', 'ru'];
