import type { ConsumerCopy } from './consumer-copy.types.js';
import type { ConsumerLocale } from './tenant-locale.js';

const DOCUMENT_CATEGORIES = {
  lab_report: 'Lab report',
  referral_letter: 'Referral letter',
  imaging_report: 'Imaging report',
  other: 'Other',
} as const;

export const CONSUMER_COPY_EN: ConsumerCopy = {
  cancelBooking: 'Cancel appointment',
  cancelBookingConfirm: 'Cancel this appointment?',
  cancelBookingFailed: 'Could not cancel appointment',
  rescheduleBooking: 'Reschedule',
  pickNewTime: 'Pick a new time',
  loadingSlots: 'Loading times…',
  noSlotsThisDay: 'No times available this day',
  confirmReschedule: 'Confirm reschedule',
  submitting: 'Saving…',
  rescheduleBookingFailed: 'Could not reschedule',
  rescheduleSummary: 'New time: {date} at {time}',
  rescheduleSuccessDetail: 'Rescheduled from {from} to {to}.',
  rescheduleCountHint: 'Rescheduled {count} of {max} times',
  rescheduleUpdatedTitle: 'Appointment updated',
  reschedulePreviousLabel: 'Previous',
  rescheduleNewLabel: 'New',
  manageBookingTitle: 'Manage appointment',
  manageBookingInvalidLink: 'This manage link is invalid or expired.',
  manageBookingSignInHint: 'Sign in to manage from your account.',
  signIn: 'Sign in',
  signInWithGoogle: 'Sign in with Google',
  cancelPackageVisit: 'Cancel package visit',
  cancelPackageVisitConfirm: 'Cancel all appointments in this package visit?',
  cancelPackageVisitFailed: 'Could not cancel package visit',
  reschedulePackageVisit: 'Reschedule package visit',
  reschedulePackageVisitSummary: 'New block: {date} at {time} ({count} services)',
  reschedulePackageVisitSuccess: 'Package visit rescheduled from {from} to {to}.',
  packageNoBlock: 'No package block available',
  bookingStatusCancelled: 'Cancelled',
  bookingStatusCompleted: 'Completed',
  bookingStatusConfirmed: 'Confirmed',
  packageVisitAppointmentCount: '{count} appointments',
  bookingConfirmed: 'Booking confirmed!',
  bookingConfirmedHint: 'You can manage this appointment from your account.',
  youMightAlsoLike: 'You might also like',
  dismissRecommendations: 'Dismiss recommendations',
  learnMore: 'Learn more',
  viewAppointments: 'View appointments',
  bookAnotherService: 'Book another service',
  checkoutSubtotal: 'Subtotal',
  checkoutTotalDue: 'Due now',
  taxIncluded: 'included',
  myResultsTab: 'Results',
  myResultsTitle: 'My results',
  myResultsEmpty:
    'No released lab results yet. Results appear here after your clinic releases them.',
  myResultsReleasedOn: 'Released',
  myResultsUnnamed: 'Lab result',
  myResultsMeasurement: 'Test',
  myResultsValue: 'Result',
  myResultsReferenceRange: 'Reference range',
  myResultsFlag: 'Flag',
  myResultsLoadFailed: 'Could not load your lab results',
  myResultsSignInPrompt: 'Sign in to view your lab results at {name}.',
  myLabToBookTitle: 'Lab to book',
  myLabToBookTab: 'Lab to book',
  myLabToBookSignInPrompt: 'Sign in to view pending lab collection requests at {name}.',
  homeLabToBookShortcut: 'Lab collection to book',
  homeLabToBookShortcutPending: 'Lab collection to book ({count} pending)',
  myLabToBookEmpty: 'No pending lab collection appointments.',
  myLabToBookCollectionService: 'Book: {service}',
  myLabToBookRequestedOn: 'Requested {date}',
  myLabToBookBookCollection: 'Book collection',
  myLabToBookLoadFailed: 'Could not load lab booking requests',
  myLabToBookUnnamedOrder: 'Lab order',
  myDocumentsTitle: 'My documents',
  myDocumentsEmpty:
    'No documents shared with you yet. Your clinic releases documents here when they are ready.',
  myDocumentsOpenDocument: 'Open PDF',
  myDocumentsUnnamed: 'Document',
  myDocumentsLoadFailed: 'Could not load your documents',
  myDocumentsCategoryLine: '{category} · {date}',
  myDocumentCategories: { ...DOCUMENT_CATEGORIES },
  resultStatusNotReceived: 'Not received',
  resultStatusPending: 'Pending',
  resultStatusWaitingCompletion: 'Waiting completion',
  resultStatusCompleted: 'Completed',
  resultStatusReviewed: 'Reviewed',
  resultStatusAutomaticallyReviewed: 'Automatically reviewed',
  resultStatusReleased: 'Released',
  resultStatusRejected: 'Rejected',
  measurementFlagNormal: 'Normal',
  measurementFlagAbnormal: 'Abnormal',
  measurementFlagHigh: 'High',
  measurementFlagLow: 'Low',
  measurementFlagInconclusive: 'Inconclusive',
  measurementFlagIndeterminate: 'Indeterminate',
  measurementFlagTestNotComplete: 'Test not completed',
  measurementFlagNotApplicable: 'Not applicable',
  measurementFlagSeeDetails: 'See details',
  publicIntakeCheckoutTitle: 'Optional pre-visit questionnaire',
  publicIntakeCheckoutSubtitle:
    'Answer a few questions before checkout to help the lab prepare for your visit.',
  publicIntakeSkip: 'Skip for now',
  publicIntakeStart: 'Start questionnaire',
  publicIntakeContinue: 'Continue',
  publicIntakeAnswerLabel: 'Your answer',
  publicIntakeUntitledQuestion: 'Question',
  publicIntakeLoadFailed: 'Could not load intake form.',
  publicIntakeSubmitFailed: 'Could not save your answer.',
  publicIntakeContinueToBooking: 'Continue to booking',
  patientAlertsRegionLabel: 'Clinic alerts',
  patientAlertsViewAction: 'View',
  patientAlertsDismiss: 'Dismiss',
  patientAlertTitleReleased: 'New lab result',
  patientAlertTitleIntake: 'Pre-visit intake incomplete',
  patientAlertTitleLabBooking: 'Lab collection to book',
  patientAlertBodyReleased: '{testName} is ready to view.',
  patientAlertBodyIntake: '{questionnaireTitle} still needs answers before your visit.',
  patientAlertBodyLabBooking:
    'Book your {collectionServiceName} for ordered labs ({orderDisplayNames}).',
  assistantTitle: 'Booking assistant',
  assistantHint: 'Ask about services, availability, or your appointments.',
  assistantPlaceholder: 'Ask anything…',
  assistantThinking: 'Thinking…',
  feedbackUp: 'Helpful',
  feedbackDown: 'Not helpful',
  feedbackThanks: 'Thanks — this helps improve the assistant.',
  feedbackReasonSkip: 'Skip',
  feedbackReasonWrongAction: 'Wrong action',
  feedbackReasonWrongDate: 'Wrong date',
  feedbackReasonWrongPerson: 'Wrong person',
  feedbackReasonWrongService: 'Wrong service',
  feedbackReasonDidNotUnderstand: "Didn't understand",
  postBookingSatisfactionTitle: 'How was your booking?',
  postBookingSatisfactionMessage:
    'Your appointment is confirmed. A quick rating helps us improve — only if you have a moment.',
  postBookingSatisfactionGreat: 'Great!',
  postBookingSatisfactionUnhappy: 'Could be better',
  postBookingSatisfactionDismiss: 'Not now',
  postBookingReviewRateTitle: 'Rate your visit',
  postBookingReviewSubmitAction: 'Submit review',
  postBookingReviewSubmitFailed: 'Could not submit your review. Try again later.',
  postBookingSupportTitle: 'Support',
  postBookingSupportSubmitted:
    'Thanks — the salon team has been notified and will follow up by email.',
  postBookingSupportFailed:
    'We could not open a ticket automatically. Tap OK to contact support on the web.',
  postBookingSupportUnavailable:
    'Support is not configured for this salon yet. You can reach them from your confirmation email.',
  rewardsSectionTitle: 'Rewards & offers',
  rewardsLoyaltyBalanceTitle: 'Your rewards balance',
  rewardsLoyaltyBalance: '{amount} available',
  rewardsLoyaltyEarnRate: 'Earn {percent}% back on eligible visits',
  rewardsPromosHint: 'Use these codes when you book:',
  rewardsPromoMinimum: 'Minimum spend {amount}',
  rewardsPromoExpires: 'Expires {date}',
  rewardsBookToRedeem: 'Book to redeem',
  rewardsSignInHint: 'Sign in to see your rewards balance and exclusive offers.',
  widgetNextAppointmentTitle: 'Next appointment',
  widgetNextAppointmentSubtitle: '{date} · {time} with {provider}',
  widgetQuickRebookTitle: 'Book again',
  widgetQuickRebookSubtitle: 'with {provider} · {time}',
  widgetSignedOutTitle: 'Sign in to OptiSchedule',
  widgetSignedOutSubtitle: 'See upcoming visits and rebook in one tap',
  notificationPrefsSectionTitle: 'Notification preferences',
  notificationPrefsSectionHint:
    'Choose what push notifications you want. Appointment reminders stay on by default so you do not miss your visit.',
  notificationPrefsRemindersTitle: 'Appointment reminders',
  notificationPrefsRemindersDescription:
    'Confirmations, schedule changes, and reminders before your visit.',
  notificationPrefsOffersTitle: 'Offers & rebook tips',
  notificationPrefsOffersDescription:
    'Promo codes, win-back messages, and nudges to book your usual service again.',
  notificationPrefsNewsTitle: 'Salon news',
  notificationPrefsNewsDescription:
    'Updates, announcements, and occasional engagement messages from the salon.',
  notificationPrefsLoadFailed: 'Could not load notification preferences.',
  notificationPrefsSaveFailed: 'Could not save your preference. Try again.',
  offlineStatusOffline: 'You are offline. Booking changes will sync when you reconnect.',
  offlineStatusSyncing: '{count} change(s) waiting to sync…',
  offlineCachedSalon: 'Showing saved salon info from your last visit.',
  offlineMutationQueued: 'Saved offline — we will sync when you are back online.',
  appGateTitle: 'Update required',
  appGateKillSwitchMessage: 'This app version is temporarily unavailable. Please try again later.',
  appGateUpdateRequiredMessage: 'Please update OptiSchedule to continue booking.',
  appGateUpdateNudgeMessage: 'A newer version of OptiSchedule is available with improvements.',
  appGateUpdateAction: 'Update in the app store',
  appGateDismissAction: 'Not now',
  analyticsConsentTitle: 'Analytics consent',
  analyticsConsentMessage:
    'Help us improve the app with anonymous usage analytics. No personal data is collected.',
  analyticsConsentAccept: 'Accept',
  analyticsConsentDecline: 'Decline',
  pushPrimingTitle: 'Your slot is confirmed',
  pushPrimingBody:
    'Turn on reminders and we will notify you when bookings are confirmed and before your appointment.',
  pushPrimingAccept: 'Yes, remind me',
  pushPrimingDecline: 'Not now',
  pushProvisionalUpgradeTitle: 'Keep these reminders on?',
  pushProvisionalUpgradeBody:
    'You opened a reminder — turn on full notifications so booking updates appear on your lock screen.',
  pushProvisionalUpgradeAccept: 'Keep reminders on',
  pushProvisionalUpgradeDecline: 'Not now',
  pushSettingsReaskTitle: 'Turn notifications back on',
  pushSettingsReaskBody:
    'We can only remind you about upcoming visits when notifications are enabled in Settings.',
  pushSettingsReaskOpen: 'Open Settings',
  pushSettingsReaskSkip: 'Skip',
  postBookingSignInTitle: 'Save this booking to your account',
  postBookingSignInBody:
    'One tap with Apple or Google — guest bookings merge automatically. You can skip and sign in later.',
  postBookingSignInGoogle: 'Continue with Google',
  postBookingSignInApple: 'Continue with Apple',
  postBookingSignInSkip: 'Maybe later',
  postBookingSignInBusy: 'Signing in…',
  activationPaymentOptionalHint:
    'Pay at your visit — online payment is optional for your first booking.',
  activationPaymentHiccupMessage:
    'Online payment did not complete. You can still confirm and pay at the salon.',
  activationPayAtVenueFallbackAction: 'Confirm and pay at visit instead',
  activationPayAtVenueSelected: 'Pay at visit selected — confirm below to complete your booking.',
  activationConfirmBooking: 'Confirm booking',
  activationPayAtVisitConfirm: 'Confirm — pay at visit',
  bookingDraftResumeConfirm: 'Continue your booking — confirm the time below.',
  bookingDraftResumeSlot: 'Continue your booking — pick a time below.',
  bookingDraftResumeService: 'Continue your unfinished booking below.',
  networkFeedbackCreated: 'Saved',
  networkFeedbackUpdated: 'Updated',
  networkFeedbackDeleted: 'Removed',
  networkFeedbackFailed: 'Something went wrong. Check your connection and try again.',
  networkFeedbackFailedCreate: 'Could not complete request.',
  networkFeedbackFailedUpdate: 'Could not save changes.',
  networkFeedbackFailedDelete: 'Could not remove item.',
  networkRetryAction: 'Try again',
  networkLoadFailed: 'Could not load. Check your connection and try again.',
  growthSectionTitle: 'Book again & share',
  growthRebookTitle: 'Book your last visit again',
  growthRebookSubtitle: '{service} with {provider} · {time}',
  growthRebookAction: 'Rebook now',
  growthShareSalonTitle: 'Share this salon',
  growthShareSalonAction: 'Share link',
  growthShareBookingAction: 'Share booking',
  growthReferTitle: 'Refer a friend',
  growthReferSubtitle: 'Invite friends — you both earn rewards at {businessName}.',
  growthReferAction: 'Send invite',
  growthShareCopied: 'Link copied to clipboard.',
  growthShareUnavailable: 'Sharing is not available on this device.',
  postBookingTenantReviewAction: 'Rate your visit',
};

export const CONSUMER_COPY_HY: ConsumerCopy = {
  cancelBooking: 'Չեղարկել ամրագրումը',
  cancelBookingConfirm: 'Չեղարկել այս հանդիպումը՞։ Սա չի կարող հետարկվել։',
  cancelBookingFailed: 'Չհաջողվեց չեղարկել հանդիպումը',
  rescheduleBooking: 'Փոխել ժամանակը',
  pickNewTime: 'Ընտրեք նոր ամսաթիվ և ժամ',
  loadingSlots: 'Բեռնվում են հասանելի ժամերը…',
  noSlotsThisDay: 'Այս օրը հասանելի ժամեր չկան',
  confirmReschedule: 'Հաստատել նոր ժամանակը',
  submitting: 'Ուղարկվում է…',
  rescheduleBookingFailed: 'Չհաջողվեց փոխել ժամանակը',
  rescheduleSummary: 'Նոր ժամ՝ {date} ժամը {time}',
  rescheduleSuccessDetail: 'Տեղափոխվել է {from}-ից դեպի {to}',
  rescheduleCountHint: '{count}/{max} վերապլանավորում օգտագործված է',
  rescheduleUpdatedTitle: 'Ամրագրումը թարմացվել է',
  reschedulePreviousLabel: 'Նախորդ',
  rescheduleNewLabel: 'Նոր',
  manageBookingTitle: 'Կառավարեք ձեր հանդիպումը',
  manageBookingInvalidLink: 'Այս հղումը անվավեր է կամ ժամկետանց',
  manageBookingSignInHint:
    'Մուտք գործեք նույն էլ. փոստով, որով կատարել եք ամրագրումը',
  signIn: 'Մուտք գործել',
  signInWithGoogle: 'Մուտք գործել Google-ով',
  cancelPackageVisit: 'Չեղարկել ամբողջ փաթեթային այցը',
  cancelPackageVisitConfirm:
    'Չեղարկել այս փաթեթային այցի բոլոր հանդիպումները՞։ Սա չի կարող հետարկվել։',
  cancelPackageVisitFailed: 'Չհաջողվեց չեղարկել փաթեթային այցը',
  reschedulePackageVisit: 'Վերապլանավորել ամբողջ այցը',
  reschedulePackageVisitSummary:
    'Տեղափոխել բոլոր {count} ծառայությունները դեպի {date}՝ սկսած {time}-ից',
  reschedulePackageVisitSuccess: 'Այցը տեղափոխվեց {from}-ից դեպի {to}',
  packageNoBlock: 'Այս փաթեթի համար հասանելի այց չի գտնվել',
  bookingStatusCancelled: 'Չեղարկված',
  bookingStatusCompleted: 'Ավարտված',
  bookingStatusConfirmed: 'Հաստատված',
  packageVisitAppointmentCount: '{count} հանդիպում այս այցում',
  bookingConfirmed: 'Ամրագրումը կատարված է',
  bookingConfirmedHint: 'Կարող եք կառավարել այս ամրագրումը ձեր հաշվից',
  youMightAlsoLike: 'Դուք կարող եք նաև հավանել',
  dismissRecommendations: 'Թաքցնել առաջարկները',
  learnMore: 'Իմանալ ավելին',
  viewAppointments: 'Դիտել ամրագրումները',
  bookAnotherService: 'Ամրագրել ևս մեկը',
  checkoutSubtotal: 'Ենթագումար',
  checkoutTotalDue: 'Վճարման ենթակա',
  taxIncluded: 'ներառված',
  myResultsTab: 'Արդյունքներ',
  myResultsTitle: 'Իմ արդյունքները',
  myResultsEmpty:
    'Ազատված լաբորատոր արդյունքներ դեռ չկան։ Դրանք կհայտնվեն այստեղ, երբ կլինիկան ազատի արդյունքները։',
  myResultsReleasedOn: 'Ազատված',
  myResultsUnnamed: 'Լաբորատոր արդյունք',
  myResultsMeasurement: 'Թեստ',
  myResultsValue: 'Արդյունք',
  myResultsReferenceRange: 'Նորմայի միջակայք',
  myResultsFlag: 'Դրոշ',
  myResultsLoadFailed: 'Չհաջողվեց բեռնել լաբորատոր արդյունքները',
  myResultsSignInPrompt: 'Մուտք գործեք՝ {name}-ում լաբորատոր արդյունքները դիտելու համար',
  myLabToBookTitle: 'Ամրագրելիք լաբորատոր հավաքումներ',
  myLabToBookTab: 'Լաբ. հավաքում',
  myLabToBookSignInPrompt: 'Մուտք գործեք՝ {name}-ում սպասող լաբորատոր հավաքման հարցումները տեսնելու համար։',
  homeLabToBookShortcut: 'Ամրագրել լաբորատոր հավաքում',
  homeLabToBookShortcutPending: 'Ամրագրել լաբորատոր հավաքում ({count} սպասող)',
  myLabToBookEmpty: 'Սպասող լաբորատոր հավաքման ամրագրումներ չկան։',
  myLabToBookCollectionService: 'Ամրագրել՝ {service}',
  myLabToBookRequestedOn: 'Հարցում՝ {date}',
  myLabToBookBookCollection: 'Ամրագրել հավաքում',
  myLabToBookLoadFailed: 'Չհաջողվեց բեռնել լաբորատոր ամրագրումների հարցումները',
  myLabToBookUnnamedOrder: 'Լաբորատոր պատվեր',
  myDocumentsTitle: 'Իմ փաստաթղթերը',
  myDocumentsEmpty:
    'Դեռ փաստաթղթեր չեն հրապարակվել։ Դրանք կհայտնվեն այստեղ, երբ կլինիկան ազատի դրանք։',
  myDocumentsOpenDocument: 'Բացել PDF',
  myDocumentsUnnamed: 'Փաստաթուղթ',
  myDocumentsLoadFailed: 'Չհաջողվեց բեռնել փաստաթղթերը',
  myDocumentsCategoryLine: '{category} · {date}',
  myDocumentCategories: {
    lab_report: 'Լաբորատոր հաշվետվություն',
    referral_letter: 'Ուղղորդում',
    imaging_report: 'Ուղղորդված պատկեր',
    other: 'Այլ',
  },
  resultStatusNotReceived: 'Չի ստացվել',
  resultStatusPending: 'Սպասման մեջ',
  resultStatusWaitingCompletion: 'Սպասում է ավարտին',
  resultStatusCompleted: 'Ավարտված',
  resultStatusReviewed: 'Վերանայված',
  resultStatusAutomaticallyReviewed: 'Ավտոմատ վերանայված',
  resultStatusReleased: 'Հրապարակված',
  resultStatusRejected: 'Մերժված',
  measurementFlagNormal: 'Նորմալ',
  measurementFlagAbnormal: 'Աննորմալ',
  measurementFlagHigh: 'Բարձր',
  measurementFlagLow: 'Ցածր',
  measurementFlagInconclusive: 'Անորոշելի',
  measurementFlagIndeterminate: 'Անորոշ',
  measurementFlagTestNotComplete: 'Թեստը ավարտված չէ',
  measurementFlagNotApplicable: 'Կիրառելի չէ',
  measurementFlagSeeDetails: 'Տես մանրամասները',
  publicIntakeCheckoutTitle: 'Նախապոստ այցի ընտրովի հարցաթերթիկ',
  publicIntakeCheckoutSubtitle:
    'Պատասխանեք մի քանի հարցի՝ գրանցումից առաջ, որպեսզի լաբորատորիան պատրաստվի ձեր այցին։',
  publicIntakeSkip: 'Բաց թողնել',
  publicIntakeStart: 'Սկսել հարցաթերթիկը',
  publicIntakeContinue: 'Շարունակել',
  publicIntakeAnswerLabel: 'Ձեր պատասխանը',
  publicIntakeUntitledQuestion: 'Անվերնագիր հարց',
  publicIntakeLoadFailed: 'Չհաջողվեց բեռնել հարցաթերթիկը։',
  publicIntakeSubmitFailed: 'Չհաջողվեց պահպանել պատասխանը։',
  publicIntakeContinueToBooking: 'Շարունակել գրանցումը',
  patientAlertsRegionLabel: 'Կլինիկայի ծանուցումներ',
  patientAlertsViewAction: 'Դիտել',
  patientAlertsDismiss: 'Փակել',
  patientAlertTitleReleased: 'Նոր լաբորատոր արդյունք',
  patientAlertTitleIntake: 'Նախայցային հարցաթերթիկը incomplete է',
  patientAlertTitleLabBooking: 'Լաբորատոր հավաքում ամրագրել',
  patientAlertBodyReleased: '{testName}-ը պատրաստ է դիտման համար։',
  patientAlertBodyIntake: '{questionnaireTitle}-ը դեռ պահանջում է պատասխաններ այցից առաջ։',
  patientAlertBodyLabBooking:
    'Ամրագրեք {collectionServiceName} պատվիրած թեստերի համար ({orderDisplayNames})։',
  assistantTitle: 'Ամրագրման օգնական',
  assistantHint: 'Հարցրեք ծառայությունների, ազատ ժամերի կամ ձեր ամրագրումների մասին։',
  assistantPlaceholder: 'Գրեք հարց…',
  assistantThinking: 'Մտածում է…',
  feedbackUp: 'Օգտակար',
  feedbackDown: 'Ոչ օգտակար',
  feedbackThanks: 'Շնորհակալություն — դա օգնում է բարելավել օգնականին։',
  feedbackReasonSkip: 'Բաց թողնել',
  feedbackReasonWrongAction: 'Սխալ գործողություն',
  feedbackReasonWrongDate: 'Սխալ ամսաթիվ',
  feedbackReasonWrongPerson: 'Սխալ անձ',
  feedbackReasonWrongService: 'Սխալ ծառայություն',
  feedbackReasonDidNotUnderstand: 'Չհասկացավ',
  postBookingSatisfactionTitle: 'Ինչպե՞ս էր ձեր ամրագրումը',
  postBookingSatisfactionMessage:
    'Ձեր հանդիպումը հաստատված է։ Կարճ գնահատականը օգնում է մեզ բարելավվել — միայն եթե ունեք րոպե։',
  postBookingSatisfactionGreat: 'Հիանալի!',
  postBookingSatisfactionUnhappy: 'Կարող էր ավելի լավ լինել',
  postBookingSatisfactionDismiss: 'Ոչ հիմա',
  postBookingReviewRateTitle: 'Գնահատել այցը',
  postBookingReviewSubmitAction: 'Ուղարկել կարծիքը',
  postBookingReviewSubmitFailed: 'Չհաջողվեց ուղարկել կարծիքը։ Փորձեք ավելի ուշ։',

  postBookingSupportTitle: 'Աջակցություն',
  postBookingSupportSubmitted:
    'Շնորհակալություն — սրահի թիմը տեղեկացվել է և կկապվի էլ. փոստով։',
  postBookingSupportFailed:
    'Չհաջողվեց ավտոմատ կերպով դիմում բացել։ Սեղմեք OK՝ աջակցությունը կայքում բացելու համար։',
  postBookingSupportUnavailable:
    'Այս սրահի համար աջակցությունը դեռ կարգավորված չէ։ Կարող եք կապվել հաստատման էլ. փոստով։',
  rewardsSectionTitle: 'Պարգևներ և առաջարկներ',
  rewardsLoyaltyBalanceTitle: 'Ձեր պարգևների մնացորդը',
  rewardsLoyaltyBalance: '{amount} հասանելի',
  rewardsLoyaltyEarnRate: 'Ստացեք {percent}% bonus հարկավոր այցերից',
  rewardsPromosHint: 'Օգտագործեք այս կոդերը ամրագրելիս.',
  rewardsPromoMinimum: 'Նվազագույն գնում {amount}',
  rewardsPromoExpires: 'Վավեր է մինչև {date}',
  rewardsBookToRedeem: 'Ամրագրել օգտագործելու համար',
  rewardsSignInHint: 'Մուտք գործեք՝ պարգևների մնացորդը և առաջարկները տեսնելու համար.',
  widgetNextAppointmentTitle: 'Հաջորդ հանդիպում',
  widgetNextAppointmentSubtitle: '{date} · {time} · {provider}',
  widgetQuickRebookTitle: 'Կրկին ամրագրել',
  widgetQuickRebookSubtitle: '{provider}-ի հետ',
  widgetSignedOutTitle: 'Մուտք OptiSchedule',
  widgetSignedOutSubtitle: 'Տեսեք առաջիկա այցերը և ամրագրեք մեկ հպումով',
  notificationPrefsSectionTitle: 'Ծանուցումների կարգավորումներ',
  notificationPrefsSectionHint:
    'Ընտրեք, թե ինչ push ծանուցումներ եք ցանկանում։ Հանդիպման հիշեցումները լռելյայն միացված են, որպեսզի այցը չկորցնեք։',
  notificationPrefsRemindersTitle: 'Հանդիպման հիշեցումներ',
  notificationPrefsRemindersDescription:
    'Հաստատումներ, փոփոխված ժամանակներ և այցից առաջ հիշեցումներ։',
  notificationPrefsOffersTitle: 'Առաջարկներ և կրկին ամրագրում',
  notificationPrefsOffersDescription:
    'Պրոմո կոդեր, վերադարձի հաղորդագրություններ և սովորական ծառայությունը կրկին ամրագրելու հուշումներ։',
  notificationPrefsNewsTitle: 'Սրահի նորություններ',
  notificationPrefsNewsDescription:
    'Թարմացումներ, հայտարարություններ և երբեմնի ներգրավման հաղորդագրություններ։',
  notificationPrefsLoadFailed: 'Չհաջողվեց բեռնել ծանուցումների կարգավորումները։',
  notificationPrefsSaveFailed: 'Չհաջողվեց պահպանել կարգավորումը։ Կրկին փորձեք։',
  offlineStatusOffline: 'Դուք offline եք։ Փոփոխությունները կհամաժամացվեն կապի վերականգնումից հետո։',
  offlineStatusSyncing: '{count} փոփոխություն սպասում է համաժամացման…',
  offlineCachedSalon: 'Ցուցադրվում է salon-ի պահպանված տեղեկատվությունը։',
  offlineMutationQueued: 'Պահպանվել է offline — կհամաժամացվի կապի վերականգնումից հետո։',
  appGateTitle: 'Պահանջվում է թարմացում',
  appGateKillSwitchMessage: 'Այս տարբերակը ժամանակավորապես անհասանելի է։ Փորձեք ավելի ուշ։',
  appGateUpdateRequiredMessage: 'Թարմացրեք OptiSchedule-ը՝ շարունակելու համար։',
  appGateUpdateNudgeMessage: 'OptiSchedule-ի նոր տարբերակը հասանելի է բարելավումներով։',
  appGateUpdateAction: 'Թարմացնել store-ում',
  appGateDismissAction: 'Ոչ հիմա',
  analyticsConsentTitle: 'Վերլուծության համաձայնություն',
  analyticsConsentMessage:
    'Օգնեք բարելավել հավելվածը անանուն օգտագործման վերլուծությամբ։ Անձնական տվյալներ չեն հավաքվում։',
  analyticsConsentAccept: 'Ընդունել',
  analyticsConsentDecline: 'Մերժել',
  pushPrimingTitle: 'Ձեր ժամանակահատվածը հաստատված է',
  pushPrimingBody:
    'Միացրեք հիշեցումները, և մենք կտեղեկացնենք ամրագրումների և այցից առաջ։',
  pushPrimingAccept: 'Այո, հիշեցրեք',
  pushPrimingDecline: 'Ոչ հիմա',
  pushProvisionalUpgradeTitle: 'Միացնե՞լ հիշեցումները',
  pushProvisionalUpgradeBody:
    'Դուք բացեցիք հիշեցում — միացրեք ամբողջական ծանուցումները, որպեսզի գրանծման թարմացումները երևան էկրանին։',
  pushProvisionalUpgradeAccept: 'Միացնել հիշեցումները',
  pushProvisionalUpgradeDecline: 'Ոչ հիմա',
  pushSettingsReaskTitle: 'Կրկին միացրեք ծանուցումները',
  pushSettingsReaskBody:
    'Մենք կարող ենք հիշեցնել մոտ approaching այցեր միայն Settings-ում ծանուցումները միացված լինելու դեպքում։',
  pushSettingsReaskOpen: 'Բացել Settings',
  pushSettingsReaskSkip: 'Բաց թողնել',
  postBookingSignInTitle: 'Պահպանեք այս ամրագրումը ձեր հաշվում',
  postBookingSignInBody:
    'Մեկ հպում Apple-ով կամ Google-ով — հյուրի ամրագրումները ավտոմատ միանում են։ Կարող եք բաց թողնել և մուտք գործել ավելի ուշ։',
  postBookingSignInGoogle: 'Շարունակել Google-ով',
  postBookingSignInApple: 'Շարունակել Apple-ով',
  postBookingSignInSkip: 'Ավելի ուշ',
  postBookingSignInBusy: 'Մուտք գործում…',
  activationPaymentOptionalHint:
    'Վճարեք այցի ժամանակ — առցանց վճարումը պարտադիր չէ ձեր առաջին ամրագրման համար։',
  activationPaymentHiccupMessage:
    'Առցանց վճարումը չի ավարտվել։ Դուք դեռ կարող եք հաստատել և վճարել սրահում։',
  activationPayAtVenueFallbackAction: 'Հաստատել և վճարել այցի ժամանակ',
  activationPayAtVenueSelected:
    'Ընտրված է «վճարել այցի ժամանակ» — հաստատեք ստորև՝ ամրագրումն ավարտելու համար։',
  activationConfirmBooking: 'Հաստատել ամրագրումը',
  activationPayAtVisitConfirm: 'Հաստատել — վճարել այցի ժամանակ',
  bookingDraftResumeConfirm: 'Շարունակեք ամրագրումը — հաստատեք ժամանակը ստորև։',
  bookingDraftResumeSlot: 'Շարունակեք ամրագրումը — ընտրեք ժամանակը ստորև։',
  bookingDraftResumeService: 'Շարունակեք ձեր չավարտված ամրագրումը ստորև։',
  networkFeedbackCreated: 'Պահպանված',
  networkFeedbackUpdated: 'Թարմացված',
  networkFeedbackDeleted: 'Հեռացված',
  networkFeedbackFailed: 'Սխալ է տեղի ունեցել։ Ստուգեք կապը և փորձեք կրկին։',
  networkFeedbackFailedCreate: 'Հնարավոր չեղավ ավարտել հարցումը։',
  networkFeedbackFailedUpdate: 'Հնարավոր չեղավ պահպանել փոփոխությունները։',
  networkFeedbackFailedDelete: 'Հնարավոր չեղավ հեռացնել։',
  networkRetryAction: 'Կրկին փորձել',
  networkLoadFailed: 'Չհաջողվեց բեռնել։ Ստուգեք կապը և փորձեք կրկին։',
  growthSectionTitle: 'Կրկին ամրագրել և կիսվել',
  growthRebookTitle: 'Կրկին ամրագրել վերջին այցը',
  growthRebookSubtitle: '{service} · {provider}',
  growthRebookAction: 'Ամրագրել հիմա',
  growthShareSalonTitle: 'Կիսվել սalon-ով',
  growthShareSalonAction: 'Կիսվել հղումով',
  growthShareBookingAction: 'Կիսվել ամրագրումով',
  growthReferTitle: 'Ուղղորդել ընկերոջ',
  growthReferSubtitle: 'Հրավիրեք ընկերներ — {businessName}-ում երկուսդ էլ կստանաք պարգևներ։',
  growthReferAction: 'Ուղարկել հրավեր',
  growthShareCopied: 'Հղումը պատճենված է։',
  growthShareUnavailable: 'Այս սարքում կիսվելը հասանելի չէ։',
  postBookingTenantReviewAction: 'Գնահատել այցը',
};

export const CONSUMER_COPY_RU: ConsumerCopy = {
  cancelBooking: 'Отменить запись',
  cancelBookingConfirm: 'Отменить эту запись? Это нельзя отменить.',
  cancelBookingFailed: 'Не удалось отменить запись',
  rescheduleBooking: 'Перенести',
  pickNewTime: 'Выберите новую дату и время',
  loadingSlots: 'Загрузка доступного времени…',
  noSlotsThisDay: 'На этот день нет свободного времени',
  confirmReschedule: 'Подтвердить новое время',
  submitting: 'Отправка…',
  rescheduleBookingFailed: 'Не удалось перенести запись',
  rescheduleSummary: 'Новое время: {date} в {time}',
  rescheduleSuccessDetail: 'Перенесено с {from} на {to}.',
  rescheduleCountHint: 'Использовано переносов: {count} из {max}',
  rescheduleUpdatedTitle: 'Запись обновлена',
  reschedulePreviousLabel: 'Было',
  rescheduleNewLabel: 'Стало',
  manageBookingTitle: 'Управление записью',
  manageBookingInvalidLink: 'Ссылка недействительна или истекла.',
  manageBookingSignInHint:
    'Войдите с тем же email, который использовали при оформлении, чтобы отменить или перенести запись.',
  signIn: 'Войти',
  signInWithGoogle: 'Войти через Google',
  cancelPackageVisit: 'Отменить весь пакетный визит',
  cancelPackageVisitConfirm:
    'Отменить все записи в этом пакетном визите? Это нельзя отменить.',
  cancelPackageVisitFailed: 'Не удалось отменить пакетный визит',
  reschedulePackageVisit: 'Перенести весь визит',
  reschedulePackageVisitSummary:
    'Перенести все {count} услуг на {date}, начало в {time}',
  reschedulePackageVisitSuccess: 'Визит перенесён с {from} на {to}.',
  packageNoBlock: 'Нет доступного визита в один день для этого пакета',
  bookingStatusCancelled: 'Отменена',
  bookingStatusCompleted: 'Завершена',
  bookingStatusConfirmed: 'Подтверждена',
  packageVisitAppointmentCount: '{count} записей в этом визите',
  bookingConfirmed: 'Запись подтверждена',
  bookingConfirmedHint: 'Вы можете управлять этой записью в своём аккаунте.',
  youMightAlsoLike: 'Вам также может понравиться',
  dismissRecommendations: 'Скрыть рекомендации',
  learnMore: 'Подробнее',
  viewAppointments: 'Мои записи',
  bookAnotherService: 'Записаться ещё раз',
  checkoutSubtotal: 'Промежуточный итог',
  checkoutTotalDue: 'К оплате',
  taxIncluded: 'включено',
  myResultsTab: 'Результаты',
  myResultsTitle: 'Мои результаты',
  myResultsEmpty:
    'Пока нет выпущенных результатов анализов. Они появятся здесь после того, как клиника их опубликует.',
  myResultsReleasedOn: 'Выпущен',
  myResultsUnnamed: 'Результат анализа',
  myResultsMeasurement: 'Тест',
  myResultsValue: 'Результат',
  myResultsReferenceRange: 'Референсный диапазон',
  myResultsFlag: 'Флаг',
  myResultsLoadFailed: 'Не удалось загрузить результаты анализов',
  myResultsSignInPrompt: 'Войдите, чтобы просмотреть результаты анализов в {name}.',
  myLabToBookTitle: 'Записи на забор',
  myLabToBookTab: 'Запись на забор',
  myLabToBookSignInPrompt: 'Войдите, чтобы увидеть ожидающие записи на забор в {name}.',
  homeLabToBookShortcut: 'Записаться на забор',
  homeLabToBookShortcutPending: 'Записаться на забор ({count} ожидают)',
  myLabToBookEmpty: 'Нет ожидающих записей на забор.',
  myLabToBookCollectionService: 'Записаться: {service}',
  myLabToBookRequestedOn: 'Запрошено {date}',
  myLabToBookBookCollection: 'Записаться на забор',
  myLabToBookLoadFailed: 'Не удалось загрузить запросы на запись',
  myLabToBookUnnamedOrder: 'Лабораторный заказ',
  myDocumentsTitle: 'Мои документы',
  myDocumentsEmpty:
    'Пока нет документов, доступных вам. Клиника публикует их здесь, когда они готовы.',
  myDocumentsOpenDocument: 'Открыть PDF',
  myDocumentsUnnamed: 'Документ',
  myDocumentsLoadFailed: 'Не удалось загрузить документы',
  myDocumentsCategoryLine: '{category} · {date}',
  myDocumentCategories: {
    lab_report: 'Лабораторный отчёт',
    referral_letter: 'Направление',
    imaging_report: 'Отчёт по визуализации',
    other: 'Другое',
  },
  resultStatusNotReceived: 'Не получен',
  resultStatusPending: 'В ожидании',
  resultStatusWaitingCompletion: 'Ожидание завершения',
  resultStatusCompleted: 'Завершён',
  resultStatusReviewed: 'Проверен',
  resultStatusAutomaticallyReviewed: 'Проверен автоматически',
  resultStatusReleased: 'Опубликован',
  resultStatusRejected: 'Отклонён',
  measurementFlagNormal: 'Норма',
  measurementFlagAbnormal: 'Отклонение',
  measurementFlagHigh: 'Выше нормы',
  measurementFlagLow: 'Ниже нормы',
  measurementFlagInconclusive: 'Неоднозначно',
  measurementFlagIndeterminate: 'Неопределённо',
  measurementFlagTestNotComplete: 'Тест не завершён',
  measurementFlagNotApplicable: 'Не применимо',
  measurementFlagSeeDetails: 'Подробнее',
  publicIntakeCheckoutTitle: 'Необязательная анкета перед визитом',
  publicIntakeCheckoutSubtitle:
    'Ответьте на несколько вопросов до оформления записи, чтобы лаборатория могла подготовиться.',
  publicIntakeSkip: 'Пропустить',
  publicIntakeStart: 'Начать анкету',
  publicIntakeContinue: 'Продолжить',
  publicIntakeAnswerLabel: 'Ваш ответ',
  publicIntakeUntitledQuestion: 'Вопрос без названия',
  publicIntakeLoadFailed: 'Не удалось загрузить анкету.',
  publicIntakeSubmitFailed: 'Не удалось сохранить ответ.',
  publicIntakeContinueToBooking: 'Перейти к оформлению',
  patientAlertsRegionLabel: 'Уведомления клиники',
  patientAlertsViewAction: 'Открыть',
  patientAlertsDismiss: 'Скрыть',
  patientAlertTitleReleased: 'Новый результат анализа',
  patientAlertTitleIntake: 'Анкета перед визитом не завершена',
  patientAlertTitleLabBooking: 'Нужно записаться на забор',
  patientAlertBodyReleased: '{testName} готов к просмотру.',
  patientAlertBodyIntake: '{questionnaireTitle} ещё требует ответов перед визитом.',
  patientAlertBodyLabBooking:
    'Запишитесь на {collectionServiceName} для назначенных анализов ({orderDisplayNames}).',
  assistantTitle: 'Помощник по записи',
  assistantHint: 'Спросите об услугах, свободном времени или ваших записях.',
  assistantPlaceholder: 'Задайте вопрос…',
  assistantThinking: 'Думаю…',
  feedbackUp: 'Полезно',
  feedbackDown: 'Не полезно',
  feedbackThanks: 'Спасибо — это помогает улучшить ассистента.',
  feedbackReasonSkip: 'Пропустить',
  feedbackReasonWrongAction: 'Неверное действие',
  feedbackReasonWrongDate: 'Неверная дата',
  feedbackReasonWrongPerson: 'Неверный человек',
  feedbackReasonWrongService: 'Неверная услуга',
  feedbackReasonDidNotUnderstand: 'Не понял',
  postBookingSatisfactionTitle: 'Как прошла запись?',
  postBookingSatisfactionMessage:
    'Запись подтверждена. Короткая оценка поможет нам стать лучше — если есть минутка.',
  postBookingSatisfactionGreat: 'Отлично!',
  postBookingSatisfactionUnhappy: 'Могло быть лучше',
  postBookingSatisfactionDismiss: 'Не сейчас',
  postBookingReviewRateTitle: 'Оценить визит',
  postBookingReviewSubmitAction: 'Отправить отзыв',
  postBookingReviewSubmitFailed: 'Не удалось отправить отзыв. Попробуйте позже.',

  postBookingSupportTitle: 'Поддержка',
  postBookingSupportSubmitted:
    'Спасибо — команда салона получила обращение и ответит по email.',
  postBookingSupportFailed:
    'Не удалось создать обращение автоматически. Нажмите OK, чтобы открыть поддержку на сайте.',
  postBookingSupportUnavailable:
    'Поддержка для этого салона пока не настроена. Свяжитесь с салоном по email из подтверждения.',
  rewardsSectionTitle: 'Бонусы и акции',
  rewardsLoyaltyBalanceTitle: 'Ваш баланс бонусов',
  rewardsLoyaltyBalance: 'Доступно {amount}',
  rewardsLoyaltyEarnRate: 'Получайте {percent}% кэшбэка с подходящих визитов',
  rewardsPromosHint: 'Используйте эти коды при записи:',
  rewardsPromoMinimum: 'Минимальная сумма {amount}',
  rewardsPromoExpires: 'Действует до {date}',
  rewardsBookToRedeem: 'Записаться и использовать',
  rewardsSignInHint: 'Войдите, чтобы видеть баланс бонусов и персональные акции.',
  widgetNextAppointmentTitle: 'Следующая запись',
  widgetNextAppointmentSubtitle: '{date} · {time} · {provider}',
  widgetQuickRebookTitle: 'Записаться снова',
  widgetQuickRebookSubtitle: 'к {provider}',
  widgetSignedOutTitle: 'Войти в OptiSchedule',
  widgetSignedOutSubtitle: 'Смотрите визиты и перезапись в одно касание',
  notificationPrefsSectionTitle: 'Настройки уведомлений',
  notificationPrefsSectionHint:
    'Выберите, какие push-уведомления получать. Напоминания о записи включены по умолчанию, чтобы вы не пропустили визит.',
  notificationPrefsRemindersTitle: 'Напоминания о записи',
  notificationPrefsRemindersDescription:
    'Подтверждения, переносы и напоминания перед визитом.',
  notificationPrefsOffersTitle: 'Акции и повторная запись',
  notificationPrefsOffersDescription:
    'Промокоды, сообщения «мы скучаем» и подсказки записаться снова.',
  notificationPrefsNewsTitle: 'Новости салона',
  notificationPrefsNewsDescription:
    'Обновления, объявления и редкие сообщения от салона.',
  notificationPrefsLoadFailed: 'Не удалось загрузить настройки уведомлений.',
  notificationPrefsSaveFailed: 'Не удалось сохранить настройку. Попробуйте снова.',
  offlineStatusOffline: 'Вы offline. Изменения синхронизируются после подключения.',
  offlineStatusSyncing: 'Ожидает синхронизации: {count}',
  offlineCachedSalon: 'Показаны сохранённые данные салона с прошлого визита.',
  offlineMutationQueued: 'Сохранено offline — синхронизируем после подключения.',
  appGateTitle: 'Нужно обновление',
  appGateKillSwitchMessage: 'Эта версия приложения временно недоступна. Попробуйте позже.',
  appGateUpdateRequiredMessage: 'Обновите OptiSchedule, чтобы продолжить запись.',
  appGateUpdateNudgeMessage: 'Доступна новая версия OptiSchedule с улучшениями.',
  appGateUpdateAction: 'Обновить в магазине',
  appGateDismissAction: 'Не сейчас',
  analyticsConsentTitle: 'Согласие на аналитику',
  analyticsConsentMessage:
    'Помогите улучшить приложение с помощью анонимной аналитики. Личные данные не собираются.',
  analyticsConsentAccept: 'Принять',
  analyticsConsentDecline: 'Отклонить',
  pushPrimingTitle: 'Ваша запись подтверждена',
  pushPrimingBody:
    'Включите напоминания — мы сообщим о подтверждении записи и перед визитом.',
  pushPrimingAccept: 'Да, напомните',
  pushPrimingDecline: 'Не сейчас',
  pushProvisionalUpgradeTitle: 'Оставить напоминания?',
  pushProvisionalUpgradeBody:
    'Вы открыли напоминание — включите полные уведомления, чтобы обновления записи появлялись на экране блокировки.',
  pushProvisionalUpgradeAccept: 'Оставить напоминания',
  pushProvisionalUpgradeDecline: 'Не сейчас',
  pushSettingsReaskTitle: 'Снова включить уведомления',
  pushSettingsReaskBody:
    'Мы сможем напоминать о визитах только если уведомления включены в настройках.',
  pushSettingsReaskOpen: 'Открыть настройки',
  pushSettingsReaskSkip: 'Пропустить',
  postBookingSignInTitle: 'Сохраните запись в аккаунте',
  postBookingSignInBody:
    'Один тап через Apple или Google — гостевые записи объединяются автоматически. Можно пропустить и войти позже.',
  postBookingSignInGoogle: 'Продолжить с Google',
  postBookingSignInApple: 'Продолжить с Apple',
  postBookingSignInSkip: 'Позже',
  postBookingSignInBusy: 'Вход…',
  activationPaymentOptionalHint:
    'Оплата на месте — для первой записи онлайн-оплата необязательна.',
  activationPaymentHiccupMessage:
    'Онлайн-оплата не завершилась. Вы всё равно можете подтвердить запись и оплатить в салоне.',
  activationPayAtVenueFallbackAction: 'Подтвердить и оплатить на месте',
  activationPayAtVenueSelected:
    'Выбрана оплата на месте — подтвердите ниже, чтобы завершить запись.',
  activationConfirmBooking: 'Подтвердить запись',
  activationPayAtVisitConfirm: 'Подтвердить — оплата на месте',
  bookingDraftResumeConfirm: 'Продолжите запись — подтвердите время ниже.',
  bookingDraftResumeSlot: 'Продолжите запись — выберите время ниже.',
  bookingDraftResumeService: 'Продолжите незавершённую запись ниже.',
  networkFeedbackCreated: 'Сохранено',
  networkFeedbackUpdated: 'Обновлено',
  networkFeedbackDeleted: 'Удалено',
  networkFeedbackFailed: 'Что-то пошло не так. Проверьте подключение и попробуйте снова.',
  networkFeedbackFailedCreate: 'Не удалось выполнить запрос.',
  networkFeedbackFailedUpdate: 'Не удалось сохранить изменения.',
  networkFeedbackFailedDelete: 'Не удалось удалить.',
  networkRetryAction: 'Повторить',
  networkLoadFailed: 'Не удалось загрузить. Проверьте подключение и попробуйте снова.',
  growthSectionTitle: 'Записаться снова и поделиться',
  growthRebookTitle: 'Повторить прошлый визит',
  growthRebookSubtitle: '{service} · {provider}',
  growthRebookAction: 'Записаться',
  growthShareSalonTitle: 'Поделиться салоном',
  growthShareSalonAction: 'Поделиться ссылкой',
  growthShareBookingAction: 'Поделиться записью',
  growthReferTitle: 'Пригласить друга',
  growthReferSubtitle: 'Пригласите друзей — вы оба получите бонусы в {businessName}.',
  growthReferAction: 'Отправить приглашение',
  growthShareCopied: 'Ссылка скопирована.',
  growthShareUnavailable: 'Поделиться на этом устройстве нельзя.',
  postBookingTenantReviewAction: 'Оценить визит',
};

const CATALOG: Record<ConsumerLocale, ConsumerCopy> = {
  en: CONSUMER_COPY_EN,
  hy: CONSUMER_COPY_HY,
  ru: CONSUMER_COPY_RU,
};

export function getConsumerCopy(locale: ConsumerLocale): ConsumerCopy {
  return CATALOG[locale];
}

export const CONSUMER_COPY_LOCALES: ConsumerLocale[] = ['en', 'hy', 'ru'];
