/** adopt-5.6 — adoption UI surfaces requiring EN/HY/RU copy + a11y hooks. */

export const CONSUMER_ADOPTION_COPY_KEYS = [
  'appGateTitle',
  'appGateKillSwitchMessage',
  'appGateUpdateRequiredMessage',
  'appGateUpdateNudgeMessage',
  'appGateUpdateAction',
  'appGateDismissAction',
  'offlineStatusOffline',
  'offlineStatusSyncing',
  'offlineCachedSalon',
  'offlineMutationQueued',
  'networkLoadFailed',
  'networkRetryAction',
  'networkFeedbackCreated',
  'networkFeedbackUpdated',
  'networkFeedbackDeleted',
  'networkFeedbackFailed',
  'networkFeedbackFailedCreate',
  'networkFeedbackFailedUpdate',
  'networkFeedbackFailedDelete',
  'analyticsConsentTitle',
  'analyticsConsentMessage',
  'analyticsConsentAccept',
  'analyticsConsentDecline',
  'pushPrimingTitle',
  'pushPrimingBody',
  'pushPrimingAccept',
  'pushPrimingDecline',
  'postBookingSatisfactionTitle',
  'postBookingSatisfactionMessage',
  'postBookingSatisfactionGreat',
  'postBookingSatisfactionUnhappy',
  'postBookingSatisfactionDismiss',
  'postBookingReviewRateTitle',
  'postBookingReviewSubmitAction',
  'postBookingReviewSubmitFailed',
  'postBookingSupportTitle',
  'postBookingSupportSubmitted',
  'postBookingSupportFailed',
  'postBookingSupportUnavailable',
] as const;

export const CONSUMER_ADOPTION_A11Y_SURFACES = [
  { file: 'components/AppVersionGate.tsx', needles: ['aria-modal', 'role="dialog"'] },
  { file: 'components/AppUpdateNudgeBanner.tsx', needles: ['role="status"'] },
  { file: 'components/ConsumerOfflineBanner.tsx', needles: ['role="status"', 'aria-live="polite"'] },
  { file: 'components/ConsumerNetworkErrorCard.tsx', needles: ['role="alert"'] },
  { file: 'components/OperationFeedbackHost.tsx', needles: ['aria-live="polite"'] },
  { file: 'components/AppAnalyticsBootstrap.tsx', needles: ['role="dialog"', 'aria-modal="true"'] },
  { file: 'components/PushOptInPrimingPrompt.tsx', needles: ['IonAlert'] },
  { file: 'components/PostVisitReviewPrompt.tsx', needles: ['IonAlert', 'IonModal'] },
] as const;
