import type { PushPermissionState } from './push-reachability.util.js';

export const VALUE_FIRST_PRIMING_ELIGIBILITY_SCENARIOS = [
  {
    id: 'first-booking-native-fcm',
    completedBookingCount: 1,
    isNative: true,
    isFcmBuild: true,
    permission: 'provisional' as PushPermissionState,
    primingShown: false,
    expected: true,
  },
  {
    id: 'android-prompt-first-booking',
    completedBookingCount: 1,
    isNative: true,
    isFcmBuild: true,
    permission: 'prompt' as PushPermissionState,
    primingShown: false,
    expected: true,
  },
  {
    id: 'skip-after-first-booking',
    completedBookingCount: 2,
    isNative: true,
    isFcmBuild: true,
    permission: 'provisional' as PushPermissionState,
    primingShown: false,
    expected: false,
  },
  {
    id: 'skip-when-already-full',
    completedBookingCount: 1,
    isNative: true,
    isFcmBuild: true,
    permission: 'full' as PushPermissionState,
    primingShown: false,
    expected: false,
  },
  {
    id: 'skip-web',
    completedBookingCount: 1,
    isNative: false,
    isFcmBuild: true,
    permission: 'unknown' as PushPermissionState,
    primingShown: false,
    expected: false,
  },
] as const;

export const POST_BOOKING_PUSH_FLOW_SCENARIOS = [
  {
    id: 'value-first-priming-after-first-booking',
    platform: 'ios' as const,
    completedBookingCount: 1,
    isNative: true,
    isFcmBuild: true,
    permission: 'provisional' as PushPermissionState,
    engagedProvisional: false,
    reaskShown: false,
    expected: 'value_first_priming' as const,
  },
  {
    id: 'android-defers-os-until-priming',
    platform: 'android' as const,
    completedBookingCount: 1,
    isNative: true,
    isFcmBuild: true,
    permission: 'prompt' as PushPermissionState,
    engagedProvisional: false,
    reaskShown: false,
    expected: 'value_first_priming' as const,
  },
  {
    id: 'settings-reask-on-second-booking-denied',
    platform: 'ios' as const,
    completedBookingCount: 2,
    isNative: true,
    isFcmBuild: true,
    permission: 'denied' as PushPermissionState,
    engagedProvisional: false,
    reaskShown: false,
    expected: 'settings_reask' as const,
  },
  {
    id: 'provisional-upgrade-when-engaged',
    platform: 'ios' as const,
    completedBookingCount: 1,
    isNative: true,
    isFcmBuild: true,
    permission: 'provisional' as PushPermissionState,
    engagedProvisional: true,
    reaskShown: false,
    expected: 'provisional_upgrade' as const,
  },
  {
    id: 'android-fallback-without-priming',
    platform: 'android' as const,
    completedBookingCount: 1,
    isNative: true,
    isFcmBuild: false,
    permission: 'prompt' as PushPermissionState,
    engagedProvisional: false,
    reaskShown: false,
    expected: 'android_post_booking_permission' as const,
  },
  {
    id: 'none-when-already-full',
    platform: 'android' as const,
    completedBookingCount: 1,
    isNative: true,
    isFcmBuild: true,
    permission: 'full' as PushPermissionState,
    engagedProvisional: false,
    reaskShown: false,
    expected: 'none' as const,
  },
] as const;

export const DEFER_OS_PERMISSION_SCENARIOS = [
  {
    id: 'defer-when-priming-eligible',
    primingEligible: true,
    expected: true,
  },
  {
    id: 'allow-fallback-without-priming',
    primingEligible: false,
    expected: false,
  },
] as const;
