require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorFirebaseAuthentication', :path => '../../node_modules/@capacitor-firebase/authentication'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  pod 'CapacitorFirebaseAuthentication/Google', :path => '../../node_modules/@capacitor-firebase/authentication'
end

post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      config.build_settings['ENABLE_MODULE_VERIFIER'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      if target.respond_to?(:product_type) && target.product_type == 'com.apple.product-type.bundle'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end

  frameworks_script = File.join(installer.sandbox.root, 'Target Support Files/Pods-App/Pods-App-frameworks.sh')
  if File.exist?(frameworks_script)
    text = File.read(frameworks_script)
    unless text.include?('xattr -cr')
      text = text.sub(
        "code_sign_if_enabled() {",
        "code_sign_if_enabled() {\n  xattr -cr \"$1\" 2>/dev/null || true"
      )
      File.write(frameworks_script, text)
    end
  end
end
