/** Generated by scripts/sync-mobile-guide-flows.mjs — do not edit. */
import type {
  GuideFlowOverlayBundle,
  GuideFlowPlaybookDef,
  MobileGuideBundle,
  MobileGuideOfflineManifest,
} from '@mobile-guide/mobile-guide.types.ts';
import playbook_0 from '../../assets/guide-flows/customer/account.json';
import playbook_1 from '../../assets/guide-flows/customer/activation-confirm.json';
import playbook_2 from '../../assets/guide-flows/customer/activation-salon.json';
import playbook_3 from '../../assets/guide-flows/customer/activation-service.json';
import playbook_4 from '../../assets/guide-flows/customer/activation-slot.json';
import playbook_5 from '../../assets/guide-flows/customer/activation-welcome.json';
import playbook_6 from '../../assets/guide-flows/customer/assistant.json';
import playbook_7 from '../../assets/guide-flows/customer/booking-flow.json';
import playbook_8 from '../../assets/guide-flows/customer/getting-started.json';
import playbook_9 from '../../assets/guide-flows/customer/packages-gift-cards.json';
import playbook_10 from '../../assets/guide-flows/customer/tabs.json';
import overlay_0 from '../../assets/guide-flows/overlays/clinic.json';
import overlay_1 from '../../assets/guide-flows/overlays/retail.json';
import overlay_2 from '../../assets/guide-flows/overlays/tour.json';
import guideFlowsI18n from '../../assets/guide-flows-i18n.json';
import guideFlowsManifest from '../../assets/guide-flows-manifest.json';

export const MOBILE_GUIDE_OFFLINE_MANIFEST = guideFlowsManifest as MobileGuideOfflineManifest;

export const MOBILE_GUIDE_BUNDLE: MobileGuideBundle = {
  surface: 'customer',
  playbooks: [playbook_0, playbook_1, playbook_2, playbook_3, playbook_4, playbook_5, playbook_6, playbook_7, playbook_8, playbook_9, playbook_10] as GuideFlowPlaybookDef[],
  overlays: [overlay_0, overlay_1, overlay_2] as GuideFlowOverlayBundle[],
  i18n: guideFlowsI18n as MobileGuideBundle['i18n'],
};
